/**
 * data-root-2.js — 語根データ（-scrib-/-script-, -vert-/-vers-, -dict-, -struct-, -rupt-）
 * 形式: { word, meaning, etymology, root, level }
 * level: 0=beginner 1=intermediate 2=advanced 3=master
 */
(function(){
  var d = [
  // ── -scrib-/-script-（書く） ──────────────────
  {word:"describe",      meaning:"描写する・説明する",    etymology:"de（下に）+ scribe（書く）",               root:"-scrib-", level:0, pos:"動詞"},
  {word:"prescribe",     meaning:"処方する・規定する",    etymology:"pre（前に）+ scribe（書く）",              root:"-scrib-", level:2, pos:"動詞"},
  {word:"subscribe",     meaning:"購読する・同意する",    etymology:"sub（下に）+ scribe（書く）",              root:"-scrib-", level:1, pos:"動詞"},
  {word:"inscribe",      meaning:"刻む・書き記す",        etymology:"in（中に）+ scribe（書く）",               root:"-scrib-", level:2, pos:"動詞"},
  {word:"transcribe",    meaning:"書き写す・文字化する",  etymology:"trans（越えて）+ scribe（書く）",          root:"-scrib-", level:2, pos:"動詞"},
  {word:"circumscribe",  meaning:"制限する・囲む",        etymology:"circum（周囲に）+ scribe（書く）",         root:"-scrib-", level:2, pos:"動詞"},
  {word:"proscribe",     meaning:"禁じる・追放する",      etymology:"pro（前に）+ scribe（書く）",              root:"-scrib-", level:3, pos:"動詞"},
  {word:"ascribe",       meaning:"〜のせいにする・帰する",etymology:"a（〜に）+ scribe（書く）",               root:"-scrib-", level:2, pos:"動詞"},
  {word:"scripture",     meaning:"聖書・聖典",            etymology:"script（書く）+ ure（結果）",              root:"-scrib-", level:1, pos:"名詞"},
  {word:"script",        meaning:"脚本・手書き文字",      etymology:"script（書かれたもの）",                  root:"-scrib-", level:0, pos:"名詞"},
  {word:"description",   meaning:"説明・描写",            etymology:"de（下に）+ scription（書く）",            root:"-scrib-", level:1, pos:"名詞"},
  {word:"prescription",  meaning:"処方箋",                etymology:"pre（前に）+ scription（書く）",           root:"-scrib-", level:1, pos:"名詞"},
  {word:"subscription",  meaning:"購読・定期購読",        etymology:"sub（下に）+ scription（書く）",           root:"-scrib-", level:1, pos:"名詞"},
  {word:"inscription",   meaning:"碑文・刻印",            etymology:"in（中に）+ scription（書く）",            root:"-scrib-", level:2, pos:"名詞"},
  {word:"transcription", meaning:"書き取り・転写",        etymology:"trans（越えて）+ scription（書く）",       root:"-scrib-", level:2, pos:"名詞"},
  {word:"manuscript",    meaning:"原稿・写本",            etymology:"manu（手）+ script（書く）",               root:"-scrib-", level:2, pos:"名詞"},
  {word:"postscript",    meaning:"追伸・後記",            etymology:"post（後に）+ script（書く）",             root:"-scrib-", level:2, pos:"名詞"},
  {word:"conscript",     meaning:"徴兵する・徴兵された人",etymology:"con（共に）+ script（書く）",              root:"-scrib-", level:2, pos:"動詞・名詞"},
  {word:"nondescript",   meaning:"特徴のない・平凡な",    etymology:"non（否定）+ de（下に）+ script（書く）",  root:"-scrib-", level:2, pos:"形容詞"},
  {word:"scribble",      meaning:"落書きする・乱筆",      etymology:"scrib（書く）+ ble（反復）",               root:"-scrib-", level:1, pos:"動詞・名詞"},

  // ── -vert-/-vers-（向く・回る） ────────────────
  {word:"convert",       meaning:"変換する・改宗する",    etymology:"con（共に）+ vert（向く）",                root:"-vert-", level:1, pos:"動詞"},
  {word:"reverse",       meaning:"逆にする・逆転",        etymology:"re（後ろに）+ verse（向く）",              root:"-vert-", level:1, pos:"動詞・名詞"},
  {word:"divert",        meaning:"迂回させる・気をそらす",etymology:"di（離れて）+ vert（向く）",               root:"-vert-", level:2, pos:"動詞"},
  {word:"invert",        meaning:"逆さにする・反転する",  etymology:"in（中に）+ vert（向く）",                 root:"-vert-", level:2, pos:"動詞"},
  {word:"avert",         meaning:"避ける・そむける",      etymology:"a（離れて）+ vert（向く）",                root:"-vert-", level:2, pos:"動詞"},
  {word:"advertise",     meaning:"広告する",              etymology:"ad（〜に）+ vert（向く）+ ise",            root:"-vert-", level:1, pos:"動詞"},
  {word:"subvert",       meaning:"崩壊させる・覆す",      etymology:"sub（下に）+ vert（向く）",                root:"-vert-", level:2, pos:"動詞"},
  {word:"pervert",       meaning:"歪める・倒錯させる",    etymology:"per（誤って）+ vert（向く）",              root:"-vert-", level:2, pos:"動詞"},
  {word:"extrovert",     meaning:"外向的な人",            etymology:"extra（外に）+ vert（向く）",              root:"-vert-", level:1, pos:"名詞"},
  {word:"introvert",     meaning:"内向的な人",            etymology:"intro（中に）+ vert（向く）",              root:"-vert-", level:1, pos:"名詞"},
  {word:"version",       meaning:"バージョン・版",        etymology:"vers（向く）+ ion（結果）",                root:"-vert-", level:0, pos:"名詞"},
  {word:"adversary",     meaning:"敵対者・競争相手",      etymology:"ad（〜に）+ vers（向く）+ ary",            root:"-vert-", level:2, pos:"名詞"},
  {word:"versatile",     meaning:"多才な・汎用性のある",  etymology:"vers（向く）+ atile（できる）",            root:"-vert-", level:2, pos:"形容詞・動詞"},
  {word:"vertical",      meaning:"垂直の",                etymology:"vert（頂点）+ ical（〜の）",               root:"-vert-", level:1, pos:"形容詞"},
  {word:"controversy",   meaning:"論争",                  etymology:"contra（反対に）+ versy（向く）",          root:"-vert-", level:2, pos:"名詞"},
  {word:"conversation",  meaning:"会話",                  etymology:"con（共に）+ vers（向く）+ ation",         root:"-vert-", level:0, pos:"名詞"},
  {word:"revert",        meaning:"元に戻る・逆戻りする",  etymology:"re（後ろに）+ vert（向く）",               root:"-vert-", level:2, pos:"動詞"},
  {word:"traverse",      meaning:"横断する",              etymology:"trans（横断して）+ verse（向く）",         root:"-vert-", level:2, pos:"動詞"},
  {word:"diverse",       meaning:"様々な・多様な",        etymology:"di（離れて）+ verse（向く）",              root:"-vert-", level:1, pos:"形容詞"},
  {word:"universe",      meaning:"宇宙・全体",            etymology:"uni（一つ）+ verse（向く）",               root:"-vert-", level:0, pos:"名詞"},

  // ── -dict-（言う・宣言する） ──────────────────
  {word:"dictionary",    meaning:"辞書",                  etymology:"dict（言う）+ ionary（〜のもの）",         root:"-dict-", level:0, pos:"名詞"},
  {word:"predict",       meaning:"予言する・予測する",    etymology:"pre（前に）+ dict（言う）",                root:"-dict-", level:1, pos:"動詞"},
  {word:"contradict",    meaning:"矛盾する",              etymology:"contra（反対に）+ dict（言う）",           root:"-dict-", level:1, pos:"動詞"},
  {word:"verdict",       meaning:"評決・判決",            etymology:"ver（真の）+ dict（言う）",                root:"-dict-", level:2, pos:"名詞"},
  {word:"indicate",      meaning:"示す・指示する",        etymology:"in（中に）+ dic（言う）+ ate",             root:"-dict-", level:1, pos:"動詞"},
  {word:"dedicate",      meaning:"捧げる・専念する",      etymology:"de（下に）+ dic（言う）+ ate",             root:"-dict-", level:1, pos:"動詞"},
  {word:"abdicate",      meaning:"退位する・放棄する",    etymology:"ab（離れて）+ dic（言う）+ ate",           root:"-dict-", level:2, pos:"動詞"},
  {word:"dictator",      meaning:"独裁者",                etymology:"dict（言う）+ ator（〜する人）",           root:"-dict-", level:1, pos:"名詞"},
  {word:"dictate",       meaning:"口述する・命令する",    etymology:"dict（言う）+ ate（〜する）",              root:"-dict-", level:2, pos:"動詞"},
  {word:"diction",       meaning:"語法・発音",            etymology:"dict（言う）+ ion（行為）",                root:"-dict-", level:2, pos:"名詞"},
  {word:"edict",         meaning:"勅令・布告",            etymology:"e（外に）+ dict（言う）",                  root:"-dict-", level:2, pos:"名詞"},
  {word:"indict",        meaning:"起訴する",              etymology:"in（〜に）+ dict（言う）",                 root:"-dict-", level:2, pos:"動詞"},
  {word:"malediction",   meaning:"呪い・悪口",            etymology:"male（悪い）+ diction（言う）",            root:"-dict-", level:3, pos:"形容詞・名詞"},
  {word:"benediction",   meaning:"祝福",                  etymology:"bene（良い）+ diction（言う）",            root:"-dict-", level:2, pos:"名詞"},
  {word:"jurisdiction",  meaning:"管轄・司法権",          etymology:"juris（法）+ diction（言う）",             root:"-dict-", level:2, pos:"名詞"},
  {word:"valediction",   meaning:"別れの言葉・卒業の辞",  etymology:"vale（さようなら）+ diction（言う）",      root:"-dict-", level:3, pos:"名詞"},
  {word:"indictment",    meaning:"起訴状・告発",          etymology:"in（〜に）+ dict（言う）+ ment",           root:"-dict-", level:2, pos:"名詞"},
  {word:"addict",        meaning:"中毒者・耽溺する",      etymology:"ad（〜に）+ dict（言う・捧げる）",         root:"-dict-", level:1, pos:"名詞・動詞"},
  {word:"condition",     meaning:"条件・状態",            etymology:"con（共に）+ dition（言う）",              root:"-dict-", level:0, pos:"名詞"},
  {word:"syndicate",     meaning:"シンジケート・組合",    etymology:"syn（共に）+ dic（言う）+ ate",            root:"-dict-", level:2, pos:"名詞"},

  // ── -struct-（構築する・積み重ねる） ──────────
  {word:"structure",     meaning:"構造・建造物",          etymology:"struct（構築する）+ ure（結果）",          root:"-struct-", level:0, pos:"名詞"},
  {word:"construct",     meaning:"構築する・建設する",    etymology:"con（共に）+ struct（構築する）",          root:"-struct-", level:1, pos:"動詞"},
  {word:"destroy",       meaning:"破壊する",              etymology:"de（否定）+ stroy（構築する）",            root:"-struct-", level:0, pos:"動詞"},
  {word:"instruct",      meaning:"指導する・命令する",    etymology:"in（中に）+ struct（構築する）",           root:"-struct-", level:1, pos:"動詞"},
  {word:"obstruct",      meaning:"妨げる・遮断する",      etymology:"ob（向かって）+ struct（構築する）",       root:"-struct-", level:2, pos:"動詞"},
  {word:"reconstruct",   meaning:"再建する",              etymology:"re（再び）+ construct（構築する）",        root:"-struct-", level:1, pos:"動詞"},
  {word:"deconstruct",   meaning:"解体する・脱構築する",  etymology:"de（離れて）+ construct（構築する）",      root:"-struct-", level:2, pos:"動詞"},
  {word:"infrastructure",meaning:"インフラ・基盤",        etymology:"infra（下に）+ struct（構築する）+ ure",   root:"-struct-", level:2, pos:"名詞"},
  {word:"instruction",   meaning:"指示・教育",            etymology:"in（中に）+ struction（構築する）",        root:"-struct-", level:1, pos:"名詞"},
  {word:"construction",  meaning:"建設・構築",            etymology:"con（共に）+ struction（構築する）",       root:"-struct-", level:1, pos:"名詞"},
  {word:"destruction",   meaning:"破壊",                  etymology:"de（否定）+ struction（構築する）",        root:"-struct-", level:1, pos:"名詞"},
  {word:"obstruction",   meaning:"妨害・障害物",          etymology:"ob（向かって）+ struction（構築する）",    root:"-struct-", level:2, pos:"名詞"},
  {word:"reconstruction",meaning:"再建・復興",            etymology:"re（再び）+ construction（構築する）",     root:"-struct-", level:2, pos:"名詞"},
  {word:"constructive",  meaning:"建設的な",              etymology:"construct（構築する）+ ive（傾向）",       root:"-struct-", level:1, pos:"形容詞"},
  {word:"destructive",   meaning:"破壊的な",              etymology:"destruct（破壊する）+ ive（傾向）",        root:"-struct-", level:1, pos:"形容詞"},
  {word:"instructor",    meaning:"教師・インストラクター",etymology:"instruct（指導する）+ or（〜する人）",     root:"-struct-", level:1, pos:"名詞"},
  {word:"indestructible",meaning:"破壊できない",          etymology:"in（否定）+ destructible（破壊できる）",  root:"-struct-", level:2, pos:"形容詞"},
  {word:"construe",      meaning:"解釈する",              etymology:"con（共に）+ strue（構築する）",           root:"-struct-", level:3, pos:"動詞"},

  // ── -rupt-（壊す・破る） ──────────────────────
  {word:"corrupt",       meaning:"腐敗した・堕落させる",  etymology:"cor（完全に）+ rupt（壊す）",              root:"-rupt-", level:1, pos:"形容詞・動詞"},
  {word:"disrupt",       meaning:"混乱させる・崩壊させる",etymology:"dis（離れて）+ rupt（壊す）",              root:"-rupt-", level:1, pos:"動詞"},
  {word:"interrupt",     meaning:"中断する・割り込む",    etymology:"inter（間に）+ rupt（壊す）",              root:"-rupt-", level:1, pos:"動詞"},
  {word:"erupt",         meaning:"爆発する・噴火する",    etymology:"e（外に）+ rupt（壊す）",                  root:"-rupt-", level:1, pos:"動詞"},
  {word:"abrupt",        meaning:"突然の",                etymology:"ab（離れて）+ rupt（壊す）",               root:"-rupt-", level:2, pos:"形容詞"},
  {word:"bankrupt",      meaning:"破産した",              etymology:"bank（銀行）+ rupt（壊す）",               root:"-rupt-", level:1, pos:"形容詞"},
  {word:"rupture",       meaning:"破裂・決裂",            etymology:"rupt（壊す）+ ure（結果）",                root:"-rupt-", level:2, pos:"名詞"},
  {word:"corruption",    meaning:"腐敗・汚職",            etymology:"cor（完全に）+ ruption（壊す）",           root:"-rupt-", level:2, pos:"名詞"},
  {word:"disruption",    meaning:"混乱・崩壊",            etymology:"dis（離れて）+ ruption（壊す）",           root:"-rupt-", level:2, pos:"名詞"},
  {word:"eruption",      meaning:"噴火・爆発",            etymology:"e（外に）+ ruption（壊す）",               root:"-rupt-", level:1, pos:"名詞"},
  {word:"interruption",  meaning:"中断・妨害",            etymology:"inter（間に）+ ruption（壊す）",           root:"-rupt-", level:1, pos:"名詞"},
  {word:"irrupt",        meaning:"急に侵入する",          etymology:"ir（中に）+ rupt（壊す）",                 root:"-rupt-", level:3, pos:"動詞"},
  {word:"disruptive",    meaning:"破壊的な・革新的な",    etymology:"dis（離れて）+ rupt（壊す）+ ive",         root:"-rupt-", level:2, pos:"形容詞"},
  {word:"incorruptible", meaning:"腐敗しない・廉潔な",    etymology:"in（否定）+ corrupt（腐敗）+ ible",        root:"-rupt-", level:3, pos:"形容詞"},
  {word:"abruptly",      meaning:"突然に・唐突に",        etymology:"ab（離れて）+ rupt（壊す）+ ly",           root:"-rupt-", level:2, pos:"副詞"},
  {word:"unbankrupt",    meaning:"破産していない",        etymology:"un（否定）+ bankrupt（破産）",             root:"-rupt-", level:1, pos:"形容詞"},
  {word:"eruptive",      meaning:"爆発的な・噴出する",    etymology:"e（外に）+ rupt（壊す）+ ive",             root:"-rupt-", level:2, pos:"形容詞・動詞"},
  {word:"corruptible",   meaning:"腐敗しやすい",          etymology:"cor（完全に）+ rupt（壊す）+ ible",        root:"-rupt-", level:2, pos:"形容詞"},
  ];

  if(!window.WORD_DATA_RAW) window.WORD_DATA_RAW=[];
  window.WORD_DATA_RAW=window.WORD_DATA_RAW.concat(d);
})();
