/**
 * data-mixed-3.js — ビジネス・学術・医学用語
 * 形式: { word, meaning, etymology, category, level }
 * level: 1=英検5-4級 2=英検3級 3=英検準2級 4=英検2級 5=英検準1級 6=英検1級 7=TOEFL/GRE
 */
(function(){
  var d = [
  // ── ビジネス用語 ──────────────────────────────
  {word:"acquire",       meaning:"取得する・習得する",    etymology:"ac（〜に）+ quire（求める）",              category:"business", level:3, pos:"動詞"},
  {word:"allocate",      meaning:"割り当てる",            etymology:"al（〜に）+ locate（場所を定める）",       category:"business", level:5, pos:"動詞"},
  {word:"ambiguity",     meaning:"曖昧さ・多義性",        etymology:"ambi（両方）+ guity（動く）",              category:"business", level:5, pos:"名詞"},
  {word:"benchmark",     meaning:"基準・ベンチマーク",    etymology:"bench（台）+ mark（印）",                  category:"business", level:3, pos:"名詞"},
  {word:"brainstorm",    meaning:"ブレインストーミング",  etymology:"brain（脳）+ storm（嵐）",                 category:"business", level:3, pos:"名詞"},
  {word:"briefing",      meaning:"ブリーフィング・概要説明",etymology:"brief（短い）+ ing（行為）",             category:"business", level:3, pos:"名詞"},
  {word:"capitalize",    meaning:"資本化する・活用する",  etymology:"capital（資本）+ ize（〜にする）",         category:"business", level:5, pos:"動詞"},
  {word:"collaborate",   meaning:"協力する",              etymology:"col（共に）+ laborate（働く）",            category:"business", level:4, pos:"動詞"},
  {word:"compliance",    meaning:"コンプライアンス・法令順守",etymology:"compli（従う）+ ance（状態）",          category:"business", level:5, pos:"名詞"},
  {word:"confidential",  meaning:"機密の・秘密の",        etymology:"con（共に）+ fidential（信頼する）",       category:"business", level:4, pos:"形容詞"},
  {word:"consolidate",   meaning:"統合する",              etymology:"con（共に）+ solidate（固める）",          category:"business", level:5, pos:"動詞"},
  {word:"contingency",   meaning:"不測の事態・偶発性",    etymology:"con（共に）+ tingency（触れる）",          category:"business", level:5, pos:"名詞"},
  {word:"corporate",     meaning:"法人の・企業の",        etymology:"corpor（体）+ ate（〜の）",                category:"business", level:3, pos:"形容詞"},
  {word:"credibility",   meaning:"信憑性",                etymology:"credib（信頼できる）+ ility（性質）",      category:"business", level:6, pos:"名詞"},
  {word:"customer",      meaning:"顧客・お客様",          etymology:"custom（習慣）+ er（〜する人）",           category:"business", level:2, pos:"名詞"},
  {word:"deadline",      meaning:"締め切り・期限",        etymology:"dead（死んだ）+ line（線）→越えると死ぬ線",category:"business", level:1, pos:"名詞"},
  {word:"delegate",      meaning:"委任する・代理人",      etymology:"de（下に）+ legate（遣わす）",             category:"business", level:5, pos:"動詞・名詞"},
  {word:"deliverable",   meaning:"成果物・納品物",        etymology:"deliver（届ける）+ able（できる）",        category:"business", level:5, pos:"名詞"},
  {word:"depreciate",    meaning:"減価償却する・価値が下がる",etymology:"de（下に）+ preci（価値）+ ate（〜する）",category:"business", level:5, pos:"動詞"},
  {word:"diversify",     meaning:"多様化する",            etymology:"divers（様々な）+ ify（〜にする）",        category:"business", level:5, pos:"動詞"},
  {word:"entrepreneur",  meaning:"起業家",                etymology:"entre（間に）+ prendre（取る）+ eur（〜する人）",category:"business", level:5, pos:"名詞"},
  {word:"escalate",      meaning:"エスカレートする・拡大する",etymology:"escal（はしご）+ ate（〜する）",       category:"business", level:3, pos:"動詞"},
  {word:"facilitate",    meaning:"促進する・容易にする",  etymology:"facil（容易な）+ itate（〜にする）",       category:"business", level:5, pos:"動詞"},
  {word:"forecast",      meaning:"予測する・見通し",      etymology:"fore（前に）+ cast（投げる）",             category:"business", level:3, pos:"動詞・名詞"},
  {word:"franchise",     meaning:"フランチャイズ・営業権",etymology:"franc（自由）+ ise（〜にする）",           category:"business", level:5, pos:"名詞"},
  {word:"incentive",     meaning:"動機・奨励金",          etymology:"incentiv（動機）+ e",                     category:"business", level:3, pos:"名詞"},
  {word:"infrastructure",meaning:"インフラ・基盤",        etymology:"infra（下に）+ struct（構築）+ ure（結果）",category:"business", level:5, pos:"名詞"},
  {word:"innovate",      meaning:"革新する",              etymology:"in（中に）+ novate（新しくする）",         category:"business", level:3, pos:"動詞"},
  {word:"integrate",     meaning:"統合する",              etymology:"in（中に）+ tegrate（完全にする）",        category:"business", level:5, pos:"動詞"},
  {word:"leverage",      meaning:"レバレッジ・影響力",    etymology:"lever（てこ）+ age（状態）",               category:"business", level:5, pos:"名詞"},
  {word:"liquidate",     meaning:"清算する・現金化する",  etymology:"liquid（液体）+ ate（〜する）",            category:"business", level:5, pos:"動詞"},
  {word:"logistics",     meaning:"物流・ロジスティクス",  etymology:"logi（論理）+ stics（技術）",              category:"business", level:5, pos:"名詞"},
  {word:"mandate",       meaning:"命令する・任務",        etymology:"man（手）+ date（与える）",                category:"business", level:5, pos:"動詞・名詞"},
  {word:"margin",        meaning:"利益率・余白",          etymology:"marg（縁）+ in（中に）",                   category:"business", level:3, pos:"名詞"},
  {word:"merger",        meaning:"合併",                  etymology:"merg（沈む）+ er（行為）",                 category:"business", level:5, pos:"名詞"},
  {word:"milestone",     meaning:"節目・重要な出来事",    etymology:"mile（マイル）+ stone（石）",              category:"business", level:3, pos:"名詞"},
  {word:"momentum",      meaning:"勢い・モメンタム",      etymology:"moment（動き）+ um（〜のもの）",           category:"business", level:5, pos:"形容詞・名詞"},
  {word:"negotiate",     meaning:"交渉する",              etymology:"neg（否定）+ otiate（余暇）→休まず働く",   category:"business", level:3, pos:"動詞"},
  {word:"outsource",     meaning:"外部委託する",          etymology:"out（外に）+ source（源）",                category:"business", level:3, pos:"動詞"},
  {word:"overhead",      meaning:"経費・頭上",            etymology:"over（上に）+ head（頭）",                 category:"business", level:3, pos:"名詞"},
  {word:"paradigm shift",meaning:"パラダイムシフト",      etymology:"para（傍らに）+ digm（示す）+ shift（変化）",category:"business", level:5, pos:"名詞"},
  {word:"portfolio",     meaning:"ポートフォリオ・事業範囲",etymology:"port（運ぶ）+ folio（葉）",              category:"business", level:3, pos:"名詞"},
  {word:"prioritize",    meaning:"優先する",              etymology:"priorit（優先）+ ize（〜にする）",         category:"business", level:3, pos:"動詞"},
  {word:"proactive",     meaning:"積極的な・先手を打つ",  etymology:"pro（前に）+ active（活発な）",            category:"business", level:3, pos:"形容詞・動詞"},
  {word:"procurement",   meaning:"調達",                  etymology:"pro（前に）+ cure（得る）+ ment（結果）",  category:"business", level:5, pos:"名詞"},
  {word:"prototype",     meaning:"試作品・原型",          etymology:"proto（最初）+ type（型）",                category:"business", level:3, pos:"名詞"},
  {word:"revenue",       meaning:"収益・歳入",            etymology:"re（再び）+ venue（来る）",                category:"business", level:3, pos:"名詞"},
  {word:"scalable",      meaning:"拡張可能な",            etymology:"scal（はしご）+ able（できる）",           category:"business", level:5, pos:"形容詞"},
  {word:"stakeholder",   meaning:"利害関係者",            etymology:"stake（賭け金）+ holder（持つ人）",        category:"business", level:4, pos:"名詞"},
  {word:"synergy",       meaning:"相乗効果",              etymology:"syn（共に）+ ergy（働く）",                category:"business", level:5, pos:"名詞"},
  {word:"transparency",  meaning:"透明性",                etymology:"trans（通じて）+ par（見える）+ ency（性質）",category:"business", level:4, pos:"名詞"},
  {word:"turnover",      meaning:"離職率・売上高",        etymology:"turn（回る）+ over（上に）",               category:"business", level:3, pos:"名詞"},
  {word:"venture",       meaning:"冒険・ベンチャー",      etymology:"vent（来る）+ ure（行為）",                category:"business", level:3, pos:"名詞"},
  {word:"viable",        meaning:"実行可能な",            etymology:"via（道）+ ble（できる）",                 category:"business", level:5, pos:"形容詞"},
  {word:"volatility",    meaning:"変動性・不安定性",      etymology:"volat（飛ぶ）+ ility（性質）",             category:"business", level:6, pos:"名詞"},

  // ── 学術用語 ─────────────────────────────────
  {word:"abstract",      meaning:"抄録・要旨",            etymology:"ab（離れて）+ tract（引く）",              category:"academic", level:3, pos:"名詞"},
  {word:"citation",      meaning:"引用・引用文",          etymology:"cit（呼ぶ）+ ation（行為）",               category:"academic", level:5, pos:"名詞"},
  {word:"cohort",        meaning:"コホート・集団",        etymology:"co（共に）+ hort（囲い）",                 category:"academic", level:5, pos:"名詞"},
  {word:"correlate",     meaning:"相関する・関連づける",  etymology:"cor（共に）+ relate（関係する）",          category:"academic", level:5, pos:"動詞"},
  {word:"empirical",     meaning:"経験的な・実証的な",    etymology:"empir（経験）+ ical（〜の）",              category:"academic", level:5, pos:"形容詞"},
  {word:"epistemology",  meaning:"認識論",                etymology:"epistemo（知識）+ logy（学）",             category:"academic", level:7, pos:"名詞"},
  {word:"extrapolate",   meaning:"外挿する・推定する",    etymology:"extra（外に）+ polate（磨く）",            category:"academic", level:6, pos:"動詞"},
  {word:"hypothesis",    meaning:"仮説",                  etymology:"hypo（下に）+ thesis（置く）",             category:"academic", level:5, pos:"名詞"},
  {word:"inference",     meaning:"推論・推定",            etymology:"infer（導く）+ ence（状態）",              category:"academic", level:5, pos:"名詞"},
  {word:"interdisciplinary",meaning:"学際的な",          etymology:"inter（間に）+ disciplinary（学問の）",    category:"academic", level:6, pos:"形容詞"},
  {word:"longitudinal",  meaning:"縦断的な・長手方向の",  etymology:"longi（長い）+ tudinal（〜の）",           category:"academic", level:6, pos:"形容詞"},
  {word:"meta-analysis", meaning:"メタ分析",              etymology:"meta（超えて）+ analysis（分析）",         category:"academic", level:7, pos:"名詞"},
  {word:"methodology",   meaning:"方法論",                etymology:"method（方法）+ ology（学）",              category:"academic", level:6, pos:"名詞"},
  {word:"paradigm",      meaning:"パラダイム・範例",      etymology:"para（傍らに）+ digm（示す）",             category:"academic", level:6, pos:"名詞"},
  {word:"peer review",   meaning:"査読",                  etymology:"peer（同格）+ review（再び見る）",         category:"academic", level:5, pos:"名詞"},
  {word:"qualitative",   meaning:"質的な",                etymology:"qualitat（質）+ ive（〜の）",              category:"academic", level:5, pos:"形容詞"},
  {word:"quantitative",  meaning:"量的な",                etymology:"quantitat（量）+ ive（〜の）",             category:"academic", level:5, pos:"形容詞"},
  {word:"replication",   meaning:"再現・複製",            etymology:"replic（繰り返す）+ ation（行為）",        category:"academic", level:5, pos:"名詞"},
  {word:"rhetoric",      meaning:"修辞学・雄弁術",        etymology:"rhetor（演説者）+ ic（技術）",             category:"academic", level:5, pos:"名詞"},
  {word:"statistical",   meaning:"統計的な",              etymology:"statistic（統計）+ al（〜の）",            category:"academic", level:4, pos:"形容詞"},
  {word:"synthesis",     meaning:"統合・合成",            etymology:"syn（共に）+ thesis（置く）",              category:"academic", level:5, pos:"名詞"},
  {word:"taxonomy",      meaning:"分類学",                etymology:"tax（秩序）+ nomy（法則）",                category:"academic", level:5, pos:"名詞"},
  {word:"theoretical",   meaning:"理論的な",              etymology:"theoret（考える）+ ical（〜の）",          category:"academic", level:4, pos:"形容詞"},
  {word:"variable",      meaning:"変数・変動する",        etymology:"vari（様々な）+ able（できる）",           category:"academic", level:3, pos:"名詞・動詞"},

  // ── 医学用語 ─────────────────────────────────
  {word:"acute",         meaning:"急性の・鋭い",          etymology:"acut（鋭い）+ e",                         category:"medical", level:3, pos:"形容詞"},
  {word:"benign",        meaning:"良性の・無害な",        etymology:"bene（良い）+ gn（生まれる）",             category:"medical", level:5, pos:"形容詞"},
  {word:"cardiovascular",meaning:"心臓血管の",            etymology:"cardio（心臓）+ vascular（血管）",         category:"medical", level:6, pos:"形容詞"},
  {word:"chronic",       meaning:"慢性の",                etymology:"chron（時間）+ ic（〜の）",                category:"medical", level:3, pos:"形容詞"},
  {word:"contraindication",meaning:"禁忌",               etymology:"contra（反対に）+ indication（指示）",      category:"medical", level:7, pos:"名詞"},
  {word:"diagnosis",     meaning:"診断",                  etymology:"dia（通じて）+ gnosis（知る）",            category:"medical", level:3, pos:"名詞"},
  {word:"epidemiology",  meaning:"疫学",                  etymology:"epi（上に）+ demo（人々）+ logy（学）",    category:"medical", level:6, pos:"名詞"},
  {word:"etiology",      meaning:"病因学",                etymology:"etio（原因）+ logy（学）",                 category:"medical", level:6, pos:"名詞"},
  {word:"hemoglobin",    meaning:"ヘモグロビン",          etymology:"hemo（血）+ globin（球状タンパク）",        category:"medical", level:5, pos:"名詞"},
  {word:"iatrogenic",    meaning:"医原性の",              etymology:"iatro（医者）+ gen（生む）+ ic（〜の）",   category:"medical", level:6, pos:"形容詞"},
  {word:"idiopathic",    meaning:"特発性の",              etymology:"idio（固有の）+ pathic（病気）",           category:"medical", level:6, pos:"形容詞"},
  {word:"immunosuppression",meaning:"免疫抑制",           etymology:"immuno（免疫）+ suppression（抑制）",      category:"medical", level:7, pos:"名詞"},
  {word:"inflammation",  meaning:"炎症",                  etymology:"in（中に）+ flamm（炎）+ ation（行為）",   category:"medical", level:4, pos:"名詞"},
  {word:"intravenous",   meaning:"静脈内の",              etymology:"intra（内に）+ venous（静脈の）",          category:"medical", level:5, pos:"形容詞"},
  {word:"lesion",        meaning:"病変・損傷",            etymology:"laes（傷つける）+ ion（結果）",            category:"medical", level:5, pos:"名詞"},
  {word:"malignant",     meaning:"悪性の",                etymology:"mal（悪い）+ ignant（生まれる）",          category:"medical", level:5, pos:"形容詞"},
  {word:"metabolism",    meaning:"代謝",                  etymology:"meta（変化）+ bolism（投げる）",           category:"medical", level:4, pos:"名詞"},
  {word:"pathology",     meaning:"病理学",                etymology:"patho（病気）+ logy（学）",                category:"medical", level:5, pos:"名詞"},
  {word:"pharmacology",  meaning:"薬理学",                etymology:"pharmaco（薬）+ logy（学）",               category:"medical", level:6, pos:"名詞"},
  {word:"prognosis",     meaning:"予後・見通し",          etymology:"pro（前に）+ gnosis（知る）",              category:"medical", level:5, pos:"名詞"},
  {word:"prophylaxis",   meaning:"予防措置",              etymology:"pro（前に）+ phylaxis（守る）",            category:"medical", level:6, pos:"名詞"},
  {word:"resection",     meaning:"切除術",                etymology:"re（再び）+ section（切る）",              category:"medical", level:6, pos:"名詞"},
  {word:"symptom",       meaning:"症状・徴候",            etymology:"sym（共に）+ ptom（落ちる）",              category:"medical", level:3, pos:"名詞"},
  {word:"syndrome",      meaning:"症候群",                etymology:"syn（共に）+ drome（走る）",               category:"medical", level:3, pos:"名詞"},
  {word:"therapy",       meaning:"治療・療法",            etymology:"therap（治療する）+ y",                    category:"medical", level:3, pos:"名詞"},
  {word:"toxicology",    meaning:"毒性学",                etymology:"toxico（毒）+ logy（学）",                 category:"medical", level:6, pos:"名詞"},
  {word:"triage",        meaning:"トリアージ・重傷度選別",etymology:"tri（三つ）+ age（行為）",                 category:"medical", level:5, pos:"名詞"},
  {word:"hypertension",  meaning:"高血圧",                etymology:"hyper（過度に）+ tension（緊張）",         category:"medical", level:4, pos:"名詞"},
  {word:"arrhythmia",    meaning:"不整脈",                etymology:"a（否定）+ rhythmia（リズム）",            category:"medical", level:5, pos:"名詞"},
  {word:"anesthesia",    meaning:"麻酔",                  etymology:"an（否定）+ esthesia（感じる）",           category:"medical", level:5, pos:"名詞"},
  ];

  if(!window.WORD_DATA_RAW) window.WORD_DATA_RAW=[];
  window.WORD_DATA_RAW=window.WORD_DATA_RAW.concat(d);
})();
