/**
 * data-mixed-1.js — TOEFL/IELTS頻出語（学術・知的語彙）
 * 形式: { word, meaning, etymology, category, level }
 * level: 1=英検5-4級 2=英検3級 3=英検準2級 4=英検2級 5=英検準1級 6=英検1級 7=TOEFL/GRE
 */
(function(){
  var d = [
  // ── TOEFL/IELTS 頻出語（A〜C） ───────────────
  {word:"abandon",       meaning:"放棄する・捨てる",      etymology:"a（〜に）+ bandon（権力）→権力から解放する",category:"TOEFL", level:3, pos:"動詞"},
  {word:"abolish",       meaning:"廃止する",              etymology:"ab（離れて）+ olish（育てる）→育成をやめる",category:"TOEFL", level:5, pos:"動詞"},
  {word:"abstract",      meaning:"抽象的な・要約",        etymology:"ab（離れて）+ tract（引く）→引き離す",     category:"TOEFL", level:3, pos:"形容詞・名詞"},
  {word:"accelerate",    meaning:"加速する",              etymology:"ac（〜に）+ celer（速い）+ ate（〜する）", category:"TOEFL", level:5, pos:"動詞"},
  {word:"acknowledge",   meaning:"認める・感謝する",      etymology:"ac（〜に）+ knowledge（知識）",            category:"TOEFL", level:3, pos:"動詞"},
  {word:"adequate",      meaning:"十分な・適切な",        etymology:"ad（〜に）+ equate（等しくする）",         category:"TOEFL", level:3, pos:"形容詞"},
  {word:"advocate",      meaning:"主張する・弁護人",      etymology:"ad（〜に）+ vocate（呼ぶ）",               category:"TOEFL", level:5, pos:"動詞・名詞"},
  {word:"alter",         meaning:"変える・変更する",      etymology:"alter（他の）→他の状態にする",             category:"TOEFL", level:3, pos:"動詞"},
  {word:"ambiguous",     meaning:"あいまいな",            etymology:"ambi（両方）+ guous（動く）",              category:"TOEFL", level:5, pos:"形容詞"},
  {word:"analogy",       meaning:"類似・アナロジー",      etymology:"ana（似た）+ logy（論理）",                category:"TOEFL", level:5, pos:"名詞"},
  {word:"annual",        meaning:"年1回の・年次の",       etymology:"ann（年）+ ual（〜の）",                   category:"TOEFL", level:3, pos:"形容詞"},
  {word:"anticipate",    meaning:"予期する・先取りする",  etymology:"anti（前に）+ cipate（取る）",             category:"TOEFL", level:5, pos:"動詞"},
  {word:"appropriate",   meaning:"適切な・当然の",        etymology:"ap（〜に）+ propriate（自分のもの）",      category:"TOEFL", level:3, pos:"形容詞"},
  {word:"approximately", meaning:"おおよそ・約",          etymology:"ap（〜に）+ proximate（近い）+ ly",        category:"TOEFL", level:4, pos:"名詞"},
  {word:"assess",        meaning:"評価する・査定する",    etymology:"as（〜に）+ sess（座る）→側に座って判断",   category:"TOEFL", level:5, pos:"動詞"},
  {word:"assume",        meaning:"想定する・仮定する",    etymology:"as（〜に）+ sume（取る）",                 category:"TOEFL", level:3, pos:"動詞"},
  {word:"attribute",     meaning:"〜のせいにする・特性",  etymology:"at（〜に）+ tribute（与える）",            category:"TOEFL", level:5, pos:"動詞・名詞"},
  {word:"benefit",       meaning:"利益・恩恵",            etymology:"bene（良い）+ fit（行う）",                category:"TOEFL", level:2, pos:"名詞"},
  {word:"bias",          meaning:"偏見・偏り",            etymology:"biais（斜めの）→一方に傾く",               category:"TOEFL", level:5, pos:"名詞"},
  {word:"capacity",      meaning:"容量・能力",            etymology:"cap（取る）+ acity（性質）",               category:"TOEFL", level:4, pos:"名詞"},
  {word:"category",      meaning:"カテゴリー・分類",      etymology:"cata（下に）+ gory（集める）",             category:"TOEFL", level:4, pos:"名詞"},
  {word:"cause",         meaning:"原因・引き起こす",      etymology:"caus（原因）+ e",                          category:"TOEFL", level:1, pos:"名詞・動詞"},
  {word:"characteristic",meaning:"特性・特徴的な",        etymology:"character（刻み込む）+ istic（〜の）",     category:"TOEFL", level:4, pos:"名詞・形容詞"},
  {word:"circumstance",  meaning:"状況・環境",            etymology:"circum（周囲に）+ stance（立つ）",         category:"TOEFL", level:3, pos:"名詞"},
  {word:"clarify",       meaning:"明確にする",            etymology:"clar（明らか）+ ify（〜にする）",          category:"TOEFL", level:3, pos:"動詞"},
  {word:"coherent",      meaning:"一貫した・理路整然とした",etymology:"co（共に）+ herent（くっつく）",          category:"TOEFL", level:5, pos:"形容詞"},
  {word:"coincide",      meaning:"一致する・同時に起こる",etymology:"co（共に）+ incide（起こる）",             category:"TOEFL", level:5, pos:"動詞"},
  {word:"collapse",      meaning:"崩壊する",              etymology:"col（完全に）+ lapse（滑る）",             category:"TOEFL", level:3, pos:"動詞"},
  {word:"colleague",     meaning:"同僚",                  etymology:"col（共に）+ league（選ぶ）",              category:"TOEFL", level:3, pos:"名詞"},
  {word:"communicate",   meaning:"伝える・コミュニケーションをとる",etymology:"com（共に）+ munic（分かち合う）+ ate",category:"TOEFL", level:2, pos:"動詞"},
  {word:"compare",       meaning:"比較する",              etymology:"com（共に）+ pare（等しい）",              category:"TOEFL", level:1, pos:"動詞"},
  {word:"complex",       meaning:"複雑な",                etymology:"com（共に）+ plex（編む）",                category:"TOEFL", level:3, pos:"形容詞"},
  {word:"concentrate",   meaning:"集中する",              etymology:"con（共に）+ centrate（中心に）",          category:"TOEFL", level:3, pos:"動詞"},
  {word:"conclude",      meaning:"結論づける",            etymology:"con（共に）+ clude（閉じる）",             category:"TOEFL", level:3, pos:"動詞"},
  {word:"consistent",    meaning:"一貫した",              etymology:"con（共に）+ sistent（立つ）",             category:"TOEFL", level:3, pos:"形容詞"},
  {word:"context",       meaning:"文脈・状況",            etymology:"con（共に）+ text（織る）",                category:"TOEFL", level:3, pos:"名詞"},
  {word:"contrast",      meaning:"対比する",              etymology:"contra（反対に）+ trast（立つ）",          category:"TOEFL", level:3, pos:"動詞"},
  {word:"contribute",    meaning:"貢献する",              etymology:"con（共に）+ tribute（与える）",           category:"TOEFL", level:3, pos:"動詞"},
  {word:"convince",      meaning:"説得する",              etymology:"con（完全に）+ vince（征服する）",         category:"TOEFL", level:3, pos:"動詞"},
  {word:"core",          meaning:"核心・中心部",          etymology:"cor（心臓）",                              category:"TOEFL", level:3, pos:"名詞"},

  // ── TOEFL/IELTS 頻出語（D〜G） ───────────────
  {word:"data",          meaning:"データ・資料",          etymology:"dat（与えられた）+ a（複数）",             category:"TOEFL", level:1, pos:"名詞"},
  {word:"debate",        meaning:"討論する・議論",        etymology:"de（完全に）+ bate（打つ）",               category:"TOEFL", level:3, pos:"動詞・名詞"},
  {word:"decline",       meaning:"減少する・断る",        etymology:"de（下に）+ cline（傾く）",                category:"TOEFL", level:3, pos:"動詞"},
  {word:"demonstrate",   meaning:"実証する・示す",        etymology:"de（完全に）+ monstrate（示す）",          category:"TOEFL", level:3, pos:"動詞"},
  {word:"depend",        meaning:"依存する",              etymology:"de（下に）+ pend（ぶら下がる）",           category:"TOEFL", level:1, pos:"動詞"},
  {word:"despite",       meaning:"〜にもかかわらず",      etymology:"de（下に）+ spite（軽蔑）",                category:"TOEFL", level:3, pos:"名詞"},
  {word:"determine",     meaning:"決定する・断定する",    etymology:"de（完全に）+ termine（境界）",            category:"TOEFL", level:3, pos:"動詞"},
  {word:"develop",       meaning:"発展させる",            etymology:"de（離れて）+ velop（包む）",              category:"TOEFL", level:2, pos:"動詞"},
  {word:"diverse",       meaning:"多様な",                etymology:"di（離れて）+ verse（向く）",              category:"TOEFL", level:3, pos:"形容詞"},
  {word:"document",      meaning:"文書・記録する",        etymology:"docu（教える）+ ment（手段）",             category:"TOEFL", level:3, pos:"名詞・動詞"},
  {word:"dominant",      meaning:"支配的な・優勢な",      etymology:"domin（支配する）+ ant（〜している）",      category:"TOEFL", level:5, pos:"形容詞"},
  {word:"dynamic",       meaning:"力強い・ダイナミック",  etymology:"dynam（力）+ ic（〜の）",                  category:"TOEFL", level:3, pos:"形容詞・名詞"},
  {word:"emphasize",     meaning:"強調する",              etymology:"em（中に）+ phas（示す）+ ize（〜する）",  category:"TOEFL", level:3, pos:"動詞"},
  {word:"enable",        meaning:"可能にする",            etymology:"en（〜にする）+ able（できる）",           category:"TOEFL", level:3, pos:"動詞"},
  {word:"encourage",     meaning:"励ます",                etymology:"en（〜にする）+ courage（勇気）",          category:"TOEFL", level:3, pos:"動詞"},
  {word:"environment",   meaning:"環境",                  etymology:"environ（囲む）+ ment（状態）",            category:"TOEFL", level:2, pos:"名詞"},
  {word:"establish",     meaning:"設立する・確立する",    etymology:"e（外に）+ stablish（立てる）",            category:"TOEFL", level:3, pos:"動詞"},
  {word:"evaluate",      meaning:"評価する",              etymology:"e（外に）+ valu（価値）+ ate（〜する）",   category:"TOEFL", level:5, pos:"動詞"},
  {word:"evidence",      meaning:"証拠",                  etymology:"e（外に）+ vid（見る）+ ence（状態）",     category:"TOEFL", level:3, pos:"名詞"},
  {word:"examine",       meaning:"調べる・試験する",      etymology:"ex（外に）+ amine（量る）",                category:"TOEFL", level:3, pos:"動詞"},
  {word:"expand",        meaning:"拡大する",              etymology:"ex（外に）+ pand（広げる）",               category:"TOEFL", level:3, pos:"動詞"},
  {word:"factor",        meaning:"要因・要素",            etymology:"fact（作る）+ or（〜するもの）",           category:"TOEFL", level:3, pos:"名詞"},
  {word:"feature",       meaning:"特徴・特色",            etymology:"featur（作る）+ e",                        category:"TOEFL", level:3, pos:"名詞"},
  {word:"fluctuate",     meaning:"変動する",              etymology:"fluctu（波）+ ate（〜する）",              category:"TOEFL", level:5, pos:"動詞"},
  {word:"focus",         meaning:"焦点を当てる",          etymology:"focus（炉）→中心に集める",                 category:"TOEFL", level:1, pos:"動詞"},
  {word:"generate",      meaning:"生み出す",              etymology:"gen（生む）+ erate（〜する）",             category:"TOEFL", level:3, pos:"動詞"},
  {word:"global",        meaning:"世界的な・全体的な",    etymology:"glob（球）+ al（〜の）",                   category:"TOEFL", level:1, pos:"形容詞"},

  // ── TOEFL/IELTS 頻出語（H〜Z） ───────────────
  {word:"hypothesis",    meaning:"仮説",                  etymology:"hypo（下に）+ thesis（置く）",             category:"TOEFL", level:4, pos:"名詞"},
  {word:"identify",      meaning:"特定する・識別する",    etymology:"ident（同じ）+ ify（〜にする）",           category:"TOEFL", level:4, pos:"動詞"},
  {word:"illustrate",    meaning:"例証する・図解する",    etymology:"il（〜に）+ lustrate（光を当てる）",       category:"TOEFL", level:3, pos:"動詞"},
  {word:"implement",     meaning:"実施する・実装する",    etymology:"im（中に）+ plement（満たす）",            category:"TOEFL", level:5, pos:"動詞"},
  {word:"implication",   meaning:"含意・暗示",            etymology:"im（中に）+ plication（折る）",            category:"TOEFL", level:5, pos:"名詞"},
  {word:"indicate",      meaning:"示す",                  etymology:"in（中に）+ dic（言う）+ ate（〜する）",   category:"TOEFL", level:3, pos:"動詞"},
  {word:"influence",     meaning:"影響・影響する",        etymology:"in（中に）+ flu（流れる）+ ence（状態）",  category:"TOEFL", level:3, pos:"名詞・動詞"},
  {word:"maintain",      meaning:"維持する",              etymology:"main（手で）+ tain（保つ）",               category:"TOEFL", level:3, pos:"動詞"},
  {word:"method",        meaning:"方法・方式",            etymology:"meta（後ろに）+ hod（道）",                category:"TOEFL", level:1, pos:"名詞"},
  {word:"numerous",      meaning:"多数の",                etymology:"numer（数）+ ous（性質）",                 category:"TOEFL", level:3, pos:"形容詞"},
  {word:"obvious",       meaning:"明らかな",              etymology:"ob（向かって）+ vious（道）",              category:"TOEFL", level:1, pos:"形容詞"},
  {word:"overcome",      meaning:"克服する",              etymology:"over（上に）+ come（来る）",               category:"TOEFL", level:3, pos:"動詞"},
  {word:"perceive",      meaning:"知覚する",              etymology:"per（完全に）+ ceive（取る）",             category:"TOEFL", level:3, pos:"動詞"},
  {word:"persistent",    meaning:"持続する・頑固な",      etymology:"per（完全に）+ sistent（立つ）",           category:"TOEFL", level:5, pos:"動詞・形容詞"},
  {word:"predominant",   meaning:"主要な・支配的な",      etymology:"pre（前に）+ dominant（支配する）",        category:"TOEFL", level:5, pos:"形容詞"},
  {word:"promote",       meaning:"促進する",              etymology:"pro（前に）+ mote（動く）",                category:"TOEFL", level:3, pos:"動詞"},
  {word:"propose",       meaning:"提案する",              etymology:"pro（前に）+ pose（置く）",                category:"TOEFL", level:3, pos:"動詞"},
  {word:"relevant",      meaning:"関連した",              etymology:"re（再び）+ lev（持ち上げる）+ ant（〜の）",category:"TOEFL", level:3, pos:"形容詞"},
  {word:"require",       meaning:"必要とする",            etymology:"re（再び）+ quire（求める）",              category:"TOEFL", level:1, pos:"動詞"},
  {word:"research",      meaning:"研究・調査する",        etymology:"re（再び）+ search（探す）",               category:"TOEFL", level:1, pos:"名詞・動詞"},
  {word:"significant",   meaning:"重要な",                etymology:"sign（印）+ ificant（作る）",              category:"TOEFL", level:4, pos:"形容詞"},
  {word:"strategy",      meaning:"戦略",                  etymology:"strat（軍隊）+ egy（導く）",               category:"TOEFL", level:3, pos:"名詞"},
  {word:"structure",     meaning:"構造・組織",            etymology:"struct（構築する）+ ure（結果）",          category:"TOEFL", level:3, pos:"名詞"},
  {word:"substantial",   meaning:"実質的な・相当な",      etymology:"sub（下に）+ stantial（立つ）",            category:"TOEFL", level:5, pos:"形容詞"},
  {word:"sufficient",    meaning:"十分な",                etymology:"suf（下に）+ ficient（作る）",             category:"TOEFL", level:3, pos:"形容詞"},
  {word:"technology",    meaning:"テクノロジー・技術",    etymology:"techno（技術）+ logy（学）",               category:"TOEFL", level:2, pos:"名詞"},
  {word:"theory",        meaning:"理論",                  etymology:"theor（見る）+ y",                         category:"TOEFL", level:3, pos:"名詞"},
  {word:"tradition",     meaning:"伝統",                  etymology:"tradi（引き渡す）+ tion（行為）",          category:"TOEFL", level:2, pos:"名詞"},
  {word:"utilize",       meaning:"利用する",              etymology:"util（役立つ）+ ize（〜にする）",          category:"TOEFL", level:3, pos:"動詞"},
  {word:"valid",         meaning:"有効な・正当な",        etymology:"val（強い）+ id（〜の）",                  category:"TOEFL", level:3, pos:"形容詞"},
  {word:"vary",          meaning:"変わる・多様にする",    etymology:"var（様々な）+ y（〜する）",               category:"TOEFL", level:3, pos:"動詞"},
  ];

  if(!window.WORD_DATA_RAW) window.WORD_DATA_RAW=[];
  window.WORD_DATA_RAW=window.WORD_DATA_RAW.concat(d);
})();
