/**
 * data-root-3.js — 語根データ vol.1
 * 語根: -cred-, -aud-, -vis-/-vid-, -sent-/-sens-, -ped-/-pod-,
 *       -man-/-manu-, -cap-/-cept-, -fac-/-fect-/-fic-
 * 形式: { word, meaning, etymology, root, level }
 * level: 0=beginner 1=intermediate 2=advanced 3=master
 */
(function(){
  var d = [

  // ── -cred-（信じる） ──────────────────────────────
  {word:"credit",       meaning:"信用・クレジット",       etymology:"cred（信じる）→ 信用されること",                root:"-cred-", level:0},
  {word:"credible",     meaning:"信頼できる",             etymology:"cred（信じる）+ ible（できる）",                root:"-cred-", level:1},
  {word:"incredible",   meaning:"信じられない・素晴らしい",etymology:"in（否定）+ cred（信じる）+ ible",              root:"-cred-", level:0},
  {word:"credibility",  meaning:"信頼性・信用性",         etymology:"cred（信じる）+ ibility（性質）",               root:"-cred-", level:1},
  {word:"credentials",  meaning:"資格証明書・信任状",     etymology:"cred（信じる）+ entials（もの）",               root:"-cred-", level:2},
  {word:"creed",        meaning:"信条・信仰箇条",         etymology:"cred（信じる）→ 信じること",                    root:"-cred-", level:2},
  {word:"credulous",    meaning:"信じやすい・騙されやすい",etymology:"cred（信じる）+ ulous（傾向がある）",           root:"-cred-", level:2},
  {word:"incredulous",  meaning:"懐疑的な・信じない",     etymology:"in（否定）+ cred（信じる）+ ulous",             root:"-cred-", level:2},
  {word:"accredit",     meaning:"認定する・公認する",     etymology:"ac（〜へ）+ cred（信じる）→ 信用を与える",      root:"-cred-", level:2},
  {word:"discredit",    meaning:"信用を傷つける",         etymology:"dis（否定）+ cred（信じる）",                   root:"-cred-", level:2},
  {word:"miscreant",    meaning:"悪人・犯罪者",           etymology:"mis（誤って）+ cred（信じる）+ ant",            root:"-cred-", level:3},
  {word:"recreant",     meaning:"臆病者・裏切り者",       etymology:"re（後ろ）+ cred（信じる）+ ant",              root:"-cred-", level:3},

  // ── -aud-（聞く） ───────────────────────────────
  {word:"audio",        meaning:"音声・オーディオ",       etymology:"aud（聞く）+ io（こと）",                       root:"-aud-", level:0},
  {word:"audience",     meaning:"聴衆・視聴者",           etymology:"aud（聞く）+ ience（人々）",                    root:"-aud-", level:0},
  {word:"audible",      meaning:"聞こえる・可聴の",       etymology:"aud（聞く）+ ible（できる）",                   root:"-aud-", level:1},
  {word:"inaudible",    meaning:"聞こえない",             etymology:"in（否定）+ aud（聞く）+ ible",                 root:"-aud-", level:2},
  {word:"audit",        meaning:"会計監査・監査する",     etymology:"aud（聞く）→ 帳簿を聞いて確かめる",             root:"-aud-", level:1},
  {word:"auditor",      meaning:"監査人・聴講生",         etymology:"aud（聞く）+ itor（人）",                       root:"-aud-", level:1},
  {word:"audition",     meaning:"オーディション・試聴",   etymology:"aud（聞く）+ ition（行為）",                    root:"-aud-", level:1},
  {word:"auditorium",   meaning:"講堂・ホール",           etymology:"aud（聞く）+ orium（場所）",                    root:"-aud-", level:1},
  {word:"audiovisual",  meaning:"視聴覚の",               etymology:"aud（聞く）+ o + visual（見る）",               root:"-aud-", level:2},
  {word:"audacious",    meaning:"大胆な・厚かましい",     etymology:"aud（勇敢に聞く）+ acious（性質）",             root:"-aud-", level:2},
  {word:"audacity",     meaning:"大胆さ・図々しさ",       etymology:"aud（勇敢）+ acity（性質）",                    root:"-aud-", level:2},
  {word:"inaudacious",  meaning:"臆病な",                 etymology:"in（否定）+ aud（勇敢）+ acious",               root:"-aud-", level:3},

  // ── -vis-/-vid-（見る） ─────────────────────────
  {word:"vision",       meaning:"視力・ビジョン・幻",     etymology:"vis（見る）+ ion（こと）",                      root:"-vis-", level:0},
  {word:"visible",      meaning:"見える・目に見える",     etymology:"vis（見る）+ ible（できる）",                   root:"-vis-", level:0},
  {word:"invisible",    meaning:"見えない・不可視の",     etymology:"in（否定）+ vis（見る）+ ible",                 root:"-vis-", level:1},
  {word:"visual",       meaning:"視覚の・映像の",         etymology:"vis（見る）+ ual（〜の）",                      root:"-vis-", level:0},
  {word:"visit",        meaning:"訪問する",               etymology:"vis（見る）→ 会いに行く",                       root:"-vis-", level:0},
  {word:"video",        meaning:"映像・動画",             etymology:"vid（見る）+ eo（こと）",                       root:"-vis-", level:0},
  {word:"evidence",     meaning:"証拠・証明",             etymology:"e（外に）+ vid（見る）+ ence → 明らかに見える", root:"-vis-", level:1},
  {word:"evident",      meaning:"明らかな・明白な",       etymology:"e（外に）+ vid（見る）+ ent",                   root:"-vis-", level:1},
  {word:"supervise",    meaning:"監督する・管理する",     etymology:"super（上に）+ vis（見る）→ 上から見る",        root:"-vis-", level:1},
  {word:"supervisor",   meaning:"監督者・管理者",         etymology:"super（上に）+ vis（見る）+ or（人）",          root:"-vis-", level:1},
  {word:"revision",     meaning:"改訂・見直し",           etymology:"re（再び）+ vis（見る）+ ion",                  root:"-vis-", level:1},
  {word:"provision",    meaning:"供給・規定・準備",       etymology:"pro（前に）+ vis（見る）+ ion → 前もって見る",  root:"-vis-", level:2},
  {word:"improvise",    meaning:"即興で行う",             etymology:"im（否定）+ pro（前に）+ vis（見る）→ 準備なし",root:"-vis-", level:2},
  {word:"visualize",    meaning:"視覚化する・想像する",   etymology:"vis（見る）+ ualize（〜にする）",               root:"-vis-", level:1},
  {word:"vista",        meaning:"展望・眺め",             etymology:"vis（見る）+ ta → 見渡す景色",                  root:"-vis-", level:2},
  {word:"visor",        meaning:"バイザー・日よけ",       etymology:"vis（見る）+ or → 視界を守るもの",              root:"-vis-", level:2},
  {word:"envisage",     meaning:"心に描く・想定する",     etymology:"en（中に）+ vis（見る）+ age",                  root:"-vis-", level:2},
  {word:"envision",     meaning:"想像する・思い描く",     etymology:"en（中に）+ vis（見る）+ ion",                  root:"-vis-", level:2},
  {word:"prevision",    meaning:"予見・先見",             etymology:"pre（前に）+ vis（見る）+ ion",                 root:"-vis-", level:3},
  {word:"clairvoyant",  meaning:"透視力のある・千里眼の", etymology:"clair（明らかに）+ voy（見る）+ ant",           root:"-vis-", level:3},

  // ── -sent-/-sens-（感じる） ─────────────────────
  {word:"sense",        meaning:"感覚・感じる",           etymology:"sens（感じる）→ 感知すること",                  root:"-sens-", level:0},
  {word:"sensible",     meaning:"分別のある・分かる",     etymology:"sens（感じる）+ ible（できる）",                root:"-sens-", level:1},
  {word:"sensitive",    meaning:"敏感な・繊細な",         etymology:"sens（感じる）+ itive（傾向がある）",           root:"-sens-", level:1},
  {word:"sensation",    meaning:"感覚・センセーション",   etymology:"sens（感じる）+ ation（こと）",                 root:"-sens-", level:1},
  {word:"sensory",      meaning:"感覚の・知覚の",         etymology:"sens（感じる）+ ory（〜の）",                   root:"-sens-", level:2},
  {word:"consent",      meaning:"同意する・承諾",         etymology:"con（共に）+ sent（感じる）→ 同じ気持ち",       root:"-sens-", level:1},
  {word:"dissent",      meaning:"反対する・異議",         etymology:"dis（反対）+ sent（感じる）→ 違う気持ち",       root:"-sens-", level:2},
  {word:"assent",       meaning:"同意する・賛成",         etymology:"as（〜へ）+ sent（感じる）→ 賛成する",          root:"-sens-", level:2},
  {word:"resent",       meaning:"憤慨する・腹を立てる",   etymology:"re（強調）+ sent（感じる）→ 強く感じる",        root:"-sens-", level:1},
  {word:"resentment",   meaning:"憤り・恨み",             etymology:"re（強調）+ sent（感じる）+ ment",              root:"-sens-", level:2},
  {word:"sentinel",     meaning:"歩哨・見張り",           etymology:"sent（感じる）+ inel → 感知する人",             root:"-sens-", level:2},
  {word:"sentimental",  meaning:"感傷的な・情緒的な",     etymology:"sent（感じる）+ iment + al",                    root:"-sens-", level:1},
  {word:"sentiment",    meaning:"感情・意見・気持ち",     etymology:"sent（感じる）+ iment（こと）",                 root:"-sens-", level:2},
  {word:"insensitive",  meaning:"無神経な・鈍感な",       etymology:"in（否定）+ sens（感じる）+ itive",             root:"-sens-", level:2},
  {word:"desensitize",  meaning:"鈍感にする・脱感作する", etymology:"de（除去）+ sens（感じる）+ itize",             root:"-sens-", level:3},
  {word:"presentiment", meaning:"予感・虫の知らせ",       etymology:"pre（前に）+ sent（感じる）+ iment",            root:"-sens-", level:3},

  // ── -ped-/-pod-（足） ──────────────────────────
  {word:"pedestrian",   meaning:"歩行者・徒歩の",         etymology:"ped（足）+ estrian（〜の人）",                  root:"-ped-", level:1},
  {word:"pedal",        meaning:"ペダル・足で踏む",       etymology:"ped（足）+ al（〜の）",                         root:"-ped-", level:0},
  {word:"impede",       meaning:"妨げる・遅らせる",       etymology:"im（中に）+ ped（足）→ 足を入れて止める",       root:"-ped-", level:2},
  {word:"impediment",   meaning:"障害・妨げ",             etymology:"im（中に）+ ped（足）+ iment",                  root:"-ped-", level:2},
  {word:"expedite",     meaning:"促進する・迅速に処理する",etymology:"ex（外に）+ ped（足）+ ite → 足かせを外す",    root:"-ped-", level:2},
  {word:"expedition",   meaning:"遠征・探検隊",           etymology:"ex（外に）+ ped（足）+ ition",                  root:"-ped-", level:2},
  {word:"pedicure",     meaning:"ペディキュア・足の手入れ",etymology:"ped（足）+ cure（手入れ）",                     root:"-ped-", level:1},
  {word:"biped",        meaning:"二足動物",               etymology:"bi（二つ）+ ped（足）",                         root:"-ped-", level:2},
  {word:"quadruped",    meaning:"四足動物",               etymology:"quadru（四つ）+ ped（足）",                     root:"-ped-", level:2},
  {word:"podium",       meaning:"演壇・表彰台",           etymology:"pod（足）+ ium（場所）→ 足元の台",              root:"-ped-", level:1},
  {word:"tripod",       meaning:"三脚",                   etymology:"tri（三つ）+ pod（足）",                        root:"-ped-", level:1},
  {word:"antipode",     meaning:"対蹠点・正反対",         etymology:"anti（反対）+ pod（足）→ 足が逆の場所",         root:"-ped-", level:3},
  {word:"orthopedics",  meaning:"整形外科",               etymology:"ortho（正しい）+ ped（足）+ ics",               root:"-ped-", level:2},
  {word:"pedagogy",     meaning:"教育法・教授法",         etymology:"ped（子供）+ agogy（導く）",                    root:"-ped-", level:3},
  {word:"pediatrics",   meaning:"小児科",                 etymology:"ped（子供）+ iatrics（医学）",                  root:"-ped-", level:2},

  // ── -man-/-manu-（手） ─────────────────────────
  {word:"manual",       meaning:"手動の・マニュアル",     etymology:"man（手）+ ual（〜の）",                        root:"-man-", level:0},
  {word:"manage",       meaning:"管理する・何とかする",   etymology:"man（手）+ age（行為）→ 手で扱う",              root:"-man-", level:0},
  {word:"manufacture",  meaning:"製造する・製品",         etymology:"manu（手）+ fact（作る）+ ure",                 root:"-man-", level:1},
  {word:"manuscript",   meaning:"原稿・写本",             etymology:"manu（手）+ script（書く）→ 手書き",            root:"-man-", level:2},
  {word:"manipulate",   meaning:"操作する・巧みに扱う",   etymology:"manu（手）+ ipulate（扱う）",                   root:"-man-", level:2},
  {word:"mandate",      meaning:"命令・任務・委任",       etymology:"man（手）+ date（与える）→ 手渡す",             root:"-man-", level:2},
  {word:"mandatory",    meaning:"義務的な・強制的な",     etymology:"man（手）+ dat（与える）+ ory",                 root:"-man-", level:2},
  {word:"manifest",     meaning:"明白にする・現れる",     etymology:"mani（手）+ fest（つかむ）→ 手でつかめる",      root:"-man-", level:2},
  {word:"manifestation",meaning:"現れ・表明・デモ",       etymology:"mani（手）+ fest（つかむ）+ ation",             root:"-man-", level:2},
  {word:"maneuver",     meaning:"作戦行動・巧みに操る",   etymology:"man（手）+ euver（動かす）",                    root:"-man-", level:2},
  {word:"manacle",      meaning:"手錠をかける・束縛",     etymology:"man（手）+ acle（もの）→ 手を縛るもの",         root:"-man-", level:3},
  {word:"emancipate",   meaning:"解放する・自由にする",   etymology:"e（外に）+ man（手）+ cipate（つかむ）→ 手枷を外す",root:"-man-", level:3},
  {word:"manicure",     meaning:"マニキュア・手の手入れ", etymology:"mani（手）+ cure（手入れ）",                    root:"-man-", level:1},
  {word:"manipulative", meaning:"操作的な・巧みな",       etymology:"manu（手）+ ipulative",                         root:"-man-", level:2},

  // ── -cap-/-cept-/-ceive-（取る・つかむ） ─────────
  {word:"capture",      meaning:"捕らえる・獲得",         etymology:"cap（取る）+ ture（こと）",                     root:"-cap-", level:0},
  {word:"capable",      meaning:"有能な・できる",         etymology:"cap（取る）+ able（できる）",                   root:"-cap-", level:0},
  {word:"concept",      meaning:"概念・コンセプト",       etymology:"con（共に）+ cept（取る）→ まとめてつかむ",     root:"-cap-", level:1},
  {word:"accept",       meaning:"受け入れる・受諾する",   etymology:"ac（〜へ）+ cept（取る）",                      root:"-cap-", level:0},
  {word:"except",       meaning:"〜を除いて",             etymology:"ex（外に）+ cept（取る）→ 外に取り出す",        root:"-cap-", level:0},
  {word:"intercept",    meaning:"遮断する・傍受する",     etymology:"inter（間に）+ cept（取る）→ 途中で取る",       root:"-cap-", level:2},
  {word:"perceive",     meaning:"知覚する・理解する",     etymology:"per（完全に）+ ceive（取る）→ 完全に取り込む",  root:"-cap-", level:2},
  {word:"perception",   meaning:"知覚・認識",             etymology:"per（完全に）+ cept（取る）+ ion",              root:"-cap-", level:2},
  {word:"receive",      meaning:"受け取る",               etymology:"re（後ろ）+ ceive（取る）",                     root:"-cap-", level:0},
  {word:"conceive",     meaning:"考え出す・妊娠する",     etymology:"con（共に）+ ceive（取る）",                    root:"-cap-", level:2},
  {word:"deceive",      meaning:"だます・欺く",           etymology:"de（離れて）+ ceive（取る）→ 取り上げる",       root:"-cap-", level:2},
  {word:"deception",    meaning:"欺き・詐欺",             etymology:"de（離れて）+ cept（取る）+ ion",               root:"-cap-", level:2},
  {word:"susceptible",  meaning:"影響されやすい・敏感な", etymology:"sus（下から）+ cept（取る）+ ible",             root:"-cap-", level:3},
  {word:"inception",    meaning:"始まり・開始",           etymology:"in（中に）+ cept（取る）+ ion → 取り込み始め",  root:"-cap-", level:3},
  {word:"precept",      meaning:"教訓・規則",             etymology:"pre（前に）+ cept（取る）→ 先に取り込む",       root:"-cap-", level:3},
  {word:"receptive",    meaning:"受容的な・受け入れる",   etymology:"re（後ろ）+ cept（取る）+ ive",                 root:"-cap-", level:2},
  {word:"anticipate",   meaning:"予期する・期待する",     etymology:"ante（前に）+ cap（取る）→ 先につかむ",         root:"-cap-", level:2},
  {word:"capacity",     meaning:"容量・能力・収容力",     etymology:"cap（取る）+ acity（性質）",                    root:"-cap-", level:1},
  {word:"incapable",    meaning:"できない・無能な",       etymology:"in（否定）+ cap（取る）+ able",                 root:"-cap-", level:2},
  {word:"emancipate",   meaning:"解放する",               etymology:"e（外に）+ man（手）+ cap（つかむ）+ ate",      root:"-cap-", level:3},

  // ── -fac-/-fect-/-fic-（作る・する） ───────────
  {word:"fact",         meaning:"事実",                   etymology:"fac（作る）+ t → 作られたこと＝起きたこと",     root:"-fac-", level:0},
  {word:"factor",       meaning:"要因・要素",             etymology:"fac（作る）+ tor（もの）",                      root:"-fac-", level:1},
  {word:"factory",      meaning:"工場",                   etymology:"fac（作る）+ tory（場所）",                     root:"-fac-", level:0},
  {word:"facilitate",   meaning:"促進する・容易にする",   etymology:"fac（作る・簡単）+ ilitate",                    root:"-fac-", level:2},
  {word:"faculty",      meaning:"能力・学部・教職員",     etymology:"fac（作る）+ ulty（性質）→ 作り出す力",         root:"-fac-", level:2},
  {word:"effect",       meaning:"結果・効果",             etymology:"ef（外に）+ fect（作る）→ 作り出されたもの",    root:"-fac-", level:0},
  {word:"effective",    meaning:"効果的な・有効な",       etymology:"ef（外に）+ fect（作る）+ ive",                 root:"-fac-", level:1},
  {word:"affect",       meaning:"影響を与える",           etymology:"af（〜に）+ fect（作る）→ 変化を作り出す",      root:"-fac-", level:1},
  {word:"defect",       meaning:"欠陥・欠点",             etymology:"de（離れて）+ fect（作る）→ 作りが外れた",      root:"-fac-", level:2},
  {word:"infect",       meaning:"感染させる",             etymology:"in（中に）+ fect（作る）→ 中で変化を作る",      root:"-fac-", level:1},
  {word:"infection",    meaning:"感染・伝染",             etymology:"in（中に）+ fect（作る）+ ion",                 root:"-fac-", level:1},
  {word:"perfect",      meaning:"完璧な・完全にする",     etymology:"per（完全に）+ fect（作る）→ 完全に作られた",   root:"-fac-", level:0},
  {word:"perfection",   meaning:"完璧・完全",             etymology:"per（完全に）+ fect（作る）+ ion",              root:"-fac-", level:1},
  {word:"deficient",    meaning:"不十分な・欠乏している", etymology:"de（離れて）+ fic（作る）+ ient",               root:"-fac-", level:2},
  {word:"deficiency",   meaning:"不足・欠乏",             etymology:"de（離れて）+ fic（作る）+ iency",              root:"-fac-", level:2},
  {word:"proficient",   meaning:"熟練した・堪能な",       etymology:"pro（前に）+ fic（作る）+ ient → 先に進んで作れる",root:"-fac-", level:2},
  {word:"sufficient",   meaning:"十分な",                 etymology:"suf（下から）+ fic（作る）+ ient → 十分に作られた",root:"-fac-", level:1},
  {word:"insufficient", meaning:"不十分な",               etymology:"in（否定）+ suf + fic（作る）+ ient",           root:"-fac-", level:2},
  {word:"efficient",    meaning:"効率的な",               etymology:"ef（外に）+ fic（作る）+ ient",                 root:"-fac-", level:1},
  {word:"efficiency",   meaning:"効率・能率",             etymology:"ef（外に）+ fic（作る）+ iency",                root:"-fac-", level:1},
  {word:"magnificent",  meaning:"壮大な・素晴らしい",     etymology:"magni（大きく）+ fic（作る）+ ent",             root:"-fac-", level:2},
  {word:"sacrifice",    meaning:"犠牲・生け贄",           etymology:"sacri（神聖な）+ fic（作る）+ e",               root:"-fac-", level:2},
  {word:"artificial",   meaning:"人工の・不自然な",       etymology:"arti（技術）+ fic（作る）+ ial",                root:"-fac-", level:1},
  {word:"beneficial",   meaning:"有益な・ためになる",     etymology:"bene（よく）+ fic（作る）+ ial",                root:"-fac-", level:2},
  {word:"terrific",     meaning:"素晴らしい・ひどい",     etymology:"terr（恐怖）+ ific（作る）",                    root:"-fac-", level:1},
  {word:"specific",     meaning:"特定の・具体的な",       etymology:"spec（種）+ ific（作る）→ 種を作る",            root:"-fac-", level:1},
  {word:"modify",       meaning:"修正する・変える",       etymology:"mod（方法）+ ify（作る）",                      root:"-fac-", level:1},
  {word:"amplify",      meaning:"増幅する・拡大する",     etymology:"ampl（広い）+ ify（作る）",                     root:"-fac-", level:2},
  {word:"notify",       meaning:"知らせる・通知する",     etymology:"not（知る）+ ify（作る）",                      root:"-fac-", level:1},
  {word:"certify",      meaning:"証明する・認定する",     etymology:"cert（確かな）+ ify（作る）",                   root:"-fac-", level:2},
  {word:"justify",      meaning:"正当化する",             etymology:"just（正しい）+ ify（作る）",                   root:"-fac-", level:2},
  {word:"satisfy",      meaning:"満足させる",             etymology:"satis（十分な）+ fy（作る）",                   root:"-fac-", level:0},
  {word:"rectify",      meaning:"修正する・正す",         etymology:"rect（正しい）+ ify（作る）",                   root:"-fac-", level:2},
  {word:"ratify",       meaning:"批准する・承認する",     etymology:"rat（計算）+ ify（作る）→ 正式に認める",        root:"-fac-", level:3},
  {word:"dignify",      meaning:"威厳を与える・高める",   etymology:"dign（価値）+ ify（作る）",                     root:"-fac-", level:3},
  {word:"pacify",       meaning:"なだめる・平和にする",   etymology:"pac（平和）+ ify（作る）",                      root:"-fac-", level:2},
  {word:"nullify",      meaning:"無効にする",             etymology:"null（ゼロ）+ ify（作る）",                     root:"-fac-", level:3},
  {word:"fortify",      meaning:"強化する・要塞にする",   etymology:"fort（強い）+ ify（作る）",                     root:"-fac-", level:2},
  {word:"testify",      meaning:"証言する・証明する",     etymology:"test（証人）+ ify（作る）",                     root:"-fac-", level:2},

  ];

  if(!window.WORD_DATA_RAW) window.WORD_DATA_RAW=[];
  window.WORD_DATA_RAW=window.WORD_DATA_RAW.concat(d);
})();
