/**
 * data-root-5.js — 語根データ前半（約360語）
 * -lect-/-leg-, -liber-, -lingu-, -liter-, -loc-, -log-/-logue-, -loqu-,
 * -luc-/-lum-, -man-/-manu-, -med-/-medi-, -mem-, -mit-/-miss-,
 * -mor-/-mort-, -mot-/-mov-, -nat-/-nasc-, -nom-/-nym-,
 * -pend-/-pens-, -plic-/-ply-, -port-, -pos-/-pon-,
 * -press-, -prob-/-prov-, -reg-/-rect-, -rupt-
 */
(function(){
  var d = [

  // ── -lect-/-leg-（選ぶ・読む） ─────────────────
  {word:"select",       meaning:"選ぶ・選択する",           etymology:"se（離れて）+ lect（選ぶ）",              root:"-lect-", level:0},
  {word:"collect",      meaning:"集める・収集する",          etymology:"col（共に）+ lect（選ぶ）",              root:"-lect-", level:0},
  {word:"elect",        meaning:"選出する",                 etymology:"e（外に）+ lect（選ぶ）",                root:"-lect-", level:1},
  {word:"intellect",    meaning:"知性・理解力",             etymology:"intel（間に）+ lect（選ぶ）",            root:"-lect-", level:2},
  {word:"neglect",      meaning:"無視する・怠る",            etymology:"neg（否定）+ lect（選ぶ）",              root:"-lect-", level:1},
  {word:"lecture",      meaning:"講義・説教",               etymology:"lect（読む）+ ure",                      root:"-lect-", level:0},
  {word:"recollect",    meaning:"思い出す",                 etymology:"re（再び）+ col + lect（選ぶ）",         root:"-lect-", level:2},
  {word:"eligible",     meaning:"資格のある",               etymology:"e（外に）+ lig（選ぶ）+ ible",           root:"-lect-", level:2},
  {word:"legend",       meaning:"伝説・説明文",             etymology:"leg（読む）+ end",                       root:"-lect-", level:1},
  {word:"legible",      meaning:"読みやすい",               etymology:"leg（読む）+ ible",                      root:"-lect-", level:2},
  {word:"diligent",     meaning:"勤勉な",                   etymology:"di（完全に）+ lig（選ぶ）+ ent",         root:"-lect-", level:1},
  {word:"predilection", meaning:"好み・傾向",               etymology:"pre（前に）+ di + lect（選ぶ）+ ion",    root:"-lect-", level:3},

  // ── -liber-（自由） ───────────────────────────
  {word:"liberal",      meaning:"自由主義の・寛大な",        etymology:"liber（自由）+ al",                      root:"-liber-", level:1},
  {word:"liberty",      meaning:"自由",                     etymology:"liber（自由）+ ty",                      root:"-liber-", level:1},
  {word:"liberate",     meaning:"解放する",                 etymology:"liber（自由）+ ate",                     root:"-liber-", level:1},
  {word:"deliberate",   meaning:"故意の・熟考する",          etymology:"de（完全に）+ liber（自由）+ ate",       root:"-liber-", level:2},
  {word:"deliver",      meaning:"届ける・解放する",          etymology:"de（完全に）+ liver（自由にする）",      root:"-liber-", level:0},
  {word:"liberation",   meaning:"解放",                     etymology:"liber（自由）+ ation",                   root:"-liber-", level:2},
  {word:"libertarian",  meaning:"自由意志論者",              etymology:"liber（自由）+ tarian",                  root:"-liber-", level:3},

  // ── -lingu-（言語・舌） ────────────────────────
  {word:"language",     meaning:"言語",                     etymology:"lingu（舌）+ age",                       root:"-lingu-", level:0},
  {word:"bilingual",    meaning:"二言語を話す",             etymology:"bi（二つ）+ lingu（言語）+ al",          root:"-lingu-", level:1},
  {word:"multilingual", meaning:"多言語の",                  etymology:"multi（多く）+ lingu（言語）+ al",       root:"-lingu-", level:2},
  {word:"linguistics",  meaning:"言語学",                   etymology:"lingu（言語）+ istics",                  root:"-lingu-", level:2},
  {word:"sublingual",   meaning:"舌下の",                   etymology:"sub（下に）+ lingu（舌）+ al",           root:"-lingu-", level:3},

  // ── -liter-（文字） ────────────────────────────
  {word:"literal",      meaning:"文字通りの",               etymology:"liter（文字）+ al",                      root:"-liter-", level:1},
  {word:"literary",     meaning:"文学の",                   etymology:"liter（文字）+ ary",                     root:"-liter-", level:1},
  {word:"literature",   meaning:"文学・文献",               etymology:"liter（文字）+ ature",                   root:"-liter-", level:1},
  {word:"literate",     meaning:"読み書きできる",            etymology:"liter（文字）+ ate",                     root:"-liter-", level:1},
  {word:"illiterate",   meaning:"読み書きできない",          etymology:"il（否定）+ liter（文字）+ ate",         root:"-liter-", level:2},
  {word:"alliteration", meaning:"頭韻",                     etymology:"al（〜へ）+ liter（文字）+ ation",       root:"-liter-", level:3},
  {word:"obliterate",   meaning:"消し去る・抹消する",        etymology:"ob（反対）+ liter（文字）+ ate",         root:"-liter-", level:3},

  // ── -loc-（場所） ─────────────────────────────
  {word:"local",        meaning:"地元の・局所的な",          etymology:"loc（場所）+ al",                        root:"-loc-", level:0},
  {word:"locate",       meaning:"位置を特定する",            etymology:"loc（場所）+ ate",                       root:"-loc-", level:0},
  {word:"location",     meaning:"場所・位置",               etymology:"loc（場所）+ ation",                     root:"-loc-", level:0},
  {word:"relocate",     meaning:"移転する",                 etymology:"re（再び）+ loc（場所）+ ate",           root:"-loc-", level:1},
  {word:"allocate",     meaning:"割り当てる",               etymology:"al（〜に）+ loc（場所）+ ate",           root:"-loc-", level:2},
  {word:"dislocate",    meaning:"脱臼させる",               etymology:"dis（離れて）+ loc（場所）+ ate",        root:"-loc-", level:2},
  {word:"locomotive",   meaning:"機関車",                   etymology:"loc（場所）+ mot（動く）+ ive",          root:"-loc-", level:1},
  {word:"locale",       meaning:"舞台・現場",               etymology:"loc（場所）",                            root:"-loc-", level:2},
  {word:"locality",     meaning:"地域・所在地",              etymology:"loc（場所）+ al + ity",                  root:"-loc-", level:2},
  {word:"collocate",    meaning:"連語を形成する",            etymology:"col（共に）+ loc（場所）+ ate",          root:"-loc-", level:3},
  {word:"locus",        meaning:"軌跡・中心",               etymology:"loc（場所）→ ラテン語「場所」",          root:"-loc-", level:3},

  // ── -log-/-logue-（言葉・学問） ─────────────
  {word:"logic",        meaning:"論理",                     etymology:"log（言葉・理論）+ ic",                  root:"-log-", level:0},
  {word:"dialogue",     meaning:"対話",                     etymology:"dia（二つの間）+ logue（言葉）",          root:"-log-", level:0},
  {word:"monologue",    meaning:"独白",                     etymology:"mono（一つ）+ logue（言葉）",            root:"-log-", level:1},
  {word:"catalogue",    meaning:"目録",                     etymology:"cata（下に）+ logue（言葉）",            root:"-log-", level:1},
  {word:"prologue",     meaning:"序文・序幕",               etymology:"pro（前に）+ logue（言葉）",             root:"-log-", level:1},
  {word:"epilogue",     meaning:"後記",                     etymology:"epi（後に）+ logue（言葉）",             root:"-log-", level:2},
  {word:"apology",      meaning:"謝罪・弁明",               etymology:"apo（離れて）+ logy（言葉）",            root:"-log-", level:1},
  {word:"biology",      meaning:"生物学",                   etymology:"bio（生命）+ logy（学問）",               root:"-log-", level:0},
  {word:"psychology",   meaning:"心理学",                   etymology:"psycho（心）+ logy（学問）",              root:"-log-", level:1},
  {word:"technology",   meaning:"技術",                     etymology:"techno（技術）+ logy（学問）",            root:"-log-", level:0},
  {word:"ecology",      meaning:"生態学",                   etymology:"eco（環境）+ logy（学問）",               root:"-log-", level:1},
  {word:"analogy",      meaning:"類似・アナロジー",          etymology:"ana（対応して）+ logy（言葉）",           root:"-log-", level:2},
  {word:"eulogy",       meaning:"賛辞・追悼演説",            etymology:"eu（良い）+ logy（言葉）",               root:"-log-", level:3},
  {word:"tautology",    meaning:"同義反復・冗長",            etymology:"tauto（同じ）+ logy（言葉）",            root:"-log-", level:3},
  {word:"neologism",    meaning:"新語・造語",               etymology:"neo（新しい）+ log（言葉）+ ism",         root:"-log-", level:3},

  // ── -loqu-（話す） ─────────────────────────────
  {word:"eloquent",     meaning:"雄弁な",                   etymology:"e（外に）+ loqu（話す）+ ent",           root:"-loqu-", level:2},
  {word:"colloquial",   meaning:"口語の",                   etymology:"col（共に）+ loqu（話す）+ ial",         root:"-loqu-", level:2},
  {word:"loquacious",   meaning:"おしゃべりな",              etymology:"loqu（話す）+ acious",                   root:"-loqu-", level:3},
  {word:"ventriloquist",meaning:"腹話術師",                  etymology:"ventri（腹）+ loqu（話す）+ ist",        root:"-loqu-", level:3},
  {word:"soliloquy",    meaning:"独り言・独白",              etymology:"sol（一人）+ iloqu（話す）+ y",          root:"-loqu-", level:3},

  // ── -luc-/-lum-（光） ────────────────────────
  {word:"lucid",        meaning:"明晰な",                   etymology:"luc（光）+ id",                          root:"-luc-", level:2},
  {word:"illuminate",   meaning:"照らす・解明する",          etymology:"il（中に）+ lumin（光）+ ate",           root:"-luc-", level:2},
  {word:"luminous",     meaning:"発光する・輝く",            etymology:"lumin（光）+ ous",                       root:"-luc-", level:2},
  {word:"translucent",  meaning:"半透明の",                  etymology:"trans（通して）+ luc（光）+ ent",        root:"-luc-", level:2},
  {word:"elucidate",    meaning:"解明する",                  etymology:"e（外に）+ lucid（明確な）+ ate",        root:"-luc-", level:3},
  {word:"luminary",     meaning:"著名人・発光体",            etymology:"lumin（光）+ ary",                       root:"-luc-", level:3},
  {word:"illustrate",   meaning:"説明する・図解する",        etymology:"il（中に）+ lustr（光）+ ate",           root:"-luc-", level:1},
  {word:"lustrous",     meaning:"光沢のある",               etymology:"lustr（光）+ ous",                       root:"-luc-", level:3},
  {word:"pellucid",     meaning:"透明な・明快な",            etymology:"per（完全に）+ luc（光）+ id",           root:"-luc-", level:3},
  {word:"luminesce",    meaning:"発光する",                  etymology:"lumin（光）+ esce（〜になる）",          root:"-luc-", level:3},

  // ── -man-/-manu-（手） ──────────────────────
  {word:"manual",       meaning:"手動の・説明書",            etymology:"manu（手）+ al",                         root:"-man-", level:0},
  {word:"manage",       meaning:"管理する",                  etymology:"man（手）+ age",                         root:"-man-", level:0},
  {word:"manufacture",  meaning:"製造する",                  etymology:"manu（手）+ facture（作る）",            root:"-man-", level:1},
  {word:"manifest",     meaning:"明らかにする",              etymology:"mani（手）+ fest（つかむ）",             root:"-man-", level:2},
  {word:"manipulate",   meaning:"操作する",                  etymology:"mani（手）+ pulate（満たす）",           root:"-man-", level:2},
  {word:"manuscript",   meaning:"原稿・手書き文書",          etymology:"manu（手）+ script（書いた）",           root:"-man-", level:2},
  {word:"maintain",     meaning:"維持する",                  etymology:"main（手）+ tain（保持する）",           root:"-man-", level:1},
  {word:"mandate",      meaning:"命令・権限",                etymology:"man（手）+ date（与える）",              root:"-man-", level:2},
  {word:"emancipate",   meaning:"解放する",                  etymology:"e（外に）+ man（手）+ cipate（取る）",   root:"-man-", level:3},
  {word:"maneuver",     meaning:"作戦行動・巧みに動かす",    etymology:"main（手）+ oeuvre（作業）",             root:"-man-", level:2},
  {word:"manicure",     meaning:"マニキュア",                etymology:"mani（手）+ cure（手入れ）",             root:"-man-", level:1},
  {word:"mandatory",    meaning:"義務的な・強制的な",         etymology:"man（手）+ dat（与える）+ ory",          root:"-man-", level:2},

  // ── -med-/-medi-（中間・治す） ──────────────
  {word:"medium",       meaning:"媒体・中間",               etymology:"medi（中間）+ um",                       root:"-med-", level:0},
  {word:"medical",      meaning:"医学の",                   etymology:"med（治す）+ ical",                      root:"-med-", level:0},
  {word:"mediate",      meaning:"仲介する",                  etymology:"medi（中間）+ ate",                      root:"-med-", level:2},
  {word:"medieval",     meaning:"中世の",                   etymology:"medi（中間）+ eval（時代）",             root:"-med-", level:1},
  {word:"intermediate", meaning:"中間の・中級の",            etymology:"inter（間）+ medi（中間）+ ate",         root:"-med-", level:1},
  {word:"medicine",     meaning:"医学・薬",                  etymology:"med（治す）+ icine",                     root:"-med-", level:0},
  {word:"remedy",       meaning:"治療法・改善策",            etymology:"re（再び）+ med（治す）+ y",             root:"-med-", level:1},
  {word:"meditate",     meaning:"瞑想する・熟考する",        etymology:"medi（中間）+ tate",                     root:"-med-", level:2},
  {word:"mediocre",     meaning:"平凡な・二流の",            etymology:"medi（中間）+ ocre（尖り）",             root:"-med-", level:2},
  {word:"immediately",  meaning:"すぐに",                   etymology:"im（否定）+ medi（中間）+ ate + ly",     root:"-med-", level:0},
  {word:"remediate",    meaning:"修復する",                  etymology:"re（再び）+ medi（治す）+ ate",          root:"-med-", level:2},

  // ── -mem-（記憶） ────────────────────────────
  {word:"memory",       meaning:"記憶・思い出",              etymology:"mem（記憶）+ ory",                       root:"-mem-", level:0},
  {word:"remember",     meaning:"覚えている",               etymology:"re（再び）+ member（記憶する）",         root:"-mem-", level:0},
  {word:"memorial",     meaning:"記念の・追悼の",            etymology:"memori（記憶）+ al",                     root:"-mem-", level:1},
  {word:"memorize",     meaning:"暗記する",                 etymology:"memori（記憶）+ ize",                    root:"-mem-", level:1},
  {word:"commemorate",  meaning:"記念する",                  etymology:"com（共に）+ memor（記憶）+ ate",        root:"-mem-", level:2},
  {word:"memento",      meaning:"記念品・形見",              etymology:"memento（思い出せ）→ ラテン語命令形",    root:"-mem-", level:2},
  {word:"memoir",       meaning:"回顧録",                   etymology:"mem（記憶）+ oir（フランス語）",         root:"-mem-", level:2},
  {word:"mnemonics",    meaning:"記憶術",                   etymology:"mnemon（記憶する人）→ ギリシャ語",       root:"-mem-", level:3},
  {word:"immemorial",   meaning:"太古の・大昔からの",        etymology:"im（否定）+ memorial（記憶できる）",     root:"-mem-", level:3},

  // ── -mit-/-miss-（送る） ─────────────────────
  {word:"mission",      meaning:"使命・任務",               etymology:"miss（送る）+ ion",                      root:"-mit-", level:0},
  {word:"submit",       meaning:"提出する・服従する",        etymology:"sub（下に）+ mit（送る）",              root:"-mit-", level:1},
  {word:"commit",       meaning:"約束する・犯す",            etymology:"com（完全に）+ mit（送る）",             root:"-mit-", level:1},
  {word:"permit",       meaning:"許可する",                 etymology:"per（完全に）+ mit（送る）",             root:"-mit-", level:1},
  {word:"omit",         meaning:"省略する",                 etymology:"o（離れて）+ mit（送る）",               root:"-mit-", level:2},
  {word:"emit",         meaning:"放出する",                  etymology:"e（外に）+ mit（送る）",                 root:"-mit-", level:2},
  {word:"transmit",     meaning:"送信する",                 etymology:"trans（超えて）+ mit（送る）",           root:"-mit-", level:1},
  {word:"missile",      meaning:"ミサイル",                  etymology:"miss（送る）+ ile",                      root:"-mit-", level:1},
  {word:"admission",    meaning:"入場・承認",               etymology:"ad（〜へ）+ miss（送る）+ ion",          root:"-mit-", level:1},
  {word:"remission",    meaning:"緩解・減刑",               etymology:"re（元に）+ miss（送る）+ ion",          root:"-mit-", level:3},
  {word:"intermittent", meaning:"断続的な",                 etymology:"inter（間に）+ mitt（送る）+ ent",        root:"-mit-", level:2},
  {word:"demise",       meaning:"死去・終焉",               etymology:"de（下に）+ mise（送る）",               root:"-mit-", level:3},

  // ── -mor-/-mort-（死） ──────────────────────
  {word:"mortal",       meaning:"死すべき・致命的な",        etymology:"mort（死）+ al",                         root:"-mor-", level:1},
  {word:"immortal",     meaning:"不死の・永遠の",           etymology:"im（否定）+ mort（死）+ al",             root:"-mor-", level:1},
  {word:"mortgage",     meaning:"住宅ローン・抵当",          etymology:"mort（死）+ gage（誓約）",              root:"-mor-", level:2},
  {word:"morbid",       meaning:"病的な・不健全な",          etymology:"morb（病気）+ id",                       root:"-mor-", level:3},
  {word:"mortify",      meaning:"屈辱を与える",              etymology:"mort（死）+ ify",                        root:"-mor-", level:3},
  {word:"moribund",     meaning:"瀕死の・廃れかけた",        etymology:"mori（死ぬ）+ bund",                     root:"-mor-", level:3},
  {word:"amortize",     meaning:"償却する",                  etymology:"a（〜に）+ mort（死）+ ize",             root:"-mor-", level:3},
  {word:"mortuary",     meaning:"霊安室・葬儀の",            etymology:"mort（死）+ uary",                       root:"-mor-", level:2},

  // ── -mot-/-mov-（動く） ─────────────────────
  {word:"move",         meaning:"動く・引っ越す",            etymology:"mov（動く）",                            root:"-mot-", level:0},
  {word:"motion",       meaning:"動き・提案",               etymology:"mot（動く）+ ion",                       root:"-mot-", level:0},
  {word:"motor",        meaning:"モーター",                 etymology:"mot（動く）+ or",                        root:"-mot-", level:0},
  {word:"remote",       meaning:"遠隔の・離れた",            etymology:"re（離れて）+ mot（動かす）+ e",         root:"-mot-", level:0},
  {word:"promote",      meaning:"昇進させる・促進する",      etymology:"pro（前に）+ mot（動かす）+ e",          root:"-mot-", level:1},
  {word:"emotion",      meaning:"感情",                     etymology:"e（外に）+ mot（動かす）+ ion",          root:"-mot-", level:0},
  {word:"motivate",     meaning:"動機づける",               etymology:"motiv（動く）+ ate",                     root:"-mot-", level:1},
  {word:"commotion",    meaning:"騒ぎ・混乱",               etymology:"com（強意）+ mot（動く）+ ion",          root:"-mot-", level:2},
  {word:"demote",       meaning:"降格させる",               etymology:"de（下に）+ mot（動かす）+ e",           root:"-mot-", level:2},
  {word:"momentum",     meaning:"勢い・運動量",              etymology:"mom（動かす）+ entum",                   root:"-mot-", level:2},
  {word:"motive",       meaning:"動機",                     etymology:"motiv（動く）",                          root:"-mot-", level:1},
  {word:"immovable",    meaning:"動かせない",               etymology:"im（否定）+ mov（動く）+ able",          root:"-mot-", level:2},

  // ── -nat-/-nasc-（生まれる） ────────────────
  {word:"nature",       meaning:"自然・本質",               etymology:"nat（生まれる）+ ure",                   root:"-nat-", level:0},
  {word:"natural",      meaning:"自然な・当然の",            etymology:"nat（生まれる）+ ural",                  root:"-nat-", level:0},
  {word:"nation",       meaning:"国家",                     etymology:"nat（生まれる）+ ion",                   root:"-nat-", level:0},
  {word:"native",       meaning:"生まれた土地の",            etymology:"nat（生まれる）+ ive",                   root:"-nat-", level:0},
  {word:"innate",       meaning:"生まれつきの",              etymology:"in（中に）+ nat（生まれる）+ e",         root:"-nat-", level:2},
  {word:"prenatal",     meaning:"出生前の",                 etymology:"pre（前）+ nat（生まれる）+ al",         root:"-nat-", level:2},
  {word:"nascent",      meaning:"芽生えつつある・初期の",    etymology:"nasc（生まれる）+ ent",                  root:"-nat-", level:3},
  {word:"renaissance",  meaning:"ルネサンス・復興",          etymology:"re（再び）+ nasc（生まれる）+ ance",     root:"-nat-", level:2},
  {word:"cognate",      meaning:"同語源の",                 etymology:"co（共に）+ gnat（生まれる）+ e",        root:"-nat-", level:3},
  {word:"nationality",  meaning:"国籍",                     etymology:"nat（生まれる）+ ional + ity",           root:"-nat-", level:1},

  // ── -nom-/-nym-（名前・法則） ───────────────
  {word:"economy",      meaning:"経済",                     etymology:"eco（家）+ nom（管理）+ y",              root:"-nom-", level:0},
  {word:"astronomy",    meaning:"天文学",                   etymology:"astro（星）+ nom（法則）+ y",            root:"-nom-", level:1},
  {word:"anonymous",    meaning:"匿名の",                   etymology:"an（否定）+ onym（名前）+ ous",          root:"-nom-", level:2},
  {word:"synonym",      meaning:"同義語",                   etymology:"syn（同じ）+ onym（名前）",              root:"-nom-", level:1},
  {word:"antonym",      meaning:"反意語",                   etymology:"anti（反対）+ onym（名前）",             root:"-nom-", level:1},
  {word:"pseudonym",    meaning:"ペンネーム",               etymology:"pseudo（偽）+ nym（名前）",              root:"-nom-", level:2},
  {word:"autonomy",     meaning:"自治・自律",               etymology:"auto（自己）+ nom（法則）+ y",           root:"-nom-", level:2},
  {word:"taxonomy",     meaning:"分類学",                   etymology:"taxis（順序）+ nom（法則）+ y",          root:"-nom-", level:3},
  {word:"acronym",      meaning:"頭字語（NASAなど）",        etymology:"acr（先端）+ onym（名前）",              root:"-nom-", level:2},
  {word:"eponym",       meaning:"名前の由来となった人・語",  etymology:"epi（上に）+ onym（名前）",              root:"-nom-", level:3},

  // ── -pend-/-pens-（ぶら下がる・量る） ────────
  {word:"depend",       meaning:"頼る・次第である",          etymology:"de（下に）+ pend（ぶら下がる）",         root:"-pend-", level:0},
  {word:"suspend",      meaning:"停止する・吊るす",          etymology:"sus（下から）+ pend（ぶら下がる）",      root:"-pend-", level:1},
  {word:"independent",  meaning:"独立した",                 etymology:"in（否定）+ de + pend + ent",            root:"-pend-", level:0},
  {word:"pending",      meaning:"保留中の",                 etymology:"pend（ぶら下がる）+ ing",                root:"-pend-", level:1},
  {word:"append",       meaning:"付け加える",               etymology:"ap（〜へ）+ pend（ぶら下げる）",         root:"-pend-", level:2},
  {word:"expenditure",  meaning:"支出",                     etymology:"ex（外に）+ pend（量る）+ iture",        root:"-pend-", level:2},
  {word:"compensate",   meaning:"補償する",                 etymology:"com（共に）+ pens（量る）+ ate",         root:"-pend-", level:2},
  {word:"pension",      meaning:"年金",                     etymology:"pens（量る）+ ion",                      root:"-pend-", level:1},
  {word:"perpendicular",meaning:"垂直の",                   etymology:"per（完全に）+ pend（ぶら下がる）+ icular",root:"-pend-",level:2},
  {word:"propensity",   meaning:"傾向・性向",               etymology:"pro（前に）+ pens（ぶら下がる）+ ity",   root:"-pend-", level:3},
  {word:"indispensable",meaning:"不可欠な",                  etymology:"in（否定）+ dis + pens（量る）+ able",   root:"-pend-", level:2},

  // ── -plic-/-ply-（折る・重ねる） ─────────────
  {word:"apply",        meaning:"申し込む・適用する",        etymology:"ap（〜へ）+ ply（折る）",                root:"-plic-", level:0},
  {word:"reply",        meaning:"返答する",                 etymology:"re（再び）+ ply（折る）",                root:"-plic-", level:0},
  {word:"imply",        meaning:"暗示する",                 etymology:"im（中に）+ ply（折る）",                root:"-plic-", level:1},
  {word:"comply",       meaning:"従う",                     etymology:"com（完全に）+ ply（折る）",             root:"-plic-", level:2},
  {word:"multiply",     meaning:"掛け算する・増やす",        etymology:"multi（多く）+ ply（折る）",             root:"-plic-", level:1},
  {word:"explicit",     meaning:"明白な",                   etymology:"ex（外に）+ plic（折る）+ it",           root:"-plic-", level:2},
  {word:"implicit",     meaning:"暗黙の",                   etymology:"im（中に）+ plic（折る）+ it",           root:"-plic-", level:2},
  {word:"complicate",   meaning:"複雑にする",               etymology:"com（共に）+ plic（折る）+ ate",         root:"-plic-", level:1},
  {word:"duplicate",    meaning:"複製する",                 etymology:"du（二つ）+ plic（折る）+ ate",          root:"-plic-", level:2},
  {word:"replicate",    meaning:"複製する",                 etymology:"re（再び）+ plic（折る）+ ate",          root:"-plic-", level:2},
  {word:"supplicate",   meaning:"嘆願する",                 etymology:"sub（下に）+ plic（折る）+ ate",         root:"-plic-", level:3},

  // ── -port-（運ぶ） ───────────────────────────
  {word:"port",         meaning:"港・入力端子",              etymology:"port（運ぶ）→ 荷を運び込む場所",         root:"-port-", level:0},
  {word:"import",       meaning:"輸入する",                  etymology:"im（中に）+ port（運ぶ）",               root:"-port-", level:0},
  {word:"export",       meaning:"輸出する",                  etymology:"ex（外に）+ port（運ぶ）",               root:"-port-", level:0},
  {word:"transport",    meaning:"輸送する",                  etymology:"trans（超えて）+ port（運ぶ）",          root:"-port-", level:0},
  {word:"report",       meaning:"報告する",                  etymology:"re（再び）+ port（運ぶ）→ 持ち帰る",     root:"-port-", level:0},
  {word:"support",      meaning:"支持する・支援する",         etymology:"sub（下に）+ port（運ぶ）→ 下から運ぶ",  root:"-port-", level:0},
  {word:"deport",       meaning:"国外追放する",              etymology:"de（離れて）+ port（運ぶ）",             root:"-port-", level:2},
  {word:"important",    meaning:"重要な",                   etymology:"im（中に）+ port（運ぶ）+ ant → 価値を運ぶ", root:"-port-", level:0},
  {word:"portable",     meaning:"携帯可能な",               etymology:"port（運ぶ）+ able",                     root:"-port-", level:1},
  {word:"portfolio",    meaning:"作品集・ポートフォリオ",     etymology:"port（運ぶ）+ folio（紙）",              root:"-port-", level:2},
  {word:"comportment",  meaning:"立ち居振る舞い",            etymology:"com（共に）+ port（運ぶ）+ ment",        root:"-port-", level:3},
  {word:"purport",      meaning:"主張する・意図する",         etymology:"pur（前に）+ port（運ぶ）→ 前に持つ",    root:"-port-", level:3},

  // ── -pos-/-pon-（置く） ──────────────────────
  {word:"position",     meaning:"位置・立場",               etymology:"pos（置く）+ ition",                     root:"-pos-", level:0},
  {word:"compose",      meaning:"作曲する・構成する",        etymology:"com（共に）+ pose（置く）",              root:"-pos-", level:1},
  {word:"expose",       meaning:"さらす・暴露する",          etymology:"ex（外に）+ pose（置く）",               root:"-pos-", level:1},
  {word:"oppose",       meaning:"反対する",                 etymology:"op（対して）+ pose（置く）",             root:"-pos-", level:1},
  {word:"impose",       meaning:"課す・押しつける",          etymology:"im（上に）+ pose（置く）",               root:"-pos-", level:2},
  {word:"propose",      meaning:"提案する",                 etymology:"pro（前に）+ pose（置く）",              root:"-pos-", level:1},
  {word:"dispose",      meaning:"処分する",                 etymology:"dis（離れて）+ pose（置く）",            root:"-pos-", level:2},
  {word:"postpone",     meaning:"延期する",                  etymology:"post（後に）+ pon（置く）+ e",           root:"-pos-", level:1},
  {word:"component",    meaning:"構成要素",                 etymology:"com（共に）+ pon（置く）+ ent",          root:"-pos-", level:2},
  {word:"exponent",     meaning:"指数・代弁者",              etymology:"ex（外に）+ pon（置く）+ ent",           root:"-pos-", level:3},
  {word:"juxtapose",    meaning:"並置する",                 etymology:"juxta（隣に）+ pose（置く）",            root:"-pos-", level:3},
  {word:"repository",   meaning:"貯蔵所・リポジトリ",        etymology:"re（再び）+ pos（置く）+ itory",         root:"-pos-", level:2},

  // ── -press-（押す） ──────────────────────────
  {word:"press",        meaning:"押す・印刷機",              etymology:"press（押す）",                          root:"-press-", level:0},
  {word:"express",      meaning:"表現する・急行の",          etymology:"ex（外に）+ press（押す）→ 外に押し出す", root:"-press-", level:0},
  {word:"impress",      meaning:"感動させる・印象を与える",   etymology:"im（中に）+ press（押す）→ 心に押し込む", root:"-press-", level:0},
  {word:"suppress",     meaning:"抑圧する・鎮圧する",        etymology:"sub（下に）+ press（押す）",             root:"-press-", level:2},
  {word:"compress",     meaning:"圧縮する",                  etymology:"com（共に）+ press（押す）",             root:"-press-", level:1},
  {word:"depress",      meaning:"落ち込ませる・押し下げる",   etymology:"de（下に）+ press（押す）",              root:"-press-", level:1},
  {word:"oppress",      meaning:"抑圧する・苦しめる",         etymology:"op（上に）+ press（押す）",              root:"-press-", level:2},
  {word:"repress",      meaning:"抑圧する・抑制する",         etymology:"re（元に）+ press（押す）",              root:"-press-", level:2},
  {word:"impression",   meaning:"印象・感銘",               etymology:"im（中に）+ press（押す）+ ion",         root:"-press-", level:1},
  {word:"depression",   meaning:"うつ病・不況",              etymology:"de（下に）+ press（押す）+ ion",         root:"-press-", level:1},
  {word:"oppressive",   meaning:"抑圧的な・辛い",            etymology:"op（上に）+ press（押す）+ ive",         root:"-press-", level:2},

  // ── -prob-/-prov-（試す・証明する） ─────────
  {word:"prove",        meaning:"証明する",                  etymology:"prov（証明する）+ e",                    root:"-prob-", level:0},
  {word:"approve",      meaning:"承認する・賛成する",          etymology:"ap（〜に）+ prove（証明する）",           root:"-prob-", level:1},
  {word:"improve",      meaning:"改善する",                  etymology:"im（中に）+ prove（試す）",               root:"-prob-", level:0},
  {word:"probe",        meaning:"探査する・調査する",         etymology:"prob（試す）+ e",                        root:"-prob-", level:2},
  {word:"probable",     meaning:"ありそうな",               etymology:"prob（試す）+ able",                     root:"-prob-", level:1},
  {word:"disapprove",   meaning:"不承認にする・反対する",     etymology:"dis（否定）+ approve（承認する）",        root:"-prob-", level:2},
  {word:"disprove",     meaning:"反証する",                  etymology:"dis（否定）+ prove（証明する）",          root:"-prob-", level:2},
  {word:"reprove",      meaning:"叱る・非難する",             etymology:"re（再び）+ prove（試す）",               root:"-prob-", level:3},
  {word:"probation",    meaning:"仮釈放・試用期間",           etymology:"prob（試す）+ ation",                    root:"-prob-", level:2},
  {word:"reprobate",    meaning:"堕落した・悪人",             etymology:"re（再び）+ prob（試す）+ ate",          root:"-prob-", level:3},

  // ── -quer-/-quest-/-quir-（求める・尋ねる） ──────
  {word:"quest",        meaning:"探求・冒険",               etymology:"quest（求める）",                        root:"-quer-", level:1},
  {word:"question",     meaning:"質問・疑問",               etymology:"quest（求める）+ ion",                   root:"-quer-", level:0},
  {word:"request",      meaning:"要求する・依頼する",        etymology:"re（再び）+ quest（求める）",            root:"-quer-", level:0},
  {word:"require",      meaning:"必要とする・要求する",       etymology:"re（再び）+ quir（求める）+ e",          root:"-quer-", level:0},
  {word:"acquire",      meaning:"習得する・取得する",        etymology:"ac（〜へ）+ quir（求める）+ e",          root:"-quer-", level:1},
  {word:"inquire",      meaning:"尋ねる・調査する",          etymology:"in（中に）+ quir（求める）+ e",          root:"-quer-", level:2},
  {word:"query",        meaning:"質問・疑問点",              etymology:"quer（求める）+ y",                      root:"-quer-", level:2},
  {word:"inquest",      meaning:"審問・死因調査",            etymology:"in（中に）+ quest（求める）",            root:"-quer-", level:3},
  {word:"exquisite",    meaning:"精巧な・極上の",            etymology:"ex（外に）+ quis（求める）+ ite",        root:"-quer-", level:2},
  {word:"inquisition",  meaning:"異端審問・厳しい尋問",      etymology:"in（中に）+ quis（求める）+ ition",      root:"-quer-", level:3},
  {word:"conquer",      meaning:"征服する・克服する",        etymology:"con（完全に）+ quer（求める）",          root:"-quer-", level:1},

  // ── -rog-（尋ねる・求める） ──────────────────
  {word:"arrogant",     meaning:"傲慢な・横柄な",            etymology:"ar（〜に）+ rog（求める）+ ant → 自分に引き付ける", root:"-rog-", level:2},
  {word:"interrogate",  meaning:"尋問する・質問する",         etymology:"inter（間に）+ rog（尋ねる）+ ate",      root:"-rog-", level:2},
  {word:"surrogate",    meaning:"代理の・代替物",             etymology:"sur（下に）+ rog（尋ねる）+ ate",        root:"-rog-", level:3},
  {word:"prerogative",  meaning:"特権",                     etymology:"pre（前に）+ rog（求める）+ ative",      root:"-rog-", level:3},
  {word:"abrogate",     meaning:"廃止する・無効にする",       etymology:"ab（離れて）+ rog（求める）+ ate",       root:"-rog-", level:3},
  {word:"derogate",     meaning:"損なう・貶める",             etymology:"de（下に）+ rog（求める）+ ate",         root:"-rog-", level:3},

  // ── -sacr-/-sanct-（神聖な） ─────────────────
  {word:"sacred",       meaning:"神聖な・聖なる",             etymology:"sacr（神聖な）+ ed",                     root:"-sacr-", level:1},
  {word:"sacrifice",    meaning:"犠牲・生け贄",              etymology:"sacr（神聖な）+ fice（作る）",           root:"-sacr-", level:1},
  {word:"sanction",     meaning:"制裁・承認する",             etymology:"sanct（神聖な）+ ion → 神が認めること",  root:"-sacr-", level:2},
  {word:"sanctuary",    meaning:"聖域・保護区",               etymology:"sanct（神聖な）+ uary",                  root:"-sacr-", level:2},
  {word:"sacrilege",    meaning:"冒涜",                      etymology:"sacri（神聖な）+ lege（盗む）",           root:"-sacr-", level:3},
  {word:"consecrate",   meaning:"神聖にする・捧げる",         etymology:"con（完全に）+ sacr（神聖な）+ ate",     root:"-sacr-", level:3},
  {word:"desecrate",    meaning:"冒涜する",                  etymology:"de（否定）+ sacr（神聖な）+ ate",        root:"-sacr-", level:3},
  {word:"sacrament",    meaning:"秘跡・聖礼典",               etymology:"sacr（神聖な）+ ament",                  root:"-sacr-", level:3},

  // ── -scend-/-scens-（登る・降りる） ─────────
  {word:"ascend",       meaning:"登る・上昇する",             etymology:"a（〜へ）+ scend（登る）",               root:"-scend-", level:1},
  {word:"descend",      meaning:"降りる・下降する",           etymology:"de（下に）+ scend（登る）",              root:"-scend-", level:1},
  {word:"transcend",    meaning:"超越する",                  etymology:"trans（超えて）+ scend（登る）",         root:"-scend-", level:2},
  {word:"condescend",   meaning:"見下す・わざわざ〜する",      etymology:"con（共に）+ de（下に）+ scend（降りる）",root:"-scend-", level:2},
  {word:"ascent",       meaning:"上昇・登り坂",               etymology:"a（〜へ）+ scent（登る）",               root:"-scend-", level:2},
  {word:"descent",      meaning:"降下・家系",                 etymology:"de（下に）+ scent（登る）",              root:"-scend-", level:2},
  {word:"transcendent", meaning:"超越した",                  etymology:"trans（超えて）+ scend（登る）+ ent",    root:"-scend-", level:3},

  // ── -sec-/-sect-（切る） ─────────────────────
  {word:"section",      meaning:"部分・区域",                etymology:"sect（切る）+ ion",                      root:"-sect-", level:0},
  {word:"intersect",    meaning:"交差する",                  etymology:"inter（間に）+ sect（切る）",            root:"-sect-", level:1},
  {word:"dissect",      meaning:"解剖する・分析する",          etymology:"dis（離れて）+ sect（切る）",            root:"-sect-", level:2},
  {word:"sector",       meaning:"部門・扇形",                etymology:"sect（切る）+ or",                       root:"-sect-", level:1},
  {word:"bisect",       meaning:"二等分する",                etymology:"bi（二つ）+ sect（切る）",               root:"-sect-", level:2},
  {word:"insect",       meaning:"昆虫",                     etymology:"in（中に）+ sect（切る）→ 切り込みのある体",root:"-sect-", level:0},
  {word:"vivisect",     meaning:"生体解剖する",               etymology:"vivi（生きた）+ sect（切る）",           root:"-sect-", level:3},

  // ── -sequ-/-secut-（続く・追う） ─────────────
  {word:"sequence",     meaning:"順序・連続",                etymology:"sequ（続く）+ ence",                     root:"-sequ-", level:1},
  {word:"consequence",  meaning:"結果・重要性",               etymology:"con（共に）+ sequ（続く）+ ence",        root:"-sequ-", level:1},
  {word:"subsequent",   meaning:"その後の",                  etymology:"sub（後に）+ sequ（続く）+ ent",         root:"-sequ-", level:2},
  {word:"execute",      meaning:"実行する・処刑する",          etymology:"ex（外に）+ secut（続く）+ e",           root:"-sequ-", level:1},
  {word:"prosecute",    meaning:"起訴する・遂行する",          etymology:"pro（前に）+ secut（続く）+ e",          root:"-sequ-", level:2},
  {word:"consecutive",  meaning:"連続した",                  etymology:"con（共に）+ secut（続く）+ ive",        root:"-sequ-", level:2},
  {word:"sequel",       meaning:"続編・結果",                etymology:"sequ（続く）+ el",                       root:"-sequ-", level:2},
  {word:"non-sequitur", meaning:"論理の飛躍・的外れ",         etymology:"non（否定）+ sequ（続く）+ itur",        root:"-sequ-", level:3},

  // ── -sens-/-sent-（感じる） ──────────────────
  {word:"sense",        meaning:"感覚・意味",                etymology:"sens（感じる）+ e",                      root:"-sens-", level:0},
  {word:"sensation",    meaning:"感覚・感動",                etymology:"sens（感じる）+ ation",                  root:"-sens-", level:1},
  {word:"sentiment",    meaning:"感情・感傷",                etymology:"senti（感じる）+ ment",                  root:"-sens-", level:2},
  {word:"consent",      meaning:"同意する",                  etymology:"con（共に）+ sent（感じる）",            root:"-sens-", level:1},
  {word:"dissent",      meaning:"意見を異にする",             etymology:"dis（離れて）+ sent（感じる）",          root:"-sens-", level:2},
  {word:"resent",       meaning:"憤慨する",                  etymology:"re（再び）+ sent（感じる）→ 再び感じる",  root:"-sens-", level:2},
  {word:"sensitive",    meaning:"敏感な",                   etymology:"sens（感じる）+ itive",                  root:"-sens-", level:1},
  {word:"sensible",     meaning:"分別のある・賢明な",          etymology:"sens（感じる）+ ible",                   root:"-sens-", level:1},
  {word:"insensitive",  meaning:"無神経な",                  etymology:"in（否定）+ sensitive（敏感な）",        root:"-sens-", level:2},
  {word:"consensus",    meaning:"合意・総意",                etymology:"con（共に）+ sens（感じる）+ us",         root:"-sens-", level:2},

  // ── -reg-/-rect-（まっすぐ・統治） ─────────────
  {word:"regular",      meaning:"規則的な・通常の",          etymology:"reg（まっすぐ）+ ular",                  root:"-reg-", level:0},
  {word:"direct",       meaning:"直接の・指示する",           etymology:"di（完全に）+ rect（まっすぐ）",         root:"-reg-", level:0},
  {word:"correct",      meaning:"正確な・修正する",           etymology:"cor（完全に）+ rect（まっすぐ）",        root:"-reg-", level:0},
  {word:"regulate",     meaning:"規制する",                  etymology:"reg（統治）+ ulate",                     root:"-reg-", level:1},
  {word:"region",       meaning:"地域",                     etymology:"reg（統治）+ ion",                       root:"-reg-", level:0},
  {word:"regal",        meaning:"王の・堂々とした",           etymology:"reg（王）+ al",                          root:"-reg-", level:2},
  {word:"regiment",     meaning:"連隊・統制する",            etymology:"reg（統治）+ iment",                     root:"-reg-", level:2},
  {word:"erect",        meaning:"直立した・建てる",           etymology:"e（外に）+ rect（まっすぐ）",            root:"-reg-", level:2},
  {word:"resurrect",    meaning:"復活させる",                etymology:"re（再び）+ sur（下から）+ rect（まっすぐ）", root:"-reg-", level:2},
  {word:"incorrigible", meaning:"矯正不能な",               etymology:"in（否定）+ cor + rig（まっすぐ）+ ible", root:"-reg-", level:3},
  {word:"rectify",      meaning:"修正する・是正する",         etymology:"rect（まっすぐ）+ ify",                  root:"-reg-", level:2},

  // ── -rupt-（壊す・破裂する） ─────────────────
  {word:"rupture",      meaning:"破裂・決裂",               etymology:"rupt（壊す）+ ure",                      root:"-rupt-", level:2},
  {word:"disrupt",      meaning:"混乱させる",               etymology:"dis（離れて）+ rupt（壊す）",            root:"-rupt-", level:2},
  {word:"interrupt",    meaning:"中断する",                 etymology:"inter（間に）+ rupt（壊す）",            root:"-rupt-", level:1},
  {word:"corrupt",      meaning:"腐敗した・不正な",          etymology:"cor（完全に）+ rupt（壊す）",            root:"-rupt-", level:1},
  {word:"erupt",        meaning:"噴火する",                 etymology:"e（外に）+ rupt（壊す）",                root:"-rupt-", level:1},
  {word:"abrupt",       meaning:"突然の・ぶっきらぼうな",    etymology:"ab（離れて）+ rupt（壊す）",             root:"-rupt-", level:2},
  {word:"bankrupt",     meaning:"破産した",                 etymology:"bank（銀行）+ rupt（壊す）",             root:"-rupt-", level:1},
  {word:"irruption",    meaning:"侵入・急増",               etymology:"ir（中に）+ rupt（壊す）+ ion",          root:"-rupt-", level:3},
  {word:"corruption",   meaning:"腐敗・汚職",               etymology:"cor（完全に）+ rupt（壊す）+ ion",       root:"-rupt-", level:2},

  // ── -sign-（印・標識） ───────────────────────
  {word:"sign",         meaning:"印・標識・署名する",        etymology:"sign（印）",                             root:"-sign-", level:0},
  {word:"signal",       meaning:"信号・合図",               etymology:"sign（印）+ al",                         root:"-sign-", level:0},
  {word:"significant",  meaning:"重要な・有意義な",          etymology:"sign（印）+ ificant（作る）",            root:"-sign-", level:1},
  {word:"designate",    meaning:"指定する・任命する",         etymology:"de（完全に）+ sign（印）+ ate",           root:"-sign-", level:2},
  {word:"assign",       meaning:"割り当てる・任命する",       etymology:"as（〜へ）+ sign（印）",                 root:"-sign-", level:1},
  {word:"resign",       meaning:"辞任する",                 etymology:"re（元に）+ sign（印）→ 署名を取り戻す",  root:"-sign-", level:2},
  {word:"insignificant",meaning:"些細な・取るに足りない",     etymology:"in（否定）+ significant（重要な）",      root:"-sign-", level:2},
  {word:"signature",    meaning:"署名・特徴",               etymology:"sign（印）+ ature",                      root:"-sign-", level:1},
  {word:"signify",      meaning:"意味する・示す",            etymology:"sign（印）+ ify",                        root:"-sign-", level:2},
  {word:"consign",      meaning:"委託する・引き渡す",         etymology:"con（共に）+ sign（印）",                root:"-sign-", level:3},

  // ── -simil-/-simul-（同じ・似た） ───────────
  {word:"similar",      meaning:"類似した",                 etymology:"simil（同じ）+ ar",                      root:"-simil-", level:0},
  {word:"simulate",     meaning:"模擬する・シミュレートする", etymology:"simul（同じ）+ ate",                     root:"-simil-", level:1},
  {word:"assimilate",   meaning:"同化する・吸収する",         etymology:"as（〜へ）+ simil（同じ）+ ate",         root:"-simil-", level:2},
  {word:"simultaneous", meaning:"同時の",                   etymology:"simul（同じ）+ taneous（時間）",          root:"-simil-", level:2},
  {word:"facsimile",    meaning:"複写・ファクシミリ",          etymology:"fac（作る）+ simile（同じ）",            root:"-simil-", level:2},
  {word:"dissimilar",   meaning:"異なる・不似合いの",         etymology:"dis（否定）+ simil（同じ）+ ar",         root:"-simil-", level:2},
  {word:"semblance",    meaning:"外見・見かけ",              etymology:"sembl（同じ）+ ance",                    root:"-simil-", level:3},
  {word:"resemble",     meaning:"〜に似ている",              etymology:"re（強意）+ sembl（同じ）+ e",           root:"-simil-", level:1},

  // ── -sol-（太陽・単独） ──────────────────────
  {word:"solar",        meaning:"太陽の",                   etymology:"sol（太陽）+ ar",                        root:"-sol-", level:1},
  {word:"solo",         meaning:"独演・一人の",              etymology:"sol（単独）+ o",                         root:"-sol-", level:0},
  {word:"sole",         meaning:"唯一の・単独の",            etymology:"sol（単独）+ e",                         root:"-sol-", level:1},
  {word:"solitary",     meaning:"孤独な・一人の",            etymology:"sol（単独）+ itary",                     root:"-sol-", level:1},
  {word:"solitude",     meaning:"孤独・独居",               etymology:"sol（単独）+ itude",                     root:"-sol-", level:2},
  {word:"desolate",     meaning:"荒れ果てた・寂しい",         etymology:"de（完全に）+ sol（単独）+ ate",         root:"-sol-", level:2},
  {word:"console",      meaning:"慰める・操作台",             etymology:"con（共に）+ sol（単独）→ 孤独を共にする",root:"-sol-", level:2},
  {word:"consolidate",  meaning:"統合する・強化する",         etymology:"con（共に）+ solid（固める）+ ate",      root:"-sol-", level:2},
  {word:"parasite",     meaning:"寄生虫・居候",              etymology:"para（横に）+ site（食べる）",           root:"-sol-", level:2},
  {word:"solstice",     meaning:"夏至・冬至",                etymology:"sol（太陽）+ stice（止まる）",           root:"-sol-", level:3},

  // ── -string-/-strict-（締める・縛る） ───────
  {word:"strict",       meaning:"厳格な・厳しい",            etymology:"strict（締める）",                       root:"-strict-", level:1},
  {word:"restrict",     meaning:"制限する",                  etymology:"re（再び）+ strict（締める）",           root:"-strict-", level:1},
  {word:"constrict",    meaning:"収縮させる・締めつける",      etymology:"con（共に）+ strict（締める）",          root:"-strict-", level:3},
  {word:"district",     meaning:"地区・管区",               etymology:"di（離れて）+ strict（締める）→ 区切られた地区", root:"-strict-", level:1},
  {word:"constraint",   meaning:"制約・束縛",               etymology:"con（共に）+ straint（締める）",          root:"-strict-", level:2},
  {word:"stringent",    meaning:"厳しい・厳格な",             etymology:"string（締める）+ ent",                  root:"-strict-", level:3},
  {word:"astringent",   meaning:"収れん性の・厳しい",         etymology:"a（〜へ）+ string（締める）+ ent",       root:"-strict-", level:3},

  // ── -stru-/-struct-（築く・組み立てる） ────────
  {word:"structure",    meaning:"構造・建造物",               etymology:"struct（築く）+ ure",                    root:"-struct-", level:0},
  {word:"construct",    meaning:"建設する・構築する",          etymology:"con（共に）+ struct（築く）",            root:"-struct-", level:1},
  {word:"destruct",     meaning:"破壊する",                  etymology:"de（離れて）+ struct（築く）",           root:"-struct-", level:2},
  {word:"instruct",     meaning:"指導する・命令する",          etymology:"in（中に）+ struct（築く）",             root:"-struct-", level:1},
  {word:"obstruct",     meaning:"妨害する・塞ぐ",             etymology:"ob（前に）+ struct（築く）→ 道を塞ぐ",   root:"-struct-", level:2},
  {word:"reconstruct",  meaning:"再建する・再現する",          etymology:"re（再び）+ construct（建設する）",      root:"-struct-", level:1},
  {word:"infrastructure",meaning:"インフラ・基盤",            etymology:"infra（下に）+ struct（築く）+ ure",     root:"-struct-", level:2},
  {word:"instrument",   meaning:"楽器・道具・手段",           etymology:"instru（作る）+ ment",                   root:"-struct-", level:0},
  {word:"destruction",  meaning:"破壊・崩壊",                etymology:"de（離れて）+ struct（築く）+ ion",      root:"-struct-", level:1},
  {word:"indestructible",meaning:"破壊不可能な",              etymology:"in（否定）+ destruct（破壊する）+ ible", root:"-struct-", level:2},
  {word:"substructure", meaning:"基盤・下部構造",             etymology:"sub（下に）+ struct（築く）+ ure",       root:"-struct-", level:3},
  {word:"superstructure",meaning:"上部構造・上部建築",         etymology:"super（上に）+ struct（築く）+ ure",     root:"-struct-", level:3},

  ];

  if(!window.WORD_DATA_RAW) window.WORD_DATA_RAW=[];
  window.WORD_DATA_RAW=window.WORD_DATA_RAW.concat(d);
})();
