/**
 * data-mixed-2.js — GRE/SAT頻出語（高度語彙・難関試験語）
 * 形式: { word, meaning, etymology, category, level }
 * level: 0=beginner 1=intermediate 2=advanced 3=master
 */
(function(){
  var d = [
  // ── GRE/SAT 頻出語（A〜C） ────────────────────
  {word:"aberrant",      meaning:"異常な・逸脱した",      etymology:"ab（離れて）+ errant（さまよう）",         category:"GRE", level:3},
  {word:"abridge",       meaning:"要約する・短縮する",    etymology:"ab（離れて）+ bridge（橋）→短くする",      category:"GRE", level:2},
  {word:"acrimony",      meaning:"辛辣さ・毒舌",          etymology:"acri（鋭い）+ mony（性質）",               category:"GRE", level:3},
  {word:"admonish",      meaning:"戒める・注意する",      etymology:"ad（〜に）+ monish（警告する）",           category:"GRE", level:3},
  {word:"adulation",     meaning:"おべっか・過度の賛辞",  etymology:"adul（おべっかを使う）+ ation（行為）",    category:"GRE", level:3},
  {word:"alacrity",      meaning:"機敏さ・すばやい行動", etymology:"alacr（活発）+ ity（性質）",               category:"GRE", level:3},
  {word:"alleviate",     meaning:"和らげる・緩和する",    etymology:"al（〜に）+ levia（軽くする）+ ate",       category:"GRE", level:2},
  {word:"ambivalent",    meaning:"相反する感情を持つ",    etymology:"ambi（両方）+ valent（価値）",             category:"GRE", level:2},
  {word:"ameliorate",    meaning:"改善する・良くする",    etymology:"a（〜に）+ meliorate（良くする）",         category:"GRE", level:3},
  {word:"anachronism",   meaning:"時代錯誤",              etymology:"ana（逆に）+ chron（時間）+ ism",          category:"GRE", level:3},
  {word:"anathema",      meaning:"忌み嫌われるもの・呪い",etymology:"ana（上に）+ thema（置く）",              category:"GRE", level:3},
  {word:"antipathy",     meaning:"反感・嫌悪",            etymology:"anti（反対）+ pathy（感じる）",            category:"GRE", level:2},
  {word:"apathy",        meaning:"無関心・無気力",        etymology:"a（否定）+ pathy（感じる）",              category:"GRE", level:2},
  {word:"appease",       meaning:"なだめる・懐柔する",    etymology:"ap（〜に）+ pease（平和）",                category:"GRE", level:3},
  {word:"arbitrary",     meaning:"独断的な・恣意的な",    etymology:"arbitr（判断する）+ ary（〜の）",          category:"GRE", level:2},
  {word:"arcane",        meaning:"神秘的な・難解な",      etymology:"arc（秘密）+ ane（〜の）",                 category:"GRE", level:3},
  {word:"arduous",       meaning:"骨の折れる・困難な",    etymology:"ardu（高い・急な）+ ous（性質）",          category:"GRE", level:2},
  {word:"articulate",    meaning:"明確に述べる・明瞭な",  etymology:"artic（関節）+ ulate（〜にする）",         category:"GRE", level:2},
  {word:"ascetic",       meaning:"禁欲的な・苦行者",      etymology:"asce（練習する）+ tic（〜の）",            category:"GRE", level:3},
  {word:"assuage",       meaning:"和らげる・慰める",      etymology:"as（〜に）+ suage（柔らかくする）",        category:"GRE", level:3},
  {word:"astute",        meaning:"抜け目ない・鋭い",      etymology:"astut（ずる賢い）+ e",                    category:"GRE", level:2},
  {word:"atrophy",       meaning:"萎縮・衰退する",        etymology:"a（否定）+ trophy（栄養）",               category:"GRE", level:2},
  {word:"audacious",     meaning:"大胆な・厚かましい",    etymology:"audac（大胆）+ ious（性質）",              category:"GRE", level:2},
  {word:"austere",       meaning:"質素な・厳格な",        etymology:"auster（厳しい）+ e",                     category:"GRE", level:2},
  {word:"avarice",       meaning:"強欲・貪欲",            etymology:"avar（貪欲）+ ice（性質）",                category:"GRE", level:3},
  {word:"banal",         meaning:"陳腐な・ありきたりな",  etymology:"banal（使用可能な・凡庸）",                category:"GRE", level:2},
  {word:"belie",         meaning:"〜と矛盾する・裏切る",  etymology:"be（〜を）+ lie（嘘をつく）",              category:"GRE", level:3},
  {word:"belligerent",   meaning:"好戦的な・戦闘員",      etymology:"belli（戦争）+ gerent（行う）",            category:"GRE", level:2},
  {word:"benevolent",    meaning:"慈悲深い・善意ある",    etymology:"bene（良い）+ volent（望む）",             category:"GRE", level:2},
  {word:"bombastic",     meaning:"大げさな・誇大な",      etymology:"bomb（膨らむ）+ astic（〜の）",            category:"GRE", level:3},
  {word:"brusque",       meaning:"ぶっきらぼうな",        etymology:"brusque（荒々しい）",                     category:"GRE", level:2},
  {word:"cacophony",     meaning:"不協和音・騒音",        etymology:"caco（悪い）+ phony（音）",                category:"GRE", level:3},
  {word:"callous",       meaning:"無情な・無感覚な",      etymology:"callous（かさぶた）→感覚のない",           category:"GRE", level:2},
  {word:"candor",        meaning:"率直さ・正直",          etymology:"cand（白い・輝く）+ or（性質）",           category:"GRE", level:2},
  {word:"capitulate",    meaning:"降伏する・屈服する",    etymology:"capit（頭）+ ulate（〜する）",             category:"GRE", level:3},
  {word:"capricious",    meaning:"気まぐれな",            etymology:"capra（ヤギ）+ icious（性質）",            category:"GRE", level:2},
  {word:"castigation",   meaning:"厳しい批判・懲罰",      etymology:"castig（罰する）+ ation（行為）",          category:"GRE", level:3},
  {word:"caustic",       meaning:"腐食性の・辛辣な",      etymology:"caust（焼く）+ ic（〜の）",                category:"GRE", level:2},
  {word:"chicanery",     meaning:"詐欺・ごまかし",        etymology:"chicane（ごまかす）+ ry（行為）",          category:"GRE", level:3},
  {word:"circumspect",   meaning:"慎重な・用心深い",      etymology:"circum（周囲に）+ spect（見る）",          category:"GRE", level:2},
  {word:"clandestine",   meaning:"秘密の・内密な",        etymology:"clande（隠れた）+ stine（〜の）",          category:"GRE", level:2},
  {word:"coalesce",      meaning:"合体する・まとまる",    etymology:"co（共に）+ alesce（育つ）",               category:"GRE", level:3},
  {word:"cogent",        meaning:"説得力のある",          etymology:"co（共に）+ gent（動かす）",               category:"GRE", level:3},
  {word:"compunction",   meaning:"良心の呵責",            etymology:"com（完全に）+ punction（刺す）",          category:"GRE", level:3},
  {word:"condescending", meaning:"見下した・恩着せがましい",etymology:"con（〜と）+ descend（降りる）+ ing",   category:"GRE", level:2},
  {word:"convoluted",    meaning:"複雑な・込み入った",    etymology:"con（共に）+ voluted（巻く）",             category:"GRE", level:2},
  {word:"corroborate",   meaning:"裏付ける・確証する",    etymology:"cor（共に）+ roborate（強くする）",        category:"GRE", level:3},
  {word:"craven",        meaning:"臆病な",                etymology:"craven（無力）",                          category:"GRE", level:3},
  {word:"culpable",      meaning:"責任がある・有罪の",    etymology:"culp（罪）+ able（できる）",               category:"GRE", level:2},
  {word:"cursory",       meaning:"おざなりな・粗略な",    etymology:"curs（走る）+ ory（〜の）",                category:"GRE", level:2},

  // ── GRE/SAT 頻出語（D〜Z） ────────────────────
  {word:"dearth",        meaning:"不足・欠乏",            etymology:"dear（高価）+ th（状態）→乏しい",         category:"GRE", level:2},
  {word:"debilitate",    meaning:"弱める・衰弱させる",    etymology:"debil（弱い）+ itate（〜にする）",         category:"GRE", level:3},
  {word:"deference",     meaning:"敬意・従うこと",        etymology:"de（下に）+ ference（運ぶ）",              category:"GRE", level:2},
  {word:"delineate",     meaning:"描写する・輪郭を描く",  etymology:"de（完全に）+ line（線）+ ate（〜する）",  category:"GRE", level:3},
  {word:"demure",        meaning:"控えめな・おとなしい",  etymology:"de（〜に）+ mure（壁）→静かにしている",   category:"GRE", level:3},
  {word:"denigrate",     meaning:"けなす・中傷する",      etymology:"de（下に）+ nigrate（黒くする）",          category:"GRE", level:3},
  {word:"deride",        meaning:"嘲笑する・ばかにする",  etymology:"de（下に）+ ride（笑う）",                 category:"GRE", level:2},
  {word:"desultory",     meaning:"とりとめない・散漫な",  etymology:"desult（跳ぶ）+ ory（〜の）",             category:"GRE", level:3},
  {word:"didactic",      meaning:"教訓的な・説教がましい",etymology:"didact（教える）+ ic（〜の）",            category:"GRE", level:3},
  {word:"diffident",     meaning:"自信のない・内気な",    etymology:"dif（離れて）+ fident（信じる）",          category:"GRE", level:2},
  {word:"dilettante",    meaning:"素人好事家・芸術愛好者",etymology:"diletta（喜ぶ）+ nte（〜する人）",         category:"GRE", level:3},
  {word:"discerning",    meaning:"識別力のある・洞察力のある",etymology:"dis（離れて）+ cern（ふるいにかける）",category:"GRE", level:2},
  {word:"discordant",    meaning:"不一致の・不協和な",    etymology:"dis（否定）+ cord（心）+ ant（〜の）",     category:"GRE", level:2},
  {word:"disinterested", meaning:"公平な・私利私欲のない",etymology:"dis（否定）+ interested（関心ある）",     category:"GRE", level:2},
  {word:"disparate",     meaning:"異質な・まったく違う",  etymology:"dis（離れて）+ parate（準備）",            category:"GRE", level:2},
  {word:"dispassionate", meaning:"冷静な・感情のない",    etymology:"dis（否定）+ passionate（熱情的）",       category:"GRE", level:3},
  {word:"divisive",      meaning:"分裂を招く・分裂的な",  etymology:"divis（分ける）+ ive（傾向）",             category:"GRE", level:2},
  {word:"dogmatic",      meaning:"独断的な",              etymology:"dogm（教義）+ atic（〜の）",               category:"GRE", level:2},
  {word:"duplicity",     meaning:"二枚舌・偽り",          etymology:"duplic（二重）+ ity（性質）",              category:"GRE", level:3},
  {word:"ebullient",     meaning:"溌剌とした・活気あふれる",etymology:"e（外に）+ bullent（沸く）",            category:"GRE", level:3},
  {word:"egregious",     meaning:"目に余る・ひどい",      etymology:"e（外に）+ gre（群れ）+ ious（性質）",    category:"GRE", level:3},
  {word:"elusive",       meaning:"つかみどころのない",    etymology:"e（外に）+ lus（遊ぶ）+ ive（傾向）",     category:"GRE", level:2},
  {word:"emulate",       meaning:"模倣する・張り合う",    etymology:"emul（競争する）+ ate（〜する）",          category:"GRE", level:2},
  {word:"enervate",      meaning:"弱める・活力を奪う",    etymology:"e（外に）+ nerv（神経）+ ate（〜する）",   category:"GRE", level:3},
  {word:"ephemeral",     meaning:"はかない・短命の",      etymology:"epi（上に）+ hemeral（日）→一日限りの",   category:"GRE", level:2},
  {word:"equivocate",    meaning:"言葉をぼかす・曖昧に言う",etymology:"equi（等しい）+ vocate（呼ぶ）",        category:"GRE", level:3},
  {word:"esoteric",      meaning:"秘教的な・難解な",      etymology:"eso（内側）+ teric（〜の）",               category:"GRE", level:3},
  {word:"eulogy",        meaning:"弔辞・賛辞",            etymology:"eu（良い）+ logy（言う）",                 category:"GRE", level:2},
  {word:"euphemism",     meaning:"婉曲表現",              etymology:"eu（良い）+ phemism（言う）",              category:"GRE", level:2},
  {word:"exacerbate",    meaning:"悪化させる",            etymology:"ex（外に）+ acerbate（苦くする）",         category:"GRE", level:2},
  {word:"excoriate",     meaning:"激しく非難する",        etymology:"ex（外に）+ coriate（皮をはぐ）",          category:"GRE", level:3},
  {word:"exculpate",     meaning:"無罪にする",            etymology:"ex（外に）+ culp（罪）+ ate（〜する）",    category:"GRE", level:3},
  {word:"exemplary",     meaning:"模範的な",              etymology:"exempl（手本）+ ary（〜の）",              category:"GRE", level:2},
  {word:"exonerate",     meaning:"無罪にする・免除する",  etymology:"ex（外に）+ oner（重荷）+ ate（〜する）",  category:"GRE", level:2},
  {word:"expedient",     meaning:"便宜的な・好都合な",    etymology:"ex（外に）+ pedient（足）",                category:"GRE", level:2},
  {word:"fatuous",       meaning:"愚かな・くだらない",    etymology:"fatu（愚か）+ ous（性質）",                category:"GRE", level:3},
  {word:"fervent",       meaning:"熱烈な・情熱的な",      etymology:"ferv（熱く燃える）+ ent（〜している）",    category:"GRE", level:2},
  {word:"flagrant",      meaning:"目に余る・明白な",      etymology:"flagr（燃える）+ ant（〜している）",       category:"GRE", level:2},
  {word:"flippant",      meaning:"軽薄な・不真面目な",    etymology:"flip（ひっくり返す）+ pant（〜の）",       category:"GRE", level:2},
  {word:"garrulous",     meaning:"おしゃべりな",          etymology:"garr（おしゃべり）+ ulous（性質）",        category:"GRE", level:3},
  {word:"gregarious",    meaning:"社交的な・群れをなす",  etymology:"greg（群れ）+ arious（性質）",             category:"GRE", level:2},
  {word:"guile",         meaning:"狡猾・策略",            etymology:"guile（策略）",                           category:"GRE", level:3},
  {word:"hackneyed",     meaning:"陳腐な・使い古した",    etymology:"hackney（乗用馬）→使い古された",          category:"GRE", level:3},
  {word:"harangue",      meaning:"激しく非難する・熱弁",  etymology:"harang（広場の演説）+ ue",                category:"GRE", level:3},
  {word:"hegemony",      meaning:"覇権・支配権",          etymology:"hegemon（指導者）+ y",                    category:"GRE", level:3},
  {word:"heresy",        meaning:"異端・異説",            etymology:"heres（選ぶ）+ y",                        category:"GRE", level:2},
  {word:"homogenize",    meaning:"均質化する",            etymology:"homo（同じ）+ gen（生む）+ ize（〜する）", category:"GRE", level:2},
  {word:"iconoclast",    meaning:"偶像破壊者・旧習打破者",etymology:"ico（像）+ no（否定）+ clast（壊す）",    category:"GRE", level:3},
  {word:"impetuous",     meaning:"衝動的な・激しい",      etymology:"impetu（勢い）+ ous（性質）",              category:"GRE", level:2},
  {word:"implacable",    meaning:"なだめられない・執念深い",etymology:"im（否定）+ placare（和解する）+ ble",  category:"GRE", level:3},
  {word:"inadvertent",   meaning:"不注意による・意図しない",etymology:"in（否定）+ advertent（注意する）",    category:"GRE", level:2},
  {word:"inchoate",      meaning:"まだ形になっていない",  etymology:"in（中に）+ choate（鋤を取り付ける）",    category:"GRE", level:3},
  {word:"inert",         meaning:"不活性な・動きのない",  etymology:"in（否定）+ ert（技能）",                 category:"GRE", level:2},
  {word:"innocuous",     meaning:"無害な・当たり障りのない",etymology:"in（否定）+ noc（傷つける）+ uous",    category:"GRE", level:2},
  {word:"insipid",       meaning:"味気ない・つまらない",  etymology:"in（否定）+ sipid（味）",                 category:"GRE", level:2},
  {word:"intransigent",  meaning:"妥協しない・頑固な",    etymology:"in（否定）+ transigent（取引する）",      category:"GRE", level:3},
  {word:"inundate",      meaning:"氾濫させる・押し寄せる",etymology:"in（中に）+ und（波）+ ate（〜する）",    category:"GRE", level:2},
  {word:"inveterate",    meaning:"根深い・慢性的な",      etymology:"in（中に）+ veter（古い）+ ate（〜の）",  category:"GRE", level:3},
  {word:"laconic",       meaning:"簡潔な・無口な",        etymology:"lakon（スパルタ人）+ ic（〜の）",         category:"GRE", level:3},
  {word:"lassitude",     meaning:"疲労感・倦怠",          etymology:"lass（疲れた）+ itude（状態）",           category:"GRE", level:3},
  {word:"loquacious",    meaning:"おしゃべりな・多弁な",  etymology:"loqu（話す）+ acious（性質）",             category:"GRE", level:3},
  {word:"lugubrious",    meaning:"悲しそうな・陰鬱な",    etymology:"lugubr（悲しむ）+ ious（性質）",          category:"GRE", level:3},
  {word:"maladroit",     meaning:"不器用な",              etymology:"mal（悪い）+ adroit（器用な）",            category:"GRE", level:3},
  {word:"malevolent",    meaning:"悪意のある",            etymology:"male（悪い）+ volent（望む）",             category:"GRE", level:3},
  {word:"mendacious",    meaning:"嘘をつく",              etymology:"mendac（嘘）+ ious（性質）",               category:"GRE", level:3},
  {word:"mercurial",     meaning:"気まぐれな・活発な",    etymology:"mercur（水銀）+ ial（〜の）",              category:"GRE", level:3},
  {word:"metamorphosis", meaning:"変態・変容",            etymology:"meta（変化）+ morph（形）+ osis（状態）",  category:"GRE", level:2},
  {word:"meticulous",    meaning:"細心の注意を払う",      etymology:"meti（恐れ）+ culous（性質）",             category:"GRE", level:2},
  {word:"myriad",        meaning:"無数の・様々な",        etymology:"myria（一万）+ d（数）",                   category:"GRE", level:2},
  {word:"nefarious",     meaning:"極悪な",                etymology:"nefar（悪）+ ious（性質）",                category:"GRE", level:3},
  {word:"nonchalant",    meaning:"無関心な・冷淡な",      etymology:"non（否定）+ chalant（熱心）",             category:"GRE", level:2},
  {word:"obfuscate",     meaning:"難解にする・混乱させる",etymology:"ob（完全に）+ fusc（暗くする）+ ate",     category:"GRE", level:3},
  {word:"obsequious",    meaning:"こびへつらう",          etymology:"ob（向かって）+ sequious（従う）",         category:"GRE", level:3},
  {word:"officious",     meaning:"お節介な・差し出口する",etymology:"offici（奉仕する）+ ious（性質）",         category:"GRE", level:3},
  {word:"onerous",       meaning:"骨の折れる・負担な",    etymology:"oner（重荷）+ ous（性質）",                category:"GRE", level:2},
  {word:"opprobrium",    meaning:"不名誉・非難",          etymology:"ob（向かって）+ probrium（恥）",           category:"GRE", level:3},
  {word:"ostentation",   meaning:"見せびらかし・虚栄心",  etymology:"osten（見せる）+ tation（行為）",          category:"GRE", level:3},
  {word:"pedantic",      meaning:"学者ぶった・衒学的な",  etymology:"pedant（学者ぶる）+ ic（〜の）",           category:"GRE", level:3},
  {word:"penchant",      meaning:"強い好み・傾向",        etymology:"pench（傾く）+ ant（〜している）",         category:"GRE", level:2},
  {word:"perfidious",    meaning:"裏切りの・不実な",      etymology:"per（完全に）+ fidi（信頼）+ ous（性質）", category:"GRE", level:3},
  {word:"peripatetic",   meaning:"遍歴する・旅する",      etymology:"peri（周囲に）+ patetic（歩く）",          category:"GRE", level:3},
  {word:"perspicacious", meaning:"洞察力のある・明敏な",  etymology:"per（完全に）+ spic（見る）+ acious（性質）",category:"GRE", level:3},
  {word:"petulant",      meaning:"怒りっぽい・気むずかしい",etymology:"petu（求める）+ lant（〜している）",    category:"GRE", level:3},
  {word:"placate",       meaning:"なだめる",              etymology:"plac（和らげる）+ ate（〜する）",          category:"GRE", level:2},
  {word:"plethora",      meaning:"過多・過剰",            etymology:"plethor（充満する）+ a",                  category:"GRE", level:2},
  {word:"polemical",     meaning:"論争的な・批判的な",    etymology:"polemi（戦争）+ cal（〜の）",              category:"GRE", level:3},
  {word:"pragmatic",     meaning:"実用主義的な",          etymology:"pragmat（行動）+ ic（〜の）",              category:"GRE", level:2},
  {word:"precarious",    meaning:"不安定な・危険な",      etymology:"prec（祈り）+ arious（性質）→不確かな",   category:"GRE", level:2},
  {word:"precipitous",   meaning:"急峻な・急な",          etymology:"precipit（頭から）+ ous（性質）",          category:"GRE", level:3},
  {word:"pretentious",   meaning:"気取った・見栄を張った",etymology:"preten（申し立てる）+ tious（〜の）",      category:"GRE", level:2},
  {word:"probity",       meaning:"誠実さ・廉潔",          etymology:"prob（良い）+ ity（性質）",                category:"GRE", level:3},
  {word:"prodigal",      meaning:"浪費する・放蕩な",      etymology:"prodi（前に）+ gal（与える）",             category:"GRE", level:2},
  {word:"propitious",    meaning:"縁起の良い・好都合な",  etymology:"propi（有利な）+ tious（性質）",           category:"GRE", level:3},
  {word:"querulous",     meaning:"不平がましい",          etymology:"queru（不満を言う）+ lous（性質）",        category:"GRE", level:3},
  {word:"recalcitrant",  meaning:"反抗的な・扱いにくい",  etymology:"re（後ろに）+ calcitrant（蹴る）",         category:"GRE", level:3},
  {word:"recondite",     meaning:"難解な・あまり知られない",etymology:"re（完全に）+ condite（隠す）",          category:"GRE", level:3},
  {word:"reticent",      meaning:"口数の少ない・無口な",  etymology:"re（再び）+ ticent（黙る）",               category:"GRE", level:2},
  {word:"sagacious",     meaning:"賢明な・洞察力のある",  etymology:"sag（賢い）+ acious（性質）",              category:"GRE", level:3},
  {word:"sanguine",      meaning:"楽観的な・血色の良い",  etymology:"sangu（血）+ ine（性質）",                 category:"GRE", level:2},
  {word:"sardonic",      meaning:"冷笑的な・皮肉な",      etymology:"sard（硬直させる）+ onic（〜の）",         category:"GRE", level:3},
  {word:"solipsism",     meaning:"唯我論",                etymology:"solus（一人）+ ipse（自分）+ ism（主義）", category:"GRE", level:3},
  {word:"spurious",      meaning:"偽の・いかがわしい",    etymology:"spur（出生不明）+ ious（性質）",           category:"GRE", level:3},
  {word:"taciturn",      meaning:"無口な・寡黙な",        etymology:"tacit（黙っている）+ urn（〜の性質）",     category:"GRE", level:2},
  {word:"tendentious",   meaning:"偏った・一方的な",      etymology:"tenden（傾く）+ tious（性質）",            category:"GRE", level:3},
  {word:"timorous",      meaning:"臆病な・おどおどした",  etymology:"tim（恐れる）+ orous（性質）",             category:"GRE", level:3},
  {word:"torpor",        meaning:"無気力・冬眠状態",      etymology:"torp（麻痺する）+ or（状態）",             category:"GRE", level:3},
  {word:"turbulent",     meaning:"激動の・騒乱の",        etymology:"turb（乱れる）+ ulent（〜の性質）",        category:"GRE", level:2},
  {word:"vacillate",     meaning:"揺れ動く・優柔不断な",  etymology:"vacill（揺れる）+ ate（〜する）",          category:"GRE", level:3},
  {word:"venerate",      meaning:"崇敬する",              etymology:"vener（崇拝）+ ate（〜する）",             category:"GRE", level:2},
  {word:"verbose",       meaning:"冗長な・くどい",        etymology:"verb（言葉）+ ose（〜に満ちた）",          category:"GRE", level:2},
  {word:"vicarious",     meaning:"代替的な・間接的な",    etymology:"vicar（代理）+ ious（性質）",              category:"GRE", level:2},
  {word:"vilify",        meaning:"中傷する・悪口を言う",  etymology:"vil（卑しい）+ ify（〜にする）",           category:"GRE", level:3},
  {word:"volatile",      meaning:"揮発性の・不安定な",    etymology:"volat（飛ぶ）+ ile（できる）",             category:"GRE", level:2},
  {word:"zealous",       meaning:"熱心な・熱狂的な",      etymology:"zeal（熱心）+ ous（性質）",                category:"GRE", level:2},
  ];

  if(!window.WORD_DATA_RAW) window.WORD_DATA_RAW=[];
  window.WORD_DATA_RAW=window.WORD_DATA_RAW.concat(d);
})();
