/**
 * data-mixed-2.js — TOEFL/IELTS/GRE/SAT頻出語・専門語（約360語）
 * 学術・ビジネス・医学・法律・科学分野の重要語彙
 */
(function(){
  var d = [

  // ── GRE頻出高難易度語 ─────────────────────────
  {word:"abstruse",     meaning:"難解な・わかりにくい",         etymology:"abs（離れて）+ trus（押す）+ e",          root:"-tract-", level:3},
  {word:"acrimony",     meaning:"辛辣さ・険悪さ",              etymology:"acri（鋭い）+ mony",                     suffix:"-ment", level:3},
  {word:"adumbrate",    meaning:"かすかに示す・予兆する",        etymology:"ad（〜へ）+ umbra（影）+ ate",            suffix:"-ate", level:3},
  {word:"alacrity",     meaning:"機敏さ・快活さ",              etymology:"alacer（機敏な）+ ity",                   suffix:"-ity", level:3},
  {word:"amalgam",      meaning:"混合物・アマルガム",           etymology:"amalga（合わせる）+ m",                   suffix:"-age", level:3},
  {word:"ambivalence",  meaning:"両面価値・相反する気持ち",      etymology:"ambi（両方）+ valence（価値）",           suffix:"-ence", level:2},
  {word:"ameliorate",   meaning:"改善する",                    etymology:"a（〜へ）+ melior（より良い）+ ate",      suffix:"-ate", level:3},
  {word:"anachronism",  meaning:"時代錯誤",                    etymology:"ana（後ろに）+ chron（時間）+ ism",        prefix:"chrono-", level:3},
  {word:"anathema",     meaning:"呪い・忌み嫌うもの",           etymology:"ana（上に）+ thema（置く）",              suffix:"-age", level:3},
  {word:"anomalous",    meaning:"異常な・不規則な",             etymology:"an（否定）+ omal（規則）+ ous",          root:"-nom-", level:3},
  {word:"antipodal",    meaning:"正反対の",                   etymology:"anti（反対）+ pod（足）+ al",            prefix:"anti-", level:3},
  {word:"apocryphal",   meaning:"疑わしい・外典の",             etymology:"apo（離れて）+ crypt（隠す）+ al",        prefix:"a-", level:3},
  {word:"approbation",  meaning:"称賛・承認",                  etymology:"ap（〜へ）+ prob（証明する）+ ation",     root:"-prob-", level:3},
  {word:"arcane",       meaning:"秘密の・神秘的な",             etymology:"arca（箱）+ ne → 閉じられた知識",          suffix:"-ary", level:3},
  {word:"arduous",      meaning:"困難な・骨の折れる",            etymology:"arduu（急な坂）+ ous",                   suffix:"-ous", level:2},
  {word:"assuage",      meaning:"和らげる・慰める",             etymology:"as（〜へ）+ sua（甘い）+ ge",            suffix:"-age", level:3},
  {word:"atrophy",      meaning:"萎縮する・衰退する",           etymology:"a（否定）+ trophy（栄養）",              prefix:"a-", level:2},
  {word:"audacity",     meaning:"大胆さ・厚かましさ",           etymology:"aud（大胆）+ acity",                     suffix:"-ity", level:2},
  {word:"avarice",      meaning:"強欲・欲張り",                etymology:"avar（貪欲な）+ ice",                    suffix:"-ance", level:3},
  {word:"banal",        meaning:"陳腐な・月並みな",             etymology:"ban（公共の）+ al → 誰でも知っている",     suffix:"-al", level:2},
  {word:"belie",        meaning:"〜と矛盾する・偽る",           etymology:"be（強意）+ lie（嘘をつく）",            prefix:"be-", level:3},
  {word:"bellicose",    meaning:"好戦的な・けんか好きな",        etymology:"belli（戦争）+ cose",                    suffix:"-ous", level:3},
  {word:"beguile",      meaning:"だます・うまく時間を過ごす",    etymology:"be（強意）+ guile（策略）",              prefix:"be-", level:3},
  {word:"byzantine",    meaning:"複雑な・迂遠な",               etymology:"Byzantium（ビザンツ）→ 難解な複雑さ",     suffix:"-ine", level:3},
  {word:"cacophony",    meaning:"不協和音・耳障りな音",          etymology:"caco（悪い）+ phony（音）",               prefix:"a-", level:3},
  {word:"candor",       meaning:"率直さ・正直",                etymology:"cand（輝く）+ or",                       suffix:"-or", level:2},
  {word:"capricious",   meaning:"気まぐれな",                  etymology:"capri（ヤギ）+ cious → ヤギのように跳び回る", suffix:"-ous", level:2},
  {word:"castigate",    meaning:"厳しく叱る",                  etymology:"casti（純粋な）+ gate → 純粋にする",      suffix:"-ate", level:3},
  {word:"caustic",      meaning:"腐食性の・辛辣な",             etymology:"caus（燃やす）+ tic",                    suffix:"-ic", level:3},
  {word:"chicanery",    meaning:"不正手段・詭計",               etymology:"chicane（妨害）+ ry",                    suffix:"-ry", level:3},

  // ── TOEFL/IELTS学術語 ────────────────────────
  {word:"coherent",     meaning:"一貫した・筋が通った",          etymology:"co（共に）+ her（くっつく）+ ent",        prefix:"co-", level:2},
  {word:"compensate",   meaning:"補償する・埋め合わせる",         etymology:"com（共に）+ pens（量る）+ ate",          root:"-pend-", level:2},
  {word:"compliance",   meaning:"遵守・服従",                  etymology:"com（共に）+ pli（折る）+ ance",          root:"-plic-", level:2},
  {word:"comprehensive",meaning:"包括的な・広範囲の",            etymology:"com（共に）+ prehen（つかむ）+ ive",      prefix:"co-", level:2},
  {word:"constitute",   meaning:"構成する・設立する",            etymology:"con（共に）+ stitute（立てる）",          prefix:"co-", level:1},
  {word:"controversial",meaning:"議論を呼ぶ・論争的な",          etymology:"contra（反対）+ vers（向く）+ ial",       prefix:"contra-", level:1},
  {word:"conventional", meaning:"慣習的な・ありきたりの",         etymology:"con（共に）+ vent（来る）+ ional",        prefix:"co-", level:1},
  {word:"correlation",  meaning:"相関関係",                    etymology:"cor（共に）+ relat（結ぶ）+ ion",         prefix:"co-", level:2},
  {word:"criterion",    meaning:"基準・判断基準",               etymology:"crit（判断する）+ erion",                suffix:"-ion", level:2},
  {word:"cumulative",   meaning:"累積的な",                   etymology:"cumul（積み重ねる）+ ative",              suffix:"-ive", level:2},
  {word:"debilitate",   meaning:"衰弱させる",                  etymology:"de（下に）+ bilit（弱い）+ ate",          prefix:"de-", level:3},
  {word:"deference",    meaning:"敬意・従順",                  etymology:"de（下に）+ fer（運ぶ）+ ence",          root:"-fer-", level:2},
  {word:"delineate",    meaning:"輪郭を描く・明確にする",         etymology:"de（完全に）+ lineat（線を引く）+ e",     prefix:"de-", level:3},
  {word:"deprivation",  meaning:"剥奪・欠乏",                  etymology:"de（離れて）+ priv（個人）+ ation",       prefix:"de-", level:2},
  {word:"derivative",   meaning:"派生した・二次的な",            etymology:"de（離れて）+ riv（川）+ ative",         prefix:"de-", level:2},
  {word:"deterioration",meaning:"悪化・劣化",                  etymology:"deterior（より悪い）+ ation",            prefix:"de-", level:2},
  {word:"discourse",    meaning:"談話・議論",                  etymology:"dis（離れて）+ course（走る）",           root:"-cur-", level:2},
  {word:"disparity",    meaning:"格差・不均衡",                 etymology:"dis（否定）+ parity（等しさ）",           prefix:"dis-", level:2},
  {word:"disseminate",  meaning:"広める・普及させる",            etymology:"dis（離れて）+ semin（種）+ ate",         prefix:"dis-", level:2},
  {word:"divergence",   meaning:"分岐・相違",                  etymology:"di（離れて）+ vergence（向く）",          prefix:"di-", level:2},

  // ── SAT頻出語 ─────────────────────────────────
  {word:"ebullient",    meaning:"活気のある・沸き立つような",     etymology:"e（外に）+ bull（沸く）+ ient",          prefix:"a-", level:3},
  {word:"egregious",    meaning:"とんでもない・ひどい",           etymology:"e（外に）+ greg（群れ）+ ious",           root:"-sequ-", level:3},
  {word:"elicit",       meaning:"引き出す・喚起する",            etymology:"e（外に）+ licit（引く）",               prefix:"a-", level:2},
  {word:"eloquence",    meaning:"雄弁・表現力",                etymology:"e（外に）+ loqu（話す）+ ence",           root:"-loqu-", level:2},
  {word:"eminent",      meaning:"著名な・卓越した",              etymology:"e（外に）+ min（突出する）+ ent",         prefix:"a-", level:2},
  {word:"endemic",      meaning:"固有の・特定地域に見られる",     etymology:"en（中に）+ dem（民衆）+ ic",            prefix:"endo-", level:2},
  {word:"ephemeral",    meaning:"はかない・一時的な",            etymology:"epi（上に）+ hemer（日）+ al",           prefix:"epi-", level:3},
  {word:"equanimity",   meaning:"平静・冷静さ",                 etymology:"equa（等しい）+ anim（心）+ ity",         prefix:"equi-", level:3},
  {word:"eradicate",    meaning:"根絶する",                    etymology:"e（外に）+ radic（根）+ ate",             suffix:"-ate", level:2},
  {word:"esoteric",     meaning:"難解な・秘教的な",              etymology:"eso（内側）+ teric",                     suffix:"-ic", level:3},
  {word:"exasperate",   meaning:"激怒させる",                   etymology:"ex（外に）+ asper（荒い）+ ate",         prefix:"ex-", level:2},
  {word:"exhaustive",   meaning:"徹底的な・網羅的な",            etymology:"exhaust（使い果たす）+ ive",             prefix:"ex-", level:2},
  {word:"exorbitant",   meaning:"法外な・過大な",               etymology:"ex（外に）+ orbit（軌道）+ ant",         prefix:"ex-", level:2},
  {word:"expedient",    meaning:"都合のよい・得策な",             etymology:"ex（外に）+ ped（足）+ ient",            prefix:"ex-", level:3},
  {word:"explicit",     meaning:"明白な・率直な",               etymology:"ex（外に）+ plic（折る）+ it",           root:"-plic-", level:2},

  // ── 医学・科学専門語 ──────────────────────────
  {word:"acute",        meaning:"急性の・鋭い・深刻な",          etymology:"acu（鋭い）+ te",                        suffix:"-ate", level:1},
  {word:"chronic",      meaning:"慢性の・長期にわたる",          etymology:"chron（時間）+ ic",                      prefix:"chrono-", level:1},
  {word:"diagnosis",    meaning:"診断",                        etymology:"dia（横切って）+ gnosis（知識）",          prefix:"dia-", level:1},
  {word:"prognosis",    meaning:"予後・予測",                   etymology:"pro（前に）+ gnosis（知識）",             prefix:"pro-", level:2},
  {word:"pandemic",     meaning:"世界的流行病",                 etymology:"pan（すべて）+ demic（民衆）",            prefix:"a-", level:1},
  {word:"pathogen",     meaning:"病原体",                      etymology:"path（病気）+ gen（生む）",               root:"-path-", level:2},
  {word:"preclusion",   meaning:"除外・排除",                  etymology:"pre（前に）+ clus（閉じる）+ ion",        prefix:"pre-", level:3},
  {word:"remission",    meaning:"寛解・緩和",                  etymology:"re（元に）+ miss（送る）+ ion",           root:"-mit-", level:3},
  {word:"syndrome",     meaning:"症候群",                      etymology:"syn（共に）+ drome（走る）",             prefix:"syn-", level:2},
  {word:"therapeutic",  meaning:"治療の・癒しになる",            etymology:"therap（治療する）+ eutic",              suffix:"-ic", level:2},
  {word:"toxin",        meaning:"毒素",                        etymology:"tox（毒矢）+ in",                        suffix:"-ine", level:2},
  {word:"viral",        meaning:"ウイルス性の・拡散する",         etymology:"vir（毒・力）+ al",                      suffix:"-al", level:1},
  {word:"immunity",     meaning:"免疫・免除",                  etymology:"im（否定）+ mun（義務）+ ity",            prefix:"im-", level:2},
  {word:"inflammatory", meaning:"炎症を起こす・激昂させる",       etymology:"in（中に）+ flamm（炎）+ atory",         prefix:"in-", level:2},
  {word:"metabolism",   meaning:"新陳代謝",                    etymology:"meta（変化）+ bolism（投げる）",          prefix:"meta-", level:2},

  // ── ビジネス・経済語 ──────────────────────────
  {word:"acquisition",  meaning:"取得・買収",                  etymology:"ac（〜へ）+ quis（求める）+ ition",       root:"-quer-", level:2},
  {word:"arbitrage",    meaning:"裁定取引",                    etymology:"arbitr（仲裁）+ age",                    suffix:"-age", level:3},
  {word:"benchmark",    meaning:"基準・ベンチマーク",            etymology:"bench（台）+ mark（印）",                suffix:"-ment", level:2},
  {word:"collateral",   meaning:"担保・副次的な",               etymology:"col（共に）+ lateral（側）",             prefix:"co-", level:2},
  {word:"commodity",    meaning:"商品・原材料",                 etymology:"commod（利便性）+ ity",                  suffix:"-ity", level:2},
  {word:"depreciation", meaning:"減価償却・価値下落",           etymology:"de（下に）+ prec（価格）+ iation",        prefix:"de-", level:2},
  {word:"dividend",     meaning:"配当金",                      etymology:"di（離れて）+ vid（分ける）+ end",         prefix:"di-", level:2},
  {word:"fiscal",       meaning:"財政の・会計の",               etymology:"fisc（国庫）+ al",                       suffix:"-al", level:2},
  {word:"incentive",    meaning:"奨励金・動機",                 etymology:"in（中に）+ cent（歌う）+ ive",           prefix:"in-", level:1},
  {word:"inflation",    meaning:"インフレ・膨張",               etymology:"in（中に）+ flat（吹く）+ ion",           prefix:"in-", level:1},
  {word:"leverage",     meaning:"てこ・影響力・借り入れ",         etymology:"lever（てこ）+ age",                     suffix:"-age", level:2},
  {word:"liability",    meaning:"責任・負債",                  etymology:"li（縛る）+ ability",                    suffix:"-ity", level:2},
  {word:"liquidate",    meaning:"清算する・処分する",            etymology:"liquid（液体）+ ate → 流動化する",        suffix:"-ate", level:2},
  {word:"merger",       meaning:"合併",                        etymology:"merg（沈む・合わさる）+ er",              suffix:"-er", level:2},
  {word:"monetary",     meaning:"金融の・通貨の",               etymology:"monet（貨幣）+ ary",                     suffix:"-ary", level:2},
  {word:"portfolio",    meaning:"資産構成・作品集",              etymology:"port（運ぶ）+ folio（紙）",               root:"-port-", level:2},
  {word:"proprietary",  meaning:"所有権のある・独自の",          etymology:"propri（自分の）+ etary",               suffix:"-ary", level:2},
  {word:"recession",    meaning:"景気後退",                    etymology:"re（後ろに）+ cess（行く）+ ion",         prefix:"re-", level:2},
  {word:"subsidy",      meaning:"補助金",                      etymology:"sub（下に）+ sid（座る）+ y",             prefix:"sub-", level:2},
  {word:"surplus",      meaning:"余剰・黒字",                  etymology:"sur（上に）+ plus（多い）",               prefix:"sur-", level:2},

  // ── 法律語 ───────────────────────────────────
  {word:"acquittal",    meaning:"無罪放免",                   etymology:"ac（〜へ）+ quit（解放する）+ tal",       suffix:"-al", level:2},
  {word:"affidavit",    meaning:"宣誓供述書",                  etymology:"af（〜へ）+ fid（信頼）+ avit",           root:"-jur-", level:3},
  {word:"arraign",      meaning:"起訴する・訴える",             etymology:"ar（〜へ）+ raign（理由）",               root:"-jur-", level:3},
  {word:"bailiff",      meaning:"執行官・廷吏",                etymology:"bail（保護）+ iff",                      suffix:"-iff", level:3},
  {word:"culpable",     meaning:"有責の・非難に値する",          etymology:"culp（罪）+ able",                       suffix:"-able", level:3},
  {word:"defendant",    meaning:"被告",                        etymology:"de（下に）+ fend（守る）+ ant",           prefix:"de-", level:2},
  {word:"deposition",   meaning:"証言・退位",                  etymology:"de（下に）+ pos（置く）+ ition",         root:"-pos-", level:2},
  {word:"habeas corpus",meaning:"人身保護令状",                etymology:"habe（持つ）+ as corpus（体を）",         root:"-jur-", level:3},
  {word:"indictment",   meaning:"起訴状",                     etymology:"in（中に）+ dict（言う）+ ment",         root:"-dict-", level:2},
  {word:"injunction",   meaning:"差止命令",                   etymology:"in（中に）+ junct（結ぶ）+ ion",         root:"-jur-", level:3},
  {word:"litigation",   meaning:"訴訟・争訟",                  etymology:"litis（争い）+ gation",                  suffix:"-tion", level:2},
  {word:"plaintiff",    meaning:"原告",                        etymology:"plain（訴える）+ iff",                   root:"-jur-", level:2},
  {word:"precedent",    meaning:"前例・先例",                  etymology:"pre（前に）+ cedent（行く）",             prefix:"pre-", level:2},
  {word:"prosecution",  meaning:"起訴・検察",                  etymology:"pro（前に）+ secut（続く）+ ion",         root:"-sequ-", level:2},
  {word:"statute",      meaning:"制定法・規則",                etymology:"stat（立てる）+ ute",                    suffix:"-ute", level:2},

  // ── 心理学・社会学語 ─────────────────────────
  {word:"cognitive",    meaning:"認知的な",                   etymology:"cogn（知る）+ itive",                    root:"-sci-", level:2},
  {word:"conditioned",  meaning:"条件付けられた",              etymology:"con（共に）+ dit（与える）+ ioned",       prefix:"co-", level:2},
  {word:"conformity",   meaning:"一致・同調",                  etymology:"con（共に）+ form（形）+ ity",            prefix:"co-", level:2},
  {word:"delusional",   meaning:"妄想性の",                   etymology:"de（離れて）+ lus（騙す）+ ional",        prefix:"de-", level:2},
  {word:"inhibition",   meaning:"抑制・遠慮",                  etymology:"in（中に）+ hibit（保つ）+ ion",          prefix:"in-", level:2},
  {word:"introvert",    meaning:"内向的な人",                  etymology:"intro（内に）+ vert（向く）",             prefix:"intra-", level:1},
  {word:"neuroscience", meaning:"神経科学",                   etymology:"neuro（神経）+ science（科学）",          prefix:"a-", level:2},
  {word:"resilience",   meaning:"回復力・レジリエンス",          etymology:"re（再び）+ sil（跳ぶ）+ ience",         prefix:"re-", level:2},
  {word:"stigma",       meaning:"烙印・偏見",                  etymology:"stig（刺す）+ ma",                       suffix:"-ic", level:2},
  {word:"subconscious", meaning:"潜在意識の",                  etymology:"sub（下に）+ conscious（意識がある）",    prefix:"sub-", level:2},

  // ── 哲学・人文科学語 ─────────────────────────
  {word:"epistemology", meaning:"認識論",                     etymology:"episteme（知識）+ logy（学問）",          root:"-log-", level:3},
  {word:"hegemony",     meaning:"覇権・主導権",               etymology:"hege（導く）+ mony",                     suffix:"-ment", level:2},
  {word:"hermeneutics", meaning:"解釈学",                     etymology:"hermen（解釈する）+ eutics",             suffix:"-ic", level:3},
  {word:"metaphysics",  meaning:"形而上学",                   etymology:"meta（超えた）+ physics（物理学）",       prefix:"meta-", level:3},
  {word:"ontology",     meaning:"存在論",                     etymology:"onto（存在）+ logy（学問）",              root:"-log-", level:3},
  {word:"paradigm",     meaning:"パラダイム・典型例",           etymology:"para（横に）+ digm（示す）",             prefix:"para-", level:2},
  {word:"zeitgeist",    meaning:"時代精神",                   etymology:"Zeit（時代）+ Geist（精神）→ ドイツ語",   suffix:"-ism", level:3},
  {word:"empirical",    meaning:"経験的な・実証的な",           etymology:"empir（経験）+ ical",                    suffix:"-al", level:2},
  {word:"existential",  meaning:"実存的な",                  etymology:"exist（存在する）+ ential",              suffix:"-al", level:2},
  {word:"phenomenology",meaning:"現象学",                    etymology:"phenom（現象）+ logy（学問）",            root:"-log-", level:3},

  // ── 環境・自然科学語 ─────────────────────────
  {word:"biodegradable",meaning:"生分解可能な",               etymology:"bio（生命）+ degrad（分解）+ able",       prefix:"bio-", level:2},
  {word:"ecosystem",    meaning:"生態系",                    etymology:"eco（環境）+ system（体系）",             root:"-log-", level:1},
  {word:"extinction",   meaning:"絶滅・消滅",                etymology:"ex（外に）+ tinct（消える）+ ion",        prefix:"ex-", level:1},
  {word:"geothermal",   meaning:"地熱の",                    etymology:"geo（大地）+ thermal（熱の）",            prefix:"geo-", level:2},
  {word:"mitigation",   meaning:"緩和・軽減",                etymology:"mit（柔らかい）+ ig + ation",            root:"-med-", level:2},
  {word:"photovoltaic", meaning:"光起電力の",                 etymology:"photo（光）+ voltaic（電力の）",          prefix:"photo-", level:3},
  {word:"precipitation",meaning:"降水量・沈殿",               etymology:"pre（前に）+ cipitat（落ちる）+ ion",     prefix:"pre-", level:2},
  {word:"sustainable",  meaning:"持続可能な",                etymology:"sus（下から）+ tain（保つ）+ able",        root:"-ten-", level:1},
  {word:"trajectory",   meaning:"軌跡・弾道",                etymology:"trans（超えて）+ ject（投げる）+ ory",    root:"-ject-", level:2},
  {word:"turbulent",    meaning:"激しく乱れた・波乱の",         etymology:"turbul（乱流）+ ent",                    suffix:"-ent", level:2},

  // ── テクノロジー・デジタル語 ──────────────────
  {word:"algorithm",    meaning:"アルゴリズム・計算手順",       etymology:"al-Khwarizmi（数学者名）",               prefix:"astro-", level:1},
  {word:"encryption",   meaning:"暗号化",                    etymology:"en（中に）+ crypt（隠す）+ ion",         prefix:"en-", level:2},
  {word:"exponential",  meaning:"指数的な",                   etymology:"ex（外に）+ pon（置く）+ ential",        root:"-pos-", level:2},
  {word:"infrastructure",meaning:"インフラ・基盤",             etymology:"infra（下に）+ struct（築く）+ ure",     root:"-struct-", level:2},
  {word:"interoperability",meaning:"相互運用性",               etymology:"inter（間に）+ operable（操作できる）+ ity",prefix:"inter-",level:3},
  {word:"latency",      meaning:"潜在性・遅延",               etymology:"late（隠れた）+ ncy",                    suffix:"-ency", level:2},
  {word:"parameter",    meaning:"パラメータ・変数",            etymology:"para（横に）+ meter（測る）",            prefix:"para-", level:2},
  {word:"prototype",    meaning:"原型・試作品",                etymology:"proto（最初）+ type（型）",              prefix:"proto-", level:2},
  {word:"redundancy",   meaning:"冗長性・余剰",               etymology:"re（再び）+ und（波）+ ancy",            prefix:"re-", level:2},
  {word:"scalable",     meaning:"拡張可能な",                 etymology:"scal（はしご）+ able",                   suffix:"-able", level:2},

  // ── GRE高難語（続き） ─────────────────────────
  {word:"circumlocution",meaning:"遠回しな言い方",             etymology:"circum（周囲）+ locut（話す）+ ion",     prefix:"circum-", level:3},
  {word:"clandestine",  meaning:"内密の・秘密の",              etymology:"clam（隠れる）+ destine",               suffix:"-ine", level:3},
  {word:"coalesce",     meaning:"合体する・融合する",           etymology:"co（共に）+ alesce（育つ）",             prefix:"co-", level:3},
  {word:"cogent",       meaning:"説得力のある",                etymology:"co（共に）+ gent（行く）",               prefix:"co-", level:3},
  {word:"commensurate", meaning:"釣り合った・比例した",          etymology:"com（共に）+ mensur（測る）+ ate",        prefix:"co-", level:3},
  {word:"compunction",  meaning:"良心の呵責",                 etymology:"com（共に）+ punct（刺す）+ ion",        prefix:"co-", level:3},
  {word:"condone",      meaning:"許す・黙認する",              etymology:"con（共に）+ done（与える）",             prefix:"co-", level:2},
  {word:"confound",     meaning:"混乱させる・打ち破る",          etymology:"con（共に）+ found（混ぜる）",           prefix:"co-", level:2},
  {word:"congenial",    meaning:"気の合う・好ましい",           etymology:"con（共に）+ genial（生まれつき）",       prefix:"co-", level:2},
  {word:"contrite",     meaning:"後悔している・悔い改めた",      etymology:"con（完全に）+ trite（すり減った）",      prefix:"co-", level:3},
  {word:"corpulent",    meaning:"太った・肥満の",               etymology:"corp（体）+ ulent",                      suffix:"-ent", level:3},
  {word:"covert",       meaning:"隠密の・秘密の",              etymology:"co（共に）+ vert（覆う）",               prefix:"co-", level:2},
  {word:"craven",       meaning:"臆病な・卑怯な",              etymology:"craven（負け犬）",                       suffix:"-en", level:3},
  {word:"culpable",     meaning:"有罪の・非難に値する",          etymology:"culp（罪）+ able",                       suffix:"-able", level:3},
  {word:"cupidity",     meaning:"強欲・金銭欲",                etymology:"cupid（欲望）+ ity",                     suffix:"-ity", level:3},
  {word:"cursory",      meaning:"おざなりの・急ぎの",           etymology:"curs（走る）+ ory",                      root:"-cur-", level:3},
  {word:"cynical",      meaning:"冷笑的な・皮肉な",             etymology:"cynos（犬）+ ical → 犬儒派の",           suffix:"-al", level:2},
  {word:"dauntless",    meaning:"勇敢な・恐れを知らない",        etymology:"daunt（怖がらせる）+ less",              suffix:"-less", level:2},
  {word:"dearth",       meaning:"不足・欠乏",                  etymology:"dear（高価な）+ th",                     suffix:"-th", level:2},
  {word:"debacle",      meaning:"大失敗・崩壊",                etymology:"de（下に）+ bacle（棒）",                prefix:"de-", level:3},
  {word:"debase",       meaning:"品質を落とす・貶める",          etymology:"de（下に）+ base（基礎）",               prefix:"de-", level:2},
  {word:"debunk",       meaning:"暴く・正体を暴露する",          etymology:"de（除く）+ bunk（でたらめ）",           prefix:"de-", level:2},
  {word:"decorum",      meaning:"礼儀正しさ・品位",             etymology:"decor（装飾）+ um",                      suffix:"-ment", level:2},
  {word:"defunct",      meaning:"廃止された・死んだ",           etymology:"de（離れて）+ funct（機能する）",        prefix:"de-", level:2},
  {word:"demagogue",    meaning:"扇動政治家",                  etymology:"dema（民衆）+ gogue（導く）",            prefix:"de-", level:2},
  {word:"demur",        meaning:"異議を唱える",                etymology:"de（下に）+ mur（遅延する）",            prefix:"de-", level:3},
  {word:"denouement",   meaning:"（物語の）結末・解決",          etymology:"de（解く）+ noue（結ぶ）+ ment",         prefix:"de-", level:3},
  {word:"desultory",    meaning:"とりとめのない・散漫な",         etymology:"de（下に）+ salt（跳ぶ）+ ory",         prefix:"de-", level:3},
  {word:"diatribe",     meaning:"激しい非難・罵倒",             etymology:"dia（完全に）+ trib（こする）+ e",        prefix:"dia-", level:3},
  {word:"diffident",    meaning:"自信のない・内気な",            etymology:"dif（否定）+ fid（信頼）+ ent",          root:"-jur-", level:2},

  // ── ビジネス・経済語（続き） ──────────────────
  {word:"amortization", meaning:"償却",                       etymology:"a（〜に）+ mort（死）+ ization",         root:"-mor-", level:3},
  {word:"arbitration",  meaning:"仲裁・調停",                  etymology:"arbitr（仲裁する）+ ation",              suffix:"-tion", level:2},
  {word:"asymmetric",   meaning:"非対称の",                   etymology:"a（否定）+ symmetric（対称の）",         prefix:"a-", level:2},
  {word:"austerity",    meaning:"緊縮財政・質素",               etymology:"auster（厳格な）+ ity",                  suffix:"-ity", level:2},
  {word:"capitalization",meaning:"資本化・時価総額",            etymology:"capital（資本）+ ization",              suffix:"-tion", level:2},
  {word:"consortium",   meaning:"コンソーシアム・共同事業",      etymology:"con（共に）+ sort（仲間）+ ium",          prefix:"co-", level:2},
  {word:"contingency",  meaning:"偶発事態・不測の事態",          etymology:"con（共に）+ ting（触れる）+ ency",      root:"-tang-", level:2},
  {word:"default",      meaning:"債務不履行・デフォルト",        etymology:"de（離れて）+ fault（失敗）",            prefix:"de-", level:2},
  {word:"deficiency",   meaning:"欠乏・不足",                  etymology:"de（否定）+ fic（作る）+ iency",         prefix:"de-", level:2},
  {word:"deflation",    meaning:"デフレ・物価下落",             etymology:"de（下に）+ flat（吹く）+ ion",          prefix:"de-", level:2},
  {word:"deregulation", meaning:"規制緩和",                   etymology:"de（除く）+ regulation（規制）",         prefix:"de-", level:2},
  {word:"divestiture",  meaning:"売却・資産処分",               etymology:"di（離れて）+ vest（着る）+ iture",      prefix:"di-", level:3},
  {word:"entrepreneur", meaning:"起業家",                     etymology:"entre（間に）+ preneur（取る）",         prefix:"a-", level:2},
  {word:"fiduciary",    meaning:"受託者の・信託の",             etymology:"fiduc（信頼）+ iary",                    root:"-jur-", level:3},
  {word:"infrastructure",meaning:"基盤・インフラ",              etymology:"infra（下に）+ struct（築く）+ ure",     prefix:"infra-", level:2},
  {word:"insolvency",   meaning:"支払い不能",                  etymology:"in（否定）+ solv（解く）+ ency",         root:"-solv-", level:3},
  {word:"intangible",   meaning:"無形の・把握しにくい",          etymology:"in（否定）+ tang（触れる）+ ible",       root:"-tang-", level:2},
  {word:"liquidity",    meaning:"流動性・換金性",               etymology:"liquid（液体）+ ity",                    suffix:"-ity", level:2},
  {word:"macroeconomics",meaning:"マクロ経済学",                etymology:"macro（大きい）+ economics（経済学）",   prefix:"macro-", level:2},
  {word:"microeconomics",meaning:"ミクロ経済学",                etymology:"micro（小さい）+ economics（経済学）",   prefix:"micro-", level:2},
  {word:"monopolistic", meaning:"独占的な",                   etymology:"mono（一つ）+ pol（売る）+ istic",       prefix:"mono-", level:2},
  {word:"procurement",  meaning:"調達・入手",                  etymology:"pro（前に）+ cure（手配する）+ ment",    prefix:"pro-", level:2},
  {word:"profitability",meaning:"収益性",                     etymology:"profit（利益）+ ability",               suffix:"-ity", level:2},
  {word:"remuneration", meaning:"報酬・報い",                  etymology:"re（再び）+ mun（贈り物）+ eration",     prefix:"re-", level:3},
  {word:"stakeholder",  meaning:"利害関係者",                  etymology:"stake（賭け）+ holder（保有者）",        suffix:"-er", level:1},
  {word:"transaction",  meaning:"取引・処理",                  etymology:"trans（超えて）+ act（行う）+ ion",      prefix:"trans-", level:1},
  {word:"volatility",   meaning:"変動性・不安定さ",             etymology:"volat（飛ぶ）+ ility",                   suffix:"-ity", level:2},
  {word:"yield",        meaning:"産出量・利回り・譲歩する",       etymology:"gield（支払う）",                        suffix:"-ment", level:1},
  {word:"benchmark",    meaning:"基準値",                     etymology:"bench（台）+ mark（印）",                suffix:"-ment", level:1},
  {word:"offshore",     meaning:"オフショア・海外の",            etymology:"off（離れて）+ shore（岸）",             prefix:"a-", level:1},

  // ── 学術一般語（重要動詞・形容詞） ────────────
  {word:"acknowledge",  meaning:"認める・感謝する",             etymology:"ac（〜へ）+ knowl（知識）+ edge",        prefix:"ad-", level:1},
  {word:"aggregate",    meaning:"集計する・合計の",             etymology:"ag（〜へ）+ greg（群れ）+ ate",          root:"-sequ-", level:2},
  {word:"alleviate",    meaning:"緩和する・軽減する",           etymology:"al（〜へ）+ levi（軽い）+ ate",          suffix:"-ate", level:2},
  {word:"ambiguous",    meaning:"曖昧な・不明確な",             etymology:"ambi（両方）+ guous",                    prefix:"ambi-", level:2},
  {word:"analogous",    meaning:"類似した・相似の",             etymology:"ana（対応して）+ log（言葉）+ ous",       root:"-log-", level:2},
  {word:"apprehend",    meaning:"理解する・逮捕する",           etymology:"ap（〜へ）+ prehen（つかむ）+ d",         prefix:"ad-", level:2},
  {word:"articulate",   meaning:"明確に表現する・関節の",        etymology:"articul（関節）+ ate",                   suffix:"-ate", level:2},
  {word:"assess",       meaning:"評価する・査定する",           etymology:"as（〜へ）+ sess（座る）",               prefix:"ad-", level:1},
  {word:"attenuate",    meaning:"薄める・弱める",               etymology:"at（〜へ）+ tenu（薄い）+ ate",          prefix:"ad-", level:3},
  {word:"augment",      meaning:"増加させる・拡大する",          etymology:"aug（増やす）+ ment",                    suffix:"-ment", level:2},
  {word:"bolster",      meaning:"支持する・強化する",            etymology:"bol（膨らむ）+ ster",                    suffix:"-er", level:2},
  {word:"circumvent",   meaning:"迂回する・回避する",           etymology:"circum（周囲）+ vent（来る）",           prefix:"circum-", level:3},
  {word:"clarify",      meaning:"明確にする",                  etymology:"clar（明確な）+ ify",                    suffix:"-fy", level:1},
  {word:"coerce",       meaning:"強制する",                   etymology:"co（共に）+ erce（封じ込める）",          prefix:"co-", level:2},
  {word:"commence",     meaning:"開始する",                   etymology:"com（完全に）+ menc（始める）+ e",        prefix:"co-", level:2},
  {word:"concede",      meaning:"認める・譲歩する",             etymology:"con（共に）+ cede（行く）",              prefix:"co-", level:2},
  {word:"confiscate",   meaning:"没収する",                   etymology:"con（共に）+ fisc（国庫）+ ate",          prefix:"co-", level:2},
  {word:"convey",       meaning:"伝える・運ぶ",                etymology:"con（共に）+ vey（運ぶ）",               prefix:"co-", level:1},
  {word:"correspond",   meaning:"一致する・通信する",            etymology:"cor（共に）+ respond（応答する）",        prefix:"co-", level:1},
  {word:"curtail",      meaning:"削減する・短縮する",           etymology:"cur（短い）+ tail（切る）",              root:"-cur-", level:2},

  // ── 重要形容詞・副詞 ──────────────────────────
  {word:"aberrant",     meaning:"逸脱した・異常な",            etymology:"ab（離れて）+ errant（さまよう）",       prefix:"ab-", level:3},
  {word:"abstruse",     meaning:"難解な",                     etymology:"abs（離れて）+ trus（押す）+ e",         prefix:"ab-", level:3},
  {word:"acerbic",      meaning:"辛辣な・苦い",                etymology:"acer（鋭い）+ bic",                      suffix:"-ic", level:3},
  {word:"acrimonious",  meaning:"険悪な・口論の多い",           etymology:"acri（鋭い）+ monious",                  suffix:"-ous", level:3},
  {word:"adroit",       meaning:"器用な・巧みな",              etymology:"a（〜へ）+ droit（正しい）",             prefix:"ad-", level:2},
  {word:"amiable",      meaning:"愛想のよい",                  etymology:"ami（友人）+ able",                      suffix:"-able", level:1},
  {word:"amicable",     meaning:"友好的な・円満な",             etymology:"amicabl（友好的な）→ able",              suffix:"-able", level:2},
  {word:"anachronistic",meaning:"時代錯誤の",                 etymology:"ana（後ろに）+ chron（時間）+ istic",     prefix:"chrono-", level:3},
  {word:"apathetic",    meaning:"無関心な・無気力な",           etymology:"a（否定）+ path（感じる）+ etic",        root:"-path-", level:2},
  {word:"assiduous",    meaning:"勤勉な・専心する",             etymology:"as（〜へ）+ sid（座る）+ uous",          prefix:"ad-", level:3},
  {word:"austere",      meaning:"厳格な・質素な",              etymology:"auster（厳格な）+ e",                    suffix:"-ous", level:2},
  {word:"belligerent",  meaning:"好戦的な・交戦中の",           etymology:"belli（戦争）+ gerent（行う）",          prefix:"be-", level:2},
  {word:"beneficent",   meaning:"慈善的な・恵み深い",           etymology:"bene（良い）+ fic（作る）+ ent",         prefix:"bene-", level:2},
  {word:"brazen",       meaning:"厚かましい・真鍮の",           etymology:"braz（真鍮）+ en",                       suffix:"-en", level:2},
  {word:"bucolic",      meaning:"田園の・牧歌的な",             etymology:"bucol（牛飼い）+ ic",                    suffix:"-ic", level:3},
  {word:"burgeoning",   meaning:"急成長している",               etymology:"burgeon（芽生える）+ ing",              suffix:"-ing", level:2},
  {word:"callous",      meaning:"無神経な・冷淡な",             etymology:"callus（硬くなった皮膚）+ ous",          suffix:"-ous", level:2},
  {word:"candid",       meaning:"率直な・公正な",              etymology:"cand（輝く）+ id",                       suffix:"-ed", level:1},
  {word:"capacious",    meaning:"広大な・容量の大きい",          etymology:"cap（取る）+ acious",                    suffix:"-ous", level:2},
  {word:"categorical",  meaning:"断固とした・絶対的な",          etymology:"categor（分類）+ ical",                  suffix:"-al", level:2},
  {word:"celerity",     meaning:"素早さ・迅速さ",              etymology:"celer（速い）+ ity",                     suffix:"-ity", level:3},
  {word:"censorious",   meaning:"批判的な・小言の多い",          etymology:"censor（検閲官）+ ious",                suffix:"-ous", level:3},
  {word:"circuitous",   meaning:"回り道の・遠回しの",            etymology:"circui（回路）+ tous",                   prefix:"circum-", level:3},
  {word:"clement",      meaning:"温和な・穏やかな",             etymology:"clement（穏和な）",                      suffix:"-ent", level:2},
  {word:"clichéd",      meaning:"陳腐な",                     etymology:"cliché（刷版）+ d",                      suffix:"-ed", level:1},
  {word:"cognizant",    meaning:"〜を知っている",               etymology:"cogn（知る）+ izant",                    root:"-sci-", level:2},
  {word:"colloquial",   meaning:"口語的な・会話的な",           etymology:"col（共に）+ loqu（話す）+ ial",         root:"-loqu-", level:2},
  {word:"complacent",   meaning:"自己満足した",                etymology:"complace（満足する）+ nt",               suffix:"-ent", level:2},
  {word:"conciliatory", meaning:"和解を求める",                etymology:"concili（集める）+ atory",               suffix:"-ory", level:3},
  {word:"conducive",    meaning:"助けになる・促進する",          etymology:"con（共に）+ duc（導く）+ ive",           root:"-duc-", level:2},

  // ── 重要名詞 ──────────────────────────────────
  {word:"accolade",     meaning:"称賛・表彰",                  etymology:"ac（〜へ）+ col（首）+ ade → 首を抱く",   suffix:"-ade", level:2},
  {word:"adage",        meaning:"ことわざ・格言",              etymology:"ad（〜へ）+ age（言う）",                suffix:"-age", level:2},
  {word:"adversity",    meaning:"逆境・苦難",                  etymology:"ad（反対）+ vers（向く）+ ity",           prefix:"ad-", level:2},
  {word:"affinity",     meaning:"親和性・好み",                etymology:"af（〜へ）+ fin（境界）+ ity",            prefix:"ad-", level:2},
  {word:"allegory",     meaning:"寓話・アレゴリー",             etymology:"alle（他の）+ gory（言う）",             suffix:"-ory", level:2},
  {word:"altercation",  meaning:"口論・争い",                  etymology:"alter（他の）+ cation",                  suffix:"-tion", level:3},
  {word:"amnesty",      meaning:"恩赦・大赦",                  etymology:"amn（忘れる）+ esty",                    root:"-mem-", level:2},
  {word:"anecdote",     meaning:"逸話・エピソード",             etymology:"an（否定）+ ecdote（出版された）",        prefix:"a-", level:1},
  {word:"animosity",    meaning:"敵意・恨み",                  etymology:"anim（精神）+ osity",                    suffix:"-ity", level:2},
  {word:"annihilate",   meaning:"全滅させる",                  etymology:"an（否定）+ nihil（無）+ ate",            prefix:"a-", level:2},
  {word:"antagonism",   meaning:"対立・敵意",                  etymology:"ant（反対）+ agon（争い）+ ism",          prefix:"anti-", level:2},
  {word:"aphorism",     meaning:"格言・金言",                  etymology:"apo（離れて）+ hor（境界）+ ism",         prefix:"a-", level:3},
  {word:"apprentice",   meaning:"見習い・徒弟",                etymology:"appren（学ぶ）+ tice",                   suffix:"-ance", level:1},
  {word:"archetype",    meaning:"原型・典型",                  etymology:"arche（最初）+ type（型）",              prefix:"arch-", level:2},
  {word:"artifact",     meaning:"人工物・遺物",                etymology:"arti（技術）+ fact（作る）",             suffix:"-ment", level:1},
  {word:"asceticism",   meaning:"禁欲主義",                   etymology:"aske（鍛える）+ ticism",                 suffix:"-ism", level:3},
  {word:"assimilation", meaning:"同化・吸収",                  etymology:"as（〜へ）+ simil（同じ）+ ation",       root:"-simil-", level:2},
  {word:"atrocity",     meaning:"残虐行為",                   etymology:"atroc（凶暴な）+ ity",                   suffix:"-ity", level:2},
  {word:"autonomy",     meaning:"自律性・自治",                etymology:"auto（自己）+ nom（法則）+ y",            root:"-nom-", level:2},
  {word:"axiom",        meaning:"公理・自明の理",               etymology:"axios（価値ある）+ iom",                 suffix:"-ism", level:2},

  // ── 重要動詞（続き） ─────────────────────────
  {word:"abdicate",     meaning:"退位する・放棄する",           etymology:"ab（離れて）+ dic（言う）+ ate",         root:"-dict-", level:2},
  {word:"abridge",      meaning:"短縮する・要約する",           etymology:"a（〜へ）+ bridge（橋）→ 縮める",         prefix:"ab-", level:2},
  {word:"absolve",      meaning:"免除する・無罪にする",          etymology:"ab（離れて）+ solv（解く）+ e",          root:"-solv-", level:3},
  {word:"accrue",       meaning:"累積する・発生する",           etymology:"ac（〜へ）+ crue（成長する）",            prefix:"ad-", level:2},
  {word:"adhere",       meaning:"固執する・接着する",           etymology:"ad（〜へ）+ here（くっつく）",           root:"-here-", level:2},
  {word:"aggravate",    meaning:"悪化させる・怒らせる",          etymology:"ag（〜へ）+ grav（重い）+ ate",           prefix:"ad-", level:2},
  {word:"annex",        meaning:"併合する・付加する",           etymology:"an（〜へ）+ nex（結ぶ）",                prefix:"ad-", level:2},
  {word:"appease",      meaning:"なだめる・慰める",             etymology:"ap（〜へ）+ pease（和平）",              prefix:"ad-", level:2},
  {word:"arbitrate",    meaning:"仲裁する",                   etymology:"arbitr（仲裁する）+ ate",                root:"-jur-", level:2},
  {word:"aspire",       meaning:"熱望する・目指す",             etymology:"a（〜へ）+ spire（息）",                 root:"-spir-", level:2},
  {word:"attest",       meaning:"証言する・証明する",           etymology:"at（〜へ）+ test（証言）",               root:"-jur-", level:2},
  {word:"bequeath",     meaning:"遺贈する",                   etymology:"be（強意）+ queath（言う）",              prefix:"be-", level:3},
  {word:"circumscribe", meaning:"制限する・描き囲む",           etymology:"circum（周囲）+ scrib（書く）+ e",        prefix:"circum-", level:3},
  {word:"cite",         meaning:"引用する・召喚する",           etymology:"cit（呼び出す）+ e",                     root:"-dict-", level:1},
  {word:"collaborate",  meaning:"協力する",                   etymology:"col（共に）+ labor（働く）+ ate",         root:"-labor-", level:1},
  {word:"commemorate",  meaning:"記念する",                   etymology:"com（共に）+ memor（記憶）+ ate",         root:"-mem-", level:2},
  {word:"congregate",   meaning:"集まる",                    etymology:"con（共に）+ greg（群れ）+ ate",          prefix:"co-", level:2},
  {word:"conjure",      meaning:"魔法をかける・懇願する",        etymology:"con（共に）+ jure（誓う）",              root:"-jur-", level:2},
  {word:"consolidate",  meaning:"統合する・固める",             etymology:"con（共に）+ solid（固める）+ ate",       prefix:"co-", level:2},
  {word:"corroborate",  meaning:"裏付ける・確証する",           etymology:"cor（共に）+ roborate（強める）",        prefix:"co-", level:3},

  // 重要な形容詞（続き）
  {word:"austere",      meaning:"厳格な・質素な",               etymology:"auster（厳しい）+ e",                   suffix:"-ous", level:2},
  {word:"banal",        meaning:"陳腐な・平凡な",               etymology:"ban（公共の）+ al",                     suffix:"-al", level:2},
  {word:"benign",       meaning:"良性の・穏やかな",              etymology:"bene（良い）+ gn（生まれ）",             prefix:"bene-", level:2},
  {word:"candid",       meaning:"率直な・正直な",               etymology:"candid（白い・輝く）",                   suffix:"-id", level:1},
  {word:"chronic",      meaning:"慢性的な・長期の",              etymology:"chron（時間）+ ic",                    root:"-tempor-", level:1},
  {word:"contrite",     meaning:"深く後悔した",                 etymology:"con（完全に）+ trite（すり減らす）",       prefix:"co-", level:3},
  {word:"credulous",    meaning:"信じやすい・だまされやすい",     etymology:"cred（信じる）+ ulous",                 root:"-cred-", level:2},
  {word:"cryptic",      meaning:"謎めいた・難解な",              etymology:"crypt（隠す）+ ic",                    suffix:"-ic", level:2},
  {word:"cursory",      meaning:"急いだ・大まかな",              etymology:"curs（走る）+ ory",                    root:"-cur-", level:2},
  {word:"defunct",      meaning:"廃止された・死んだ",            etymology:"de（否定）+ funct（機能する）",           prefix:"de-", level:2},
  {word:"deleterious",  meaning:"有害な",                      etymology:"delete（消す）+ rious",                 suffix:"-ous", level:3},
  {word:"diffident",    meaning:"自信のない・内気な",            etymology:"dif（否定）+ fid（信頼）+ ent",          prefix:"dis-", level:3},
  {word:"digressive",   meaning:"脱線した・回り道の",            etymology:"di（離れて）+ gress（進む）+ ive",       root:"-grad-", level:3},
  {word:"discordant",   meaning:"不調和な",                    etymology:"dis（否定）+ cord（心）+ ant",           prefix:"dis-", level:2},
  {word:"durable",      meaning:"耐久性のある",                 etymology:"dur（硬い・続く）+ able",                suffix:"-able", level:1},

  // 重要な名詞（続き）
  {word:"acumen",       meaning:"洞察力・鋭敏さ",               etymology:"acu（尖る）+ men",                     suffix:"-ment", level:2},
  {word:"allegiance",   meaning:"忠誠・忠義",                  etymology:"al（〜へ）+ leg（法）+ iance",           suffix:"-ance", level:2},
  {word:"altruism",     meaning:"利他主義",                    etymology:"altr（他者）+ u + ism",                suffix:"-ism", level:2},
  {word:"ambiguity",    meaning:"曖昧さ",                     etymology:"ambi（両方）+ gu（動く）+ ity",          prefix:"ambi-", level:2},
  {word:"apathy",       meaning:"無関心・無気力",               etymology:"a（否定）+ path（感情）+ y",            root:"-path-", level:1},
  {word:"archetype",    meaning:"原型・典型",                  etymology:"arche（最初）+ type（型）",              prefix:"arch-", level:2},
  {word:"atrophy",      meaning:"萎縮・退化",                  etymology:"a（否定）+ troph（栄養）+ y",            prefix:"a-", level:2},
  {word:"aversion",     meaning:"嫌悪・反感",                  etymology:"a（離れて）+ vers（向く）+ ion",         root:"-vert-", level:2},
  {word:"axiom",        meaning:"公理・自明の理",               etymology:"axios（価値ある）+ m",                  suffix:"-ism", level:2},
  {word:"catalyst",     meaning:"触媒・きっかけ",               etymology:"cata（下へ）+ lyst（分解）",             prefix:"cata-", level:2},
  {word:"coherence",    meaning:"一貫性・まとまり",              etymology:"co（共に）+ here（くっつく）+ nce",      root:"-here-", level:2},
  {word:"conundrum",    meaning:"難問・謎",                    etymology:"con（共に）+ undrum（不明）",            prefix:"co-", level:2},
  {word:"covenant",     meaning:"契約・誓約",                  etymology:"co（共に）+ ven（来る）+ ant",           root:"-ven-", level:2},

  // 重要な動詞（続き）
  {word:"capitulate",   meaning:"降伏する・屈服する",           etymology:"capit（頭）+ ul + ate",                root:"-cap-", level:3},
  {word:"censure",      meaning:"非難する・叱責する",           etymology:"cens（判断する）+ ure",                 suffix:"-ure", level:2},
  {word:"curtail",      meaning:"削減する・切り詰める",          etymology:"curt（短い）+ ail",                    suffix:"-al", level:2},
  {word:"delineate",    meaning:"描写する・説明する",           etymology:"de（完全に）+ lineat（線）+ e",          prefix:"de-", level:2},
  {word:"demarcate",    meaning:"境界を定める",                etymology:"de（完全に）+ marc（境界）+ ate",        prefix:"de-", level:3},
  {word:"denigrate",    meaning:"中傷する・侮辱する",           etymology:"de（否定）+ nigr（黒）+ ate",            prefix:"de-", level:3},
  {word:"deplete",      meaning:"枯渇させる",                  etymology:"de（否定）+ plete（満たす）",            prefix:"de-", level:2},
  {word:"disseminate",  meaning:"広める・普及させる",           etymology:"dis（広げる）+ semin（種）+ ate",        prefix:"dis-", level:2},
  {word:"elicit",       meaning:"引き出す・誘発する",           etymology:"e（外へ）+ licit（誘う）",               prefix:"ex-", level:2},
  {word:"emulate",      meaning:"手本にする・競争する",          etymology:"emul（競う）+ ate",                    suffix:"-ate", level:2},
  {word:"exacerbate",   meaning:"悪化させる",                  etymology:"ex（強意）+ acerb（辛い）+ ate",         prefix:"ex-", level:2},
  {word:"fabricate",    meaning:"製作する・でっちあげる",        etymology:"fabric（工作）+ ate",                  suffix:"-ate", level:2},
  {word:"galvanize",    meaning:"刺激する・活性化する",          etymology:"galvan（電流）+ ize",                  suffix:"-ize", level:2},
  {word:"impede",       meaning:"妨げる・阻止する",             etymology:"im（中に）+ ped（足）+ e",               root:"-ped-", level:2},
  {word:"mitigate",     meaning:"緩和する・軽減する",           etymology:"miti（穏やか）+ g + ate",               suffix:"-ate", level:2},
  {word:"perpetuate",   meaning:"永続させる",                  etymology:"perpetu（永続的な）+ ate",              suffix:"-ate", level:2},
  {word:"repudiate",    meaning:"否定する・拒絶する",           etymology:"re（戻す）+ pudi（恥）+ ate",            prefix:"re-", level:3},

  ];

  if(!window.WORD_DATA_RAW) window.WORD_DATA_RAW=[];
  window.WORD_DATA_RAW=window.WORD_DATA_RAW.concat(d);
})();
