/**
 * data-root-1.js — 語根データ（-graph-, -port-, -ject-, -duct-, -spec-）
 * 形式: { word, meaning, etymology, root, level }
 * level: 0=beginner 1=intermediate 2=advanced 3=master
 */
(function(){
  var d = [
  // ── -graph-（書く・記録する） ──────────────────
  {word:"graph",         meaning:"グラフ・図",            etymology:"graph（書く）",                            root:"-graph-", level:0},
  {word:"graphic",       meaning:"図形の・視覚的な",      etymology:"graph（書く）+ ic（〜の）",                root:"-graph-", level:0},
  {word:"paragraph",     meaning:"段落",                  etymology:"para（傍らに）+ graph（書く）",            root:"-graph-", level:0},
  {word:"photograph",    meaning:"写真",                  etymology:"photo（光）+ graph（書く）",               root:"-graph-", level:0},
  {word:"geography",     meaning:"地理学",                etymology:"geo（大地）+ graphy（書く）",              root:"-graph-", level:0},
  {word:"biography",     meaning:"伝記",                  etymology:"bio（生命）+ graphy（書く）",              root:"-graph-", level:0},
  {word:"autograph",     meaning:"サイン・自署",          etymology:"auto（自分）+ graph（書く）",              root:"-graph-", level:0},
  {word:"telegram",      meaning:"電報",                  etymology:"tele（遠くの）+ gram（書く）",             root:"-graph-", level:1},
  {word:"diagram",       meaning:"図・ダイアグラム",      etymology:"dia（通じて）+ gram（書く）",              root:"-graph-", level:1},
  {word:"graphics",      meaning:"グラフィックス",        etymology:"graph（書く）+ ics（技術）",               root:"-graph-", level:0},
  {word:"typography",    meaning:"タイポグラフィ・活版印刷",etymology:"typo（活字）+ graphy（書く）",           root:"-graph-", level:2},
  {word:"calligraphy",   meaning:"習字・書道",            etymology:"calli（美しい）+ graphy（書く）",          root:"-graph-", level:2},
  {word:"cryptography",  meaning:"暗号学",                etymology:"crypto（隠れた）+ graphy（書く）",         root:"-graph-", level:2},
  {word:"choreography",  meaning:"振付",                  etymology:"choreo（踊り）+ graphy（書く）",           root:"-graph-", level:2},
  {word:"cardiography",  meaning:"心電図記録",            etymology:"cardio（心臓）+ graphy（書く）",           root:"-graph-", level:2},
  {word:"demographic",   meaning:"人口統計の",            etymology:"demo（人々）+ graphic（書く）",            root:"-graph-", level:2},
  {word:"ethnography",   meaning:"民族誌",                etymology:"ethno（民族）+ graphy（書く）",            root:"-graph-", level:2},
  {word:"holography",    meaning:"ホログラフィー",        etymology:"holo（全体）+ graphy（書く）",             root:"-graph-", level:2},
  {word:"lithography",   meaning:"石版印刷",              etymology:"litho（石）+ graphy（書く）",              root:"-graph-", level:2},
  {word:"oceanography",  meaning:"海洋学",                etymology:"oceano（海）+ graphy（書く）",             root:"-graph-", level:2},
  {word:"paleography",   meaning:"古文書学",              etymology:"paleo（古い）+ graphy（書く）",            root:"-graph-", level:3},
  {word:"polygraph",     meaning:"嘘発見器",              etymology:"poly（多くの）+ graph（書く）",            root:"-graph-", level:2},
  {word:"seismograph",   meaning:"地震計",                etymology:"seismo（地震）+ graph（書く）",            root:"-graph-", level:2},
  {word:"stenography",   meaning:"速記術",                etymology:"steno（狭い）+ graphy（書く）",            root:"-graph-", level:3},
  {word:"topography",    meaning:"地形学",                etymology:"topo（場所）+ graphy（書く）",             root:"-graph-", level:2},
  {word:"bibliography",  meaning:"参考文献・書誌",        etymology:"biblio（本）+ graphy（書く）",             root:"-graph-", level:2},
  {word:"cinematography",meaning:"映画撮影術",            etymology:"cinema（動き）+ tography（書く）",         root:"-graph-", level:2},
  {word:"pornography",   meaning:"ポルノグラフィー",      etymology:"porno（売春）+ graphy（書く）",            root:"-graph-", level:2},
  {word:"radiography",   meaning:"X線撮影",               etymology:"radio（放射線）+ graphy（書く）",          root:"-graph-", level:2},
  {word:"historiography",meaning:"歴史記述・史学史",      etymology:"historio（歴史）+ graphy（書く）",         root:"-graph-", level:3},

  // ── -port-（運ぶ・持ち帰る） ──────────────────
  {word:"port",          meaning:"港・ポート",            etymology:"port（運ぶ・港）",                         root:"-port-", level:0},
  {word:"transport",     meaning:"輸送する・交通機関",    etymology:"trans（横断して）+ port（運ぶ）",          root:"-port-", level:0},
  {word:"import",        meaning:"輸入する",              etymology:"im（中に）+ port（運ぶ）",                 root:"-port-", level:0},
  {word:"export",        meaning:"輸出する",              etymology:"ex（外に）+ port（運ぶ）",                 root:"-port-", level:0},
  {word:"report",        meaning:"報告する・レポート",    etymology:"re（再び）+ port（運ぶ）",                 root:"-port-", level:0},
  {word:"support",       meaning:"支援する・支持",        etymology:"sub（下から）+ port（運ぶ）",              root:"-port-", level:0},
  {word:"airport",       meaning:"空港",                  etymology:"air（空）+ port（港）",                    root:"-port-", level:0},
  {word:"portable",      meaning:"携帯できる",            etymology:"port（運ぶ）+ able（できる）",             root:"-port-", level:1},
  {word:"portfolio",     meaning:"ポートフォリオ",        etymology:"port（運ぶ）+ folio（葉）",                root:"-port-", level:1},
  {word:"passport",      meaning:"パスポート・旅券",      etymology:"pass（通る）+ port（港）",                 root:"-port-", level:0},
  {word:"deport",        meaning:"国外追放する",          etymology:"de（離れて）+ port（運ぶ）",               root:"-port-", level:2},
  {word:"reporter",      meaning:"記者・レポーター",      etymology:"re（再び）+ port（運ぶ）+ er（人）",        root:"-port-", level:0},
  {word:"transportation",meaning:"輸送・運送",            etymology:"trans（横断して）+ portation（運ぶ）",     root:"-port-", level:1},
  {word:"deportation",   meaning:"国外追放",              etymology:"de（離れて）+ portation（運ぶ）",          root:"-port-", level:2},
  {word:"portfolio management",meaning:"資産管理",        etymology:"port（運ぶ）+ folio（葉）+ management",    root:"-port-", level:2},
  {word:"portage",       meaning:"陸路運搬・運搬料",      etymology:"port（運ぶ）+ age（行為）",                root:"-port-", level:2},
  {word:"comportment",   meaning:"身のこなし・態度",      etymology:"com（共に）+ port（運ぶ）+ ment",          root:"-port-", level:3},
  {word:"important",     meaning:"重要な",                etymology:"im（中に）+ port（運ぶ）+ ant（〜している）",root:"-port-", level:0},
  {word:"opportune",     meaning:"好都合な・時機を得た",  etymology:"op（向かって）+ portune（港）",            root:"-port-", level:2},
  {word:"opportunity",   meaning:"機会・チャンス",        etymology:"op（向かって）+ portun（港）+ ity",        root:"-port-", level:0},

  // ── -ject-（投げる） ──────────────────────────
  {word:"project",       meaning:"プロジェクト・投影する",etymology:"pro（前に）+ ject（投げる）",              root:"-ject-", level:0},
  {word:"reject",        meaning:"拒絶する・却下する",    etymology:"re（後ろに）+ ject（投げる）",             root:"-ject-", level:0},
  {word:"inject",        meaning:"注射する・注入する",    etymology:"in（中に）+ ject（投げる）",               root:"-ject-", level:1},
  {word:"eject",         meaning:"排出する・立ち退かせる",etymology:"e（外に）+ ject（投げる）",                root:"-ject-", level:1},
  {word:"object",        meaning:"物体・反対する",        etymology:"ob（向かって）+ ject（投げる）",           root:"-ject-", level:0},
  {word:"subject",       meaning:"主語・科目・従わせる",  etymology:"sub（下に）+ ject（投げる）",              root:"-ject-", level:0},
  {word:"adjective",     meaning:"形容詞",                etymology:"ad（〜に）+ ject（投げる）+ ive",          root:"-ject-", level:1},
  {word:"dejected",      meaning:"落胆した",              etymology:"de（下に）+ ject（投げる）+ ed",           root:"-ject-", level:2},
  {word:"conjecture",    meaning:"推測・憶測",            etymology:"con（共に）+ ject（投げる）+ ure",         root:"-ject-", level:2},
  {word:"trajectory",    meaning:"弾道・軌跡",            etymology:"tra（横断して）+ ject（投げる）+ ory",     root:"-ject-", level:2},
  {word:"projection",    meaning:"投影・予測",            etymology:"pro（前に）+ ject（投げる）+ ion",         root:"-ject-", level:1},
  {word:"injection",     meaning:"注射・注入",            etymology:"in（中に）+ ject（投げる）+ ion",          root:"-ject-", level:1},
  {word:"ejection",      meaning:"排出・立ち退き",        etymology:"e（外に）+ ject（投げる）+ ion",           root:"-ject-", level:2},
  {word:"interjection",  meaning:"感嘆詞・叫び声",        etymology:"inter（間に）+ ject（投げる）+ ion",       root:"-ject-", level:2},
  {word:"subjection",    meaning:"服従・支配",            etymology:"sub（下に）+ ject（投げる）+ ion",         root:"-ject-", level:2},
  {word:"objection",     meaning:"反対・異議",            etymology:"ob（向かって）+ ject（投げる）+ ion",      root:"-ject-", level:1},
  {word:"rejection",     meaning:"拒絶・却下",            etymology:"re（後ろに）+ ject（投げる）+ ion",        root:"-ject-", level:1},
  {word:"subjective",    meaning:"主観的な",              etymology:"sub（下に）+ ject（投げる）+ ive",         root:"-ject-", level:1},
  {word:"objective",     meaning:"客観的な・目標",        etymology:"ob（向かって）+ ject（投げる）+ ive",      root:"-ject-", level:1},
  {word:"deject",        meaning:"落胆させる",            etymology:"de（下に）+ ject（投げる）",               root:"-ject-", level:2},
  {word:"abject",        meaning:"悲惨な・卑しい",        etymology:"ab（離れて）+ ject（投げる）",             root:"-ject-", level:3},

  // ── -duct-（導く・引く） ──────────────────────
  {word:"conduct",       meaning:"行う・指揮する",        etymology:"con（共に）+ duct（導く）",                root:"-duct-", level:1},
  {word:"produce",       meaning:"生産する",              etymology:"pro（前に）+ duce（導く）",                root:"-duct-", level:0},
  {word:"reduce",        meaning:"減らす",                etymology:"re（元に）+ duce（導く）",                 root:"-duct-", level:0},
  {word:"introduce",     meaning:"紹介する・導入する",    etymology:"intro（中に）+ duce（導く）",              root:"-duct-", level:0},
  {word:"educate",       meaning:"教育する",              etymology:"e（外に）+ duc（導く）+ ate",              root:"-duct-", level:0},
  {word:"deduct",        meaning:"差し引く・控除する",    etymology:"de（離れて）+ duct（導く）",               root:"-duct-", level:1},
  {word:"induct",        meaning:"就任させる・徴兵する",  etymology:"in（中に）+ duct（導く）",                 root:"-duct-", level:2},
  {word:"abduct",        meaning:"誘拐する",              etymology:"ab（離れて）+ duct（導く）",               root:"-duct-", level:2},
  {word:"seduction",     meaning:"誘惑",                  etymology:"se（離れて）+ duction（導く）",            root:"-duct-", level:2},
  {word:"aqueduct",      meaning:"水道橋",                etymology:"aque（水）+ duct（導く）",                 root:"-duct-", level:2},
  {word:"ductile",       meaning:"延性のある・従順な",    etymology:"duct（導く）+ ile（できる）",              root:"-duct-", level:2},
  {word:"production",    meaning:"生産",                  etymology:"pro（前に）+ duction（導く）",             root:"-duct-", level:0},
  {word:"reduction",     meaning:"減少・削減",            etymology:"re（元に）+ duction（導く）",              root:"-duct-", level:1},
  {word:"conduction",    meaning:"伝導・指揮",            etymology:"con（共に）+ duction（導く）",             root:"-duct-", level:2},
  {word:"deduction",     meaning:"差し引き・演繹",        etymology:"de（離れて）+ duction（導く）",            root:"-duct-", level:2},
  {word:"induction",     meaning:"帰納・就任",            etymology:"in（中に）+ duction（導く）",              root:"-duct-", level:2},
  {word:"abduction",     meaning:"誘拐・外転",            etymology:"ab（離れて）+ duction（導く）",            root:"-duct-", level:2},
  {word:"transduction",  meaning:"形質導入",              etymology:"trans（横断して）+ duction（導く）",       root:"-duct-", level:3},
  {word:"eduction",      meaning:"導出・抽出",            etymology:"e（外に）+ duction（導く）",               root:"-duct-", level:3},
  {word:"seduct",        meaning:"誘惑する",              etymology:"se（離れて）+ duct（導く）",               root:"-duct-", level:2},

  // ── -spec-（見る・観察する） ──────────────────
  {word:"special",       meaning:"特別な",                etymology:"spec（見る）+ ial（〜の）",                root:"-spec-", level:0},
  {word:"spectacle",     meaning:"光景・眼鏡",            etymology:"spec（見る）+ tacle（道具）",              root:"-spec-", level:1},
  {word:"inspect",       meaning:"検査する・調べる",      etymology:"in（中に）+ spect（見る）",                root:"-spec-", level:1},
  {word:"expect",        meaning:"期待する",              etymology:"ex（外に）+ pect（見る）",                 root:"-spec-", level:0},
  {word:"respect",       meaning:"尊敬する・尊重",        etymology:"re（再び）+ spect（見る）",                root:"-spec-", level:0},
  {word:"suspect",       meaning:"疑う・容疑者",          etymology:"sub（下に）+ spect（見る）",               root:"-spec-", level:1},
  {word:"prospect",      meaning:"見通し・可能性",        etymology:"pro（前に）+ spect（見る）",               root:"-spec-", level:1},
  {word:"spectator",     meaning:"観客・観察者",          etymology:"spec（見る）+ tator（〜する人）",          root:"-spec-", level:1},
  {word:"spectacular",   meaning:"壮観な・印象的な",      etymology:"spec（見る）+ tacular（〜に満ちた）",      root:"-spec-", level:1},
  {word:"perspective",   meaning:"観点・遠近法",          etymology:"per（完全に）+ spec（見る）+ tive",        root:"-spec-", level:2},
  {word:"species",       meaning:"種・種類",              etymology:"spec（見る・種類）+ ies",                  root:"-spec-", level:1},
  {word:"specific",      meaning:"特定の・具体的な",      etymology:"spec（見る）+ ific（〜にする）",           root:"-spec-", level:1},
  {word:"specimen",      meaning:"標本・見本",            etymology:"spec（見る）+ imen（小さい）",             root:"-spec-", level:1},
  {word:"spectrum",      meaning:"スペクトル・範囲",      etymology:"spec（見る）+ trum（器具）",               root:"-spec-", level:2},
  {word:"speculation",   meaning:"推測・投機",            etymology:"spec（見る）+ ulation（行為）",            root:"-spec-", level:2},
  {word:"introspection", meaning:"内省・自己観察",        etymology:"intro（中に）+ spection（見る）",          root:"-spec-", level:2},
  {word:"circumspect",   meaning:"慎重な",                etymology:"circum（周囲に）+ spect（見る）",          root:"-spec-", level:2},
  {word:"conspicuous",   meaning:"目立つ・顕著な",        etymology:"con（共に）+ spic（見る）+ uous",          root:"-spec-", level:2},
  {word:"despise",       meaning:"軽蔑する",              etymology:"de（下に）+ spise（見る）",                root:"-spec-", level:2},
  {word:"auspicious",    meaning:"縁起の良い・幸先の良い",etymology:"au（鳥）+ spec（見る）+ ious",            root:"-spec-", level:2},
  {word:"perspicacious", meaning:"洞察力のある",          etymology:"per（完全に）+ spic（見る）+ acious",      root:"-spec-", level:3},
  {word:"inauspicious",  meaning:"不吉な・縁起の悪い",    etymology:"in（否定）+ au（鳥）+ spec（見る）",       root:"-spec-", level:3},
  ];

  if(!window.WORD_DATA_RAW) window.WORD_DATA_RAW=[];
  window.WORD_DATA_RAW=window.WORD_DATA_RAW.concat(d);
})();
