/**
 * examples.js — 単語の用例データ（手動作成・高品質）
 * window.WORD_EXAMPLES に { word: { example, exampleJa } } の形式で格納
 * data.js の _buildIndex() でマージされる
 * ※ generated ファイルより後にロードされ、Object.assign で手動分が優先される
 */
(function(){
  var e = window.WORD_EXAMPLES = window.WORD_EXAMPLES || {};
  Object.assign(e, {
    // ── pre- ─────────────────────────────────────────
    "preview":      { example: "Let me preview the document before sending it.", exampleJa: "送信する前にドキュメントをプレビューさせてください。" },
    "prepare":      { example: "We need to prepare for the big presentation.", exampleJa: "大きなプレゼンの準備をしなければなりません。" },
    "predict":      { example: "Scientists predict that temperatures will rise.", exampleJa: "科学者たちは気温が上昇すると予測しています。" },
    "prevent":      { example: "Regular exercise can prevent many diseases.", exampleJa: "定期的な運動は多くの病気を予防できます。" },
    "preface":      { example: "The author wrote a short preface to the book.", exampleJa: "著者は本に短い序文を書きました。" },
    "precaution":   { example: "Take precautions when working with chemicals.", exampleJa: "化学物質を扱うときは予防措置を取ってください。" },
    "preliminary":  { example: "The preliminary results look very promising.", exampleJa: "予備的な結果は非常に有望に見えます。" },
    "prerequisite": { example: "Math is a prerequisite for this engineering course.", exampleJa: "数学はこのエンジニアリングコースの前提条件です。" },
    "precede":      { example: "A short introduction precedes the main speech.", exampleJa: "短い紹介が本スピーチの前に行われます。" },
    "preserve":     { example: "We must preserve the natural environment.", exampleJa: "私たちは自然環境を保護しなければなりません。" },

    // ── un- ──────────────────────────────────────────
    "undo":         { example: "You can undo your last action by pressing Ctrl+Z.", exampleJa: "Ctrl+Zを押すと最後の操作を元に戻せます。" },
    "unlock":       { example: "She used her phone to unlock the front door.", exampleJa: "彼女はスマホを使って玄関のドアを解錠しました。" },
    "unusual":      { example: "It is unusual to see snow in this city.", exampleJa: "この街で雪が降るのは珍しいことです。" },
    "unfair":       { example: "The students thought the exam was unfair.", exampleJa: "生徒たちはそのテストは不公平だと思いました。" },
    "unknown":      { example: "The author of this painting is unknown.", exampleJa: "この絵の作者は不明です。" },
    "uncover":      { example: "Detectives worked to uncover the truth.", exampleJa: "探偵たちは真実を明らかにするために働きました。" },
    "unlikely":     { example: "It is unlikely that he will arrive on time.", exampleJa: "彼が時間通りに到着する可能性は低いです。" },
    "uncomfortable":{ example: "The long flight made everyone uncomfortable.", exampleJa: "長いフライトで全員が不快になりました。" },
    "unforgettable":{ example: "The trip to Paris was truly unforgettable.", exampleJa: "パリへの旅行は本当に忘れられないものでした。" },
    "uncertain":    { example: "The future of the project is uncertain.", exampleJa: "そのプロジェクトの将来は不確かです。" },

    // ── re- ──────────────────────────────────────────
    "return":       { example: "Please return the book to the library.", exampleJa: "図書館に本を返却してください。" },
    "review":       { example: "She reviewed her notes before the exam.", exampleJa: "彼女は試験前にノートを復習しました。" },
    "rebuild":      { example: "The town was rebuilt after the earthquake.", exampleJa: "地震の後、その町は再建されました。" },
    "remind":       { example: "Can you remind me to call her tomorrow?", exampleJa: "明日彼女に電話するよう思い出させてもらえますか？" },
    "replace":      { example: "We need to replace the old battery.", exampleJa: "古いバッテリーを交換する必要があります。" },
    "reflect":      { example: "The lake reflects the mountains perfectly.", exampleJa: "湖は山々を完璧に映し出しています。" },
    "reform":       { example: "The government plans to reform the tax system.", exampleJa: "政府は税制を改革する計画を立てています。" },
    "restore":      { example: "Experts restored the ancient painting carefully.", exampleJa: "専門家たちは古い絵を丁寧に修復しました。" },
    "recycle":      { example: "It is important to recycle paper and plastic.", exampleJa: "紙やプラスチックをリサイクルすることは大切です。" },
    "reconsider":   { example: "Please reconsider your decision before acting.", exampleJa: "行動する前に決断を再考してください。" },

    // ── dis- ─────────────────────────────────────────
    "discover":     { example: "Columbus discovered America in 1492.", exampleJa: "コロンブスは1492年にアメリカを発見しました。" },
    "disagree":     { example: "The two experts disagree on the cause.", exampleJa: "2人の専門家は原因について意見が合いません。" },
    "disappear":    { example: "The fog slowly disappeared in the morning sun.", exampleJa: "霧は朝の日差しの中でゆっくりと消えていきました。" },
    "disappoint":   { example: "I hate to disappoint you with bad news.", exampleJa: "悪い知らせであなたをがっかりさせたくありません。" },
    "disconnect":   { example: "Please disconnect the power before repairs.", exampleJa: "修理の前に電源を切ってください。" },
    "disorder":     { example: "The room was in complete disorder.", exampleJa: "部屋はひどく散らかっていました。" },
    "distrust":     { example: "There is growing distrust in the media.", exampleJa: "メディアへの不信感が高まっています。" },
    "distance":     { example: "The distance between the two cities is 300 km.", exampleJa: "2つの都市間の距離は300キロメートルです。" },

    // ── mis- ─────────────────────────────────────────
    "mistake":      { example: "Everyone makes mistakes when learning.", exampleJa: "学ぶときには誰もがミスをします。" },
    "mislead":      { example: "The advertisement misled customers about prices.", exampleJa: "その広告は顧客を価格について誤解させました。" },
    "misunderstand":{ example: "I think you misunderstood my question.", exampleJa: "私の質問を誤解されたと思います。" },
    "misplace":     { example: "I always misplace my keys.", exampleJa: "いつも鍵をなくしてしまいます。" },

    // ── over- ────────────────────────────────────────
    "overcome":     { example: "She overcame her fear of public speaking.", exampleJa: "彼女は人前で話すことへの恐怖を克服しました。" },
    "overlook":     { example: "Don't overlook the small details.", exampleJa: "細かいことを見落とさないようにしてください。" },
    "overall":      { example: "Overall, the project was a great success.", exampleJa: "全体的に、そのプロジェクトは大きな成功でした。" },
    "overwork":     { example: "You shouldn't overwork yourself every day.", exampleJa: "毎日自分を酷使すべきではありません。" },
    "overseas":     { example: "She studied overseas for two years.", exampleJa: "彼女は2年間海外で勉強しました。" },

    // ── under- ───────────────────────────────────────
    "understand":   { example: "Do you understand the instructions?", exampleJa: "説明を理解していますか？" },
    "undergo":      { example: "The patient had to undergo surgery.", exampleJa: "患者は手術を受けなければなりませんでした。" },
    "underestimate":{ example: "Never underestimate the power of kindness.", exampleJa: "親切の力を決して過小評価してはいけません。" },
    "undertake":    { example: "He undertook the difficult challenge alone.", exampleJa: "彼は一人でその困難な挑戦に取り組みました。" },
    "undermine":    { example: "The scandal undermined public trust.", exampleJa: "そのスキャンダルは公の信頼を損ないました。" },

    // ── sub- / super- ────────────────────────────────
    "submit":       { example: "Please submit your report by Friday.", exampleJa: "金曜日までにレポートを提出してください。" },
    "subscribe":    { example: "I subscribe to several newsletters.", exampleJa: "いくつかのニュースレターを購読しています。" },
    "substitute":   { example: "You can substitute honey for sugar.", exampleJa: "砂糖の代わりにはちみつを使えます。" },
    "supervise":    { example: "A teacher must supervise students during exams.", exampleJa: "試験中、先生は生徒を監督しなければなりません。" },
    "surpass":      { example: "The results surpassed all expectations.", exampleJa: "結果はすべての期待を上回りました。" },
    "suspect":      { example: "Police suspect him of the crime.", exampleJa: "警察は彼を犯罪の容疑者として疑っています。" },

    // ── out- ─────────────────────────────────────────
    "outcome":      { example: "The outcome of the election surprised everyone.", exampleJa: "選挙の結果は全員を驚かせました。" },
    "outline":      { example: "Please prepare an outline for your essay.", exampleJa: "エッセイのアウトラインを準備してください。" },
    "outstanding":  { example: "She did an outstanding job on the project.", exampleJa: "彼女はそのプロジェクトで素晴らしい仕事をしました。" },
    "outperform":   { example: "Our team consistently outperforms competitors.", exampleJa: "私たちのチームは競合他社を一貫して上回っています。" },

    // ── -tion/-sion ──────────────────────────────────
    "action":       { example: "Quick action saved the child's life.", exampleJa: "迅速な行動が子供の命を救いました。" },
    "solution":     { example: "We found a solution to the problem.", exampleJa: "私たちは問題の解決策を見つけました。" },
    "information":  { example: "Please provide your contact information.", exampleJa: "連絡先情報をご提供ください。" },
    "direction":    { example: "Can you give me directions to the station?", exampleJa: "駅への道を教えてもらえますか？" },
    "connection":   { example: "There is a strong connection between diet and health.", exampleJa: "食事と健康には強い関連があります。" },
    "production":   { example: "The factory increased its production this year.", exampleJa: "工場は今年生産量を増やしました。" },
    "education":    { example: "Education is the key to a better future.", exampleJa: "教育はより良い未来への鍵です。" },
    "translation":  { example: "The translation of the novel took two years.", exampleJa: "その小説の翻訳には2年かかりました。" },

    // ── -ment ────────────────────────────────────────
    "agreement":    { example: "Both parties signed the agreement.", exampleJa: "両者は合意書に署名しました。" },
    "movement":     { example: "The movement for equality grew stronger.", exampleJa: "平等を求める運動はより強くなりました。" },
    "development":  { example: "Technology development is moving very fast.", exampleJa: "技術の発展は非常に速く進んでいます。" },
    "environment":  { example: "We should protect our environment.", exampleJa: "私たちは環境を守るべきです。" },
    "improvement":  { example: "I noticed a great improvement in your skills.", exampleJa: "あなたのスキルが大きく向上していることに気づきました。" },
    "management":   { example: "Good management is key to business success.", exampleJa: "良い管理はビジネスの成功への鍵です。" },
    "treatment":    { example: "The doctor recommended a new treatment.", exampleJa: "医師は新しい治療法を勧めました。" },
    "achievement":  { example: "Graduating was her greatest achievement.", exampleJa: "卒業は彼女の最大の達成でした。" },

    // ── -ness ────────────────────────────────────────
    "happiness":    { example: "Money alone cannot buy happiness.", exampleJa: "お金だけでは幸せを買うことはできません。" },
    "kindness":     { example: "A small act of kindness can change someone's day.", exampleJa: "小さな親切が誰かの一日を変えることがあります。" },
    "awareness":    { example: "Raising awareness about climate change is important.", exampleJa: "気候変動への意識を高めることが重要です。" },
    "darkness":     { example: "She was afraid of the darkness.", exampleJa: "彼女は暗闇を怖れていました。" },
    "weakness":     { example: "Admitting weakness takes courage.", exampleJa: "弱さを認めることには勇気が要ります。" },
    "fitness":      { example: "Regular exercise improves your overall fitness.", exampleJa: "定期的な運動は全体的な体力を向上させます。" },

    // ── -able/-ible ──────────────────────────────────
    "capable":      { example: "She is capable of solving complex problems.", exampleJa: "彼女は複雑な問題を解決できます。" },
    "comfortable":  { example: "The hotel room was clean and comfortable.", exampleJa: "ホテルの部屋は清潔で快適でした。" },
    "reliable":     { example: "He is a reliable person you can always count on.", exampleJa: "彼はいつでも頼れる信頼できる人です。" },
    "available":    { example: "Are you available for a meeting on Monday?", exampleJa: "月曜日に会議の時間はありますか？" },
    "flexible":     { example: "Our schedule is flexible, so we can adjust.", exampleJa: "スケジュールは柔軟なので調整できます。" },
    "responsible":  { example: "Parents are responsible for their children.", exampleJa: "親は子供に責任を持っています。" },
    "memorable":    { example: "It was the most memorable day of my life.", exampleJa: "それは私の人生で最も忘れられない日でした。" },
    "reasonable":   { example: "The price seemed very reasonable.", exampleJa: "価格はとても手頃に思えました。" },

    // ── -ful ─────────────────────────────────────────
    "helpful":      { example: "The staff were very helpful during our visit.", exampleJa: "スタッフは訪問中とても親切でした。" },
    "beautiful":    { example: "The sunset over the ocean was beautiful.", exampleJa: "海に沈む夕日は美しかったです。" },
    "powerful":     { example: "She gave a powerful speech at the conference.", exampleJa: "彼女は会議で力強いスピーチをしました。" },
    "successful":   { example: "The campaign was very successful.", exampleJa: "そのキャンペーンはとても成功しました。" },
    "grateful":     { example: "I am grateful for your support.", exampleJa: "あなたのご支援に感謝しています。" },
    "careful":      { example: "Be careful when crossing the street.", exampleJa: "道を渡るときは気をつけてください。" },
    "peaceful":     { example: "The countryside is quiet and peaceful.", exampleJa: "田舎は静かで穏やかです。" },

    // ── -less ────────────────────────────────────────
    "helpless":     { example: "The lost child looked helpless and scared.", exampleJa: "迷子の子供は無力そうで怖がっていました。" },
    "careless":     { example: "That careless mistake cost us the contract.", exampleJa: "そのうっかりミスで契約を失いました。" },
    "hopeless":     { example: "The situation seemed hopeless at first.", exampleJa: "最初は状況が絶望的に見えました。" },
    "endless":      { example: "The debate seemed to go on in endless circles.", exampleJa: "議論は永遠に繰り返されているようでした。" },
    "harmless":     { example: "The snake is completely harmless to humans.", exampleJa: "そのヘビは人間にとって全くの無害です。" },
    "speechless":   { example: "She was speechless when she heard the news.", exampleJa: "そのニュースを聞いて彼女は言葉を失いました。" },
    "priceless":    { example: "The old painting is considered priceless.", exampleJa: "その古い絵画は値がつけられないほど貴重とされています。" },

    // ── -ous ─────────────────────────────────────────
    "famous":       { example: "Paris is famous for its cuisine and art.", exampleJa: "パリは料理と芸術で有名です。" },
    "dangerous":    { example: "Driving too fast is very dangerous.", exampleJa: "スピードの出しすぎはとても危険です。" },
    "nervous":      { example: "I was nervous before my job interview.", exampleJa: "就職面接の前に緊張しました。" },
    "generous":     { example: "She was generous enough to donate her time.", exampleJa: "彼女は時間を寄付するほど寛大でした。" },
    "curious":      { example: "Children are naturally curious about the world.", exampleJa: "子供たちは生まれつき世界に対して好奇心旺盛です。" },
    "serious":      { example: "This is a serious matter that needs attention.", exampleJa: "これは注意が必要な深刻な問題です。" },
    "ambitious":    { example: "He has ambitious plans for his company.", exampleJa: "彼は会社に対して野心的な計画を持っています。" },
    "numerous":     { example: "There are numerous reasons to study English.", exampleJa: "英語を学ぶ理由は数多くあります。" },

    // ── -ive ─────────────────────────────────────────
    "active":       { example: "She leads a very active lifestyle.", exampleJa: "彼女はとても活発なライフスタイルを送っています。" },
    "creative":     { example: "The marketing team came up with a creative idea.", exampleJa: "マーケティングチームが独創的なアイデアを考えました。" },
    "effective":    { example: "This method is very effective for learning.", exampleJa: "この方法は学習にとても効果的です。" },
    "positive":     { example: "Try to maintain a positive attitude.", exampleJa: "ポジティブな姿勢を維持するよう努めてください。" },
    "attractive":   { example: "The city center is very attractive to tourists.", exampleJa: "市の中心部は観光客にとても魅力的です。" },
    "sensitive":    { example: "Be sensitive to other people's feelings.", exampleJa: "他の人の気持ちに敏感になってください。" },
    "productive":   { example: "Working in the morning is most productive for me.", exampleJa: "私には午前中が最も生産的に働ける時間です。" },
    "competitive":  { example: "The job market is extremely competitive.", exampleJa: "就職市場は非常に競争が激しいです。" },

    // ── -al ──────────────────────────────────────────
    "natural":      { example: "Use natural ingredients whenever possible.", exampleJa: "できるだけ天然の材料を使ってください。" },
    "personal":     { example: "This is a personal decision only you can make.", exampleJa: "これはあなただけが決められる個人的な決断です。" },
    "practical":    { example: "We need a practical solution, not theory.", exampleJa: "理論ではなく実用的な解決策が必要です。" },
    "original":     { example: "The artist created something truly original.", exampleJa: "アーティストは本当にオリジナルなものを作りました。" },
    "emotional":    { example: "It was an emotional farewell at the airport.", exampleJa: "空港での別れは感情的なものでした。" },

    // ── -ly ──────────────────────────────────────────
    "suddenly":     { example: "She suddenly stopped and turned around.", exampleJa: "彼女は突然立ち止まり、振り返りました。" },
    "clearly":      { example: "Please speak more clearly so I can understand.", exampleJa: "理解できるようにもっとはっきり話してください。" },
    "recently":     { example: "I recently moved to a new apartment.", exampleJa: "最近新しいアパートに引っ越しました。" },
    "directly":     { example: "Please contact me directly if you have questions.", exampleJa: "質問があれば直接ご連絡ください。" },
    "quickly":      { example: "She quickly finished the task.", exampleJa: "彼女は素早くその作業を終えました。" },
    "strongly":     { example: "I strongly recommend reading this book.", exampleJa: "この本を強くお勧めします。" },

    // ── -er/-or ──────────────────────────────────────
    "teacher":      { example: "The teacher explained the lesson patiently.", exampleJa: "先生は辛抱強く授業を説明しました。" },
    "director":     { example: "The director guided the film to success.", exampleJa: "監督は映画を成功へと導きました。" },
    "supervisor":   { example: "My supervisor gave me useful feedback.", exampleJa: "上司から有益なフィードバックをもらいました。" },
    "inventor":     { example: "The inventor patented his new device.", exampleJa: "発明家は新しい装置の特許を取得しました。" },
    "translator":   { example: "A skilled translator preserves the original tone.", exampleJa: "熟練の翻訳者は原文のトーンを保ちます。" },

    // ── -ist ─────────────────────────────────────────
    "specialist":   { example: "You should see a specialist for that condition.", exampleJa: "その症状については専門医に診てもらうべきです。" },
    "journalist":   { example: "The journalist investigated the story for months.", exampleJa: "ジャーナリストは何ヶ月もかけてその話を調査しました。" },
    "scientist":    { example: "The scientist published her findings last week.", exampleJa: "科学者は先週研究成果を発表しました。" },

    // ── -ize ─────────────────────────────────────────
    "organize":     { example: "She organized the files into clear folders.", exampleJa: "彼女はファイルを分かりやすいフォルダに整理しました。" },
    "recognize":    { example: "I recognized her from across the room.", exampleJa: "部屋の向こうから彼女だとわかりました。" },
    "realize":      { example: "I suddenly realized I had left my bag on the train.", exampleJa: "電車にバッグを置いてきたことに突然気づきました。" },
    "modernize":    { example: "The company plans to modernize its systems.", exampleJa: "会社はシステムの近代化を計画しています。" },
    "summarize":    { example: "Can you summarize the main points?", exampleJa: "主要なポイントをまとめてもらえますか？" },

    // ── -graph- ──────────────────────────────────────
    "photograph":   { example: "She took a photograph of the beautiful sunset.", exampleJa: "彼女は美しい夕日の写真を撮りました。" },
    "paragraph":    { example: "Each paragraph should focus on one main idea.", exampleJa: "各段落は一つの主要なアイデアに焦点を当てるべきです。" },
    "biography":    { example: "I am reading a biography of Abraham Lincoln.", exampleJa: "エイブラハム・リンカーンの伝記を読んでいます。" },
    "geography":    { example: "Geography helps us understand the world around us.", exampleJa: "地理学は私たちの周りの世界を理解するのに役立ちます。" },
    "autograph":    { example: "He asked the singer for her autograph.", exampleJa: "彼は歌手にサインを求めました。" },

    // ── -port- ───────────────────────────────────────
    "transport":    { example: "Public transport in Tokyo is excellent.", exampleJa: "東京の公共交通機関は優秀です。" },
    "export":       { example: "Japan exports cars to many countries.", exampleJa: "日本は多くの国に車を輸出しています。" },
    "import":       { example: "We import coffee beans from Colombia.", exampleJa: "私たちはコロンビアからコーヒー豆を輸入しています。" },
    "support":      { example: "Thank you for your continuous support.", exampleJa: "継続的なご支援に感謝します。" },
    "report":       { example: "Please submit a report by the end of the week.", exampleJa: "週末までにレポートを提出してください。" },
    "portable":     { example: "A portable charger is very useful while traveling.", exampleJa: "旅行中、携帯型充電器はとても便利です。" },

    // ── -ject- ───────────────────────────────────────
    "project":      { example: "Our team just finished an important project.", exampleJa: "私たちのチームは重要なプロジェクトを終えました。" },
    "reject":       { example: "The company rejected his job application.", exampleJa: "会社は彼の求人応募を却下しました。" },
    "subject":      { example: "My favorite subject at school was history.", exampleJa: "学校で一番好きな科目は歴史でした。" },
    "object":       { example: "She objects to working on weekends.", exampleJa: "彼女は週末の仕事に反対しています。" },

    // ── -duct- ───────────────────────────────────────
    "produce":      { example: "This factory produces over 1,000 cars a day.", exampleJa: "この工場は1日1,000台以上の車を生産します。" },
    "conduct":      { example: "The orchestra conductor led a brilliant performance.", exampleJa: "オーケストラの指揮者が素晴らしい演奏を指揮しました。" },
    "reduce":       { example: "We should reduce our use of plastic.", exampleJa: "プラスチックの使用を減らすべきです。" },
    "introduce":    { example: "Let me introduce you to my colleague.", exampleJa: "私の同僚を紹介させてください。" },
    "educate":      { example: "We must educate children about the environment.", exampleJa: "子供たちに環境について教育しなければなりません。" },

    // ── -spec- ───────────────────────────────────────
    "inspect":      { example: "The engineer inspected the bridge for damage.", exampleJa: "エンジニアは橋の損傷を点検しました。" },
    "respect":      { example: "We should respect people from all cultures.", exampleJa: "あらゆる文化の人々を尊重すべきです。" },
    "expect":       { example: "I expect the report to be ready by Monday.", exampleJa: "月曜日までにレポートが準備できると思っています。" },

    // ── -vis- ────────────────────────────────────────
    "vision":       { example: "The company has a clear vision for the future.", exampleJa: "会社には将来に向けた明確なビジョンがあります。" },
    "visible":      { example: "The stars were clearly visible on that night.", exampleJa: "その夜、星がはっきりと見えました。" },
    "revise":       { example: "Please revise your essay and resubmit it.", exampleJa: "エッセイを修正して再提出してください。" },

    // ── -vert- ───────────────────────────────────────
    "convert":      { example: "We converted the spare room into an office.", exampleJa: "空き部屋をオフィスに改造しました。" },
    "advertise":    { example: "The company spent a lot on advertising.", exampleJa: "会社は広告に多くのお金を使いました。" },
    "divert":       { example: "Traffic was diverted due to road work.", exampleJa: "道路工事のため交通が迂回されました。" },

    // ── -struct- ─────────────────────────────────────
    "construct":    { example: "Workers constructed the bridge in six months.", exampleJa: "作業員たちは6ヶ月で橋を建設しました。" },
    "instruct":     { example: "The manual instructs you to read carefully.", exampleJa: "マニュアルは注意深く読むよう指示しています。" },
    "structure":    { example: "The structure of the sentence is very complex.", exampleJa: "その文の構造は非常に複雑です。" },

    // ── -dict- ───────────────────────────────────────
    "contradict":   { example: "His actions contradict his words.", exampleJa: "彼の行動は言葉と矛盾しています。" },

    // ── -tract- ──────────────────────────────────────
    "attract":      { example: "Flowers attract bees with their scent.", exampleJa: "花は香りで蜂を引きつけます。" },
    "contract":     { example: "Both sides signed the contract.", exampleJa: "両者が契約書に署名しました。" },
    "subtract":     { example: "Subtract 10 from 30 to get 20.", exampleJa: "30から10を引くと20になります。" },
    "extract":      { example: "The dentist had to extract the broken tooth.", exampleJa: "歯科医は欠けた歯を抜く必要がありました。" },

    // ── -mot- ────────────────────────────────────────
    "promote":      { example: "She was promoted to senior manager.", exampleJa: "彼女はシニアマネージャーに昇進しました。" },
    "motivate":     { example: "A good leader knows how to motivate their team.", exampleJa: "優れたリーダーはチームをやる気にさせる方法を知っています。" },
    "emotion":      { example: "The film was full of strong emotions.", exampleJa: "その映画は強い感情に満ちていました。" },

    // ── co- / inter- / trans- ────────────────────────
    "cooperate":    { example: "We need to cooperate to finish on time.", exampleJa: "時間通りに終わらせるためには協力が必要です。" },
    "interact":     { example: "Children learn by interacting with others.", exampleJa: "子供たちは他の人と交流することで学びます。" },
    "transfer":     { example: "She transferred to a school in another city.", exampleJa: "彼女は別の街の学校に転校しました。" },
    "transform":    { example: "The renovation transformed the old house.", exampleJa: "改装で古い家が様変わりしました。" },
    "international":{ example: "She works for an international company.", exampleJa: "彼女は国際的な企業で働いています。" },

    // ── level-0 verbs ────────────────────────────────
    "prefer":       { example: "I prefer tea to coffee in the morning.", exampleJa: "私は朝はコーヒーよりお茶の方が好きです。" },
    "repeat":       { example: "Could you please repeat that? I didn't catch it.", exampleJa: "もう一度言ってもらえますか？聞き取れませんでした。" },
    "recall":       { example: "I can't recall where I put my glasses.", exampleJa: "眼鏡をどこに置いたか思い出せません。" },
    "believe":      { example: "I believe that hard work always pays off.", exampleJa: "努力は必ず報われると信じています。" },
    "forget":       { example: "Don't forget to bring your passport.", exampleJa: "パスポートを持ってくることを忘れないでください。" },
    "forgive":      { example: "It takes strength to forgive someone who hurt you.", exampleJa: "あなたを傷つけた人を許すには強さが必要です。" },
    "combine":      { example: "Combine the flour and sugar in a large bowl.", exampleJa: "大きなボウルに小麦粉と砂糖を合わせてください。" },
    "communicate":  { example: "It is important to communicate clearly with your team.", exampleJa: "チームと明確にコミュニケーションを取ることが大切です。" },
    "compare":      { example: "Let me compare the two options before deciding.", exampleJa: "決める前に2つの選択肢を比較させてください。" },
    "compete":      { example: "Athletes from 50 countries will compete in the games.", exampleJa: "50か国の選手たちがその大会で競います。" },
    "connect":      { example: "This cable connects your computer to the printer.", exampleJa: "このケーブルはコンピューターとプリンターをつなぎます。" },
    "decide":       { example: "Have you decided what to study at university?", exampleJa: "大学で何を学ぶか決めましたか？" },
    "describe":     { example: "Can you describe what the thief looked like?", exampleJa: "泥棒がどんな外見だったか説明できますか？" },
    "destroy":      { example: "The fire destroyed the entire building.", exampleJa: "火事で建物全体が壊されました。" },
    "enable":       { example: "This app enables you to learn anytime, anywhere.", exampleJa: "このアプリはいつでもどこでも学べるようにしてくれます。" },
    "enjoy":        { example: "We enjoyed the concert very much.", exampleJa: "私たちはコンサートをとても楽しみました。" },
    "encourage":    { example: "My teacher always encouraged me to keep trying.", exampleJa: "先生はいつも挑戦し続けるよう励ましてくれました。" },
    "explain":      { example: "The professor explained the theory in simple terms.", exampleJa: "教授は理論をわかりやすい言葉で説明しました。" },
    "express":      { example: "Art is a great way to express your feelings.", exampleJa: "芸術は感情を表現する素晴らしい方法です。" },
    "forecast":     { example: "The forecast says it will rain all weekend.", exampleJa: "予報では週末ずっと雨が降るとのことです。" },
    "identify":     { example: "Scientists have identified a new species of fish.", exampleJa: "科学者たちは新種の魚を確認しました。" },
    "improve":      { example: "Reading every day will improve your vocabulary.", exampleJa: "毎日読書すると語彙力が上がります。" },
    "involve":      { example: "The project involves a lot of team effort.", exampleJa: "そのプロジェクトは多くのチームの努力を必要とします。" },
    "join":         { example: "Would you like to join us for dinner tonight?", exampleJa: "今夜一緒に夕食を食べませんか？" },
    "operate":      { example: "He has operated this machine for ten years.", exampleJa: "彼は10年間この機械を操作しています。" },
    "pass":         { example: "She passed the driving test on her first try.", exampleJa: "彼女は一発で運転免許試験に合格しました。" },
    "protect":      { example: "Wear sunscreen to protect your skin from UV rays.", exampleJa: "紫外線から肌を守るために日焼け止めを塗ってください。" },
    "provide":      { example: "The hotel provides free Wi-Fi for all guests.", exampleJa: "ホテルは全宿泊客に無料Wi-Fiを提供しています。" },
    "receive":      { example: "She received a scholarship to study abroad.", exampleJa: "彼女は留学のための奨学金を受け取りました。" },
    "select":       { example: "Please select your preferred seat on the map.", exampleJa: "地図上でご希望の席を選んでください。" },
    "serve":        { example: "This restaurant serves breakfast from 7 a.m.", exampleJa: "このレストランは朝7時から朝食を提供しています。" },
    "spend":        { example: "He spends about an hour commuting each day.", exampleJa: "彼は毎日約1時間通勤に費やしています。" },
    "succeed":      { example: "You will succeed if you keep practicing.", exampleJa: "練習し続ければ成功できます。" },
    "visit":        { example: "I plan to visit Kyoto next spring.", exampleJa: "来年の春に京都を訪れる予定です。" },
    "achieve":      { example: "She achieved her goal of running a marathon.", exampleJa: "彼女はマラソンを完走するという目標を達成しました。" },
    "affect":       { example: "The weather can greatly affect your mood.", exampleJa: "天気は気分に大きく影響することがあります。" },
    "create":       { example: "She created a beautiful painting for the exhibition.", exampleJa: "彼女は展覧会のために美しい絵画を制作しました。" },
    "develop":      { example: "The company is developing a new product.", exampleJa: "会社は新しい製品を開発しています。" },
    "focus":        { example: "Try to focus on one task at a time.", exampleJa: "一度に一つのタスクに集中するようにしてください。" },
    "prove":        { example: "The experiment proved the scientist's theory.", exampleJa: "実験で科学者の理論が証明されました。" },
    "postpone":     { example: "We had to postpone the meeting due to rain.", exampleJa: "雨のため会議を延期しなければなりませんでした。" },
    "admit":        { example: "He admitted that he had made a mistake.", exampleJa: "彼は間違いを犯したことを認めました。" },
    "advance":      { example: "Technology has advanced rapidly in recent years.", exampleJa: "近年、技術は急速に進歩しています。" },
    "collect":      { example: "He collects vintage stamps from around the world.", exampleJa: "彼は世界中のヴィンテージ切手を集めています。" },
    "accept":       { example: "She gracefully accepted the award on stage.", exampleJa: "彼女はステージで優雅に賞を受け取りました。" },
    "behave":       { example: "Please behave properly in public places.", exampleJa: "公共の場では礼儀正しく振る舞ってください。" },
    "occur":        { example: "The accident occurred at the intersection.", exampleJa: "事故は交差点で起きました。" },
    "request":      { example: "I would like to request a window seat, please.", exampleJa: "窓側の席をお願いしたいのですが。" },
    "react":        { example: "How did she react when she heard the news?", exampleJa: "彼女はそのニュースを聞いてどう反応しましたか？" },
    "record":       { example: "They recorded the entire ceremony on video.", exampleJa: "彼らは式典全体をビデオに録画しました。" },
    "correct":      { example: "Please correct any grammar mistakes in my writing.", exampleJa: "文章の文法の間違いを直してください。" },
    "include":      { example: "The price includes breakfast and dinner.", exampleJa: "料金には朝食と夕食が含まれています。" },
    "form":         { example: "The children formed a circle in the classroom.", exampleJa: "子供たちは教室で輪を作りました。" },
    "judge":        { example: "You shouldn't judge people by their appearance.", exampleJa: "外見で人を判断すべきではありません。" },
    "multiply":     { example: "In math, multiply 6 by 7 to get 42.", exampleJa: "数学では6に7を掛けると42になります。" },
    "graduate":     { example: "She graduated from university with top honors.", exampleJa: "彼女は首席で大学を卒業しました。" },
    "deliver":      { example: "The package was delivered the next morning.", exampleJa: "荷物は翌朝届けられました。" },
    "separate":     { example: "Please separate the recyclables from the garbage.", exampleJa: "リサイクルと普通ごみを分けてください。" },
    "observe":      { example: "Scientists observed the behavior of the animals.", exampleJa: "科学者たちは動物の行動を観察しました。" },
    "command":      { example: "The general commanded his soldiers to advance.", exampleJa: "将軍は兵士たちに前進するよう命令しました。" },
    "perform":      { example: "The band performed live in front of 10,000 fans.", exampleJa: "そのバンドは10,000人のファンの前でライブを行いました。" },
    "translate":    { example: "Can you translate this sentence into Japanese?", exampleJa: "この文を日本語に翻訳してもらえますか？" },
    "depend":       { example: "The result depends on how much effort you put in.", exampleJa: "結果はどれだけ努力するかにかかっています。" },
    "exist":        { example: "Do aliens actually exist? No one really knows.", exampleJa: "宇宙人は本当に存在するのでしょうか？誰にもわかりません。" },
    "afford":       { example: "I can't afford to buy a new laptop right now.", exampleJa: "今は新しいパソコンを買う余裕がありません。" },

    // ── level-0 nouns ────────────────────────────────
    "technology":   { example: "Modern technology has made our lives more convenient.", exampleJa: "現代の技術は私たちの生活をより便利にしました。" },
    "economy":      { example: "The economy grew by 3% last year.", exampleJa: "昨年、経済は3%成長しました。" },
    "symbol":       { example: "The dove is a symbol of peace.", exampleJa: "ハトは平和の象徴です。" },
    "dialogue":     { example: "Open dialogue between the two countries is essential.", exampleJa: "両国間のオープンな対話が不可欠です。" },
    "logic":        { example: "His argument had no logic behind it.", exampleJa: "彼の主張には根拠となる論理がありませんでした。" },
    "interview":    { example: "She was very nervous before the job interview.", exampleJa: "彼女は就職面接の前にとても緊張していました。" },
    "automobile":   { example: "The automobile industry is shifting toward electric vehicles.", exampleJa: "自動車産業は電気自動車へのシフトが進んでいます。" },
    "bicycle":      { example: "He rides a bicycle to school every day.", exampleJa: "彼は毎日自転車で学校に行きます。" },
    "telephone":    { example: "She called him on the telephone to share the good news.", exampleJa: "彼女は電話で彼に良い知らせを伝えました。" },
    "television":   { example: "Many families watch television together in the evenings.", exampleJa: "多くの家族が夕方一緒にテレビを見ます。" },
    "microscope":   { example: "The scientist used a microscope to study the bacteria.", exampleJa: "科学者は細菌を研究するために顕微鏡を使いました。" },
    "telescope":    { example: "With this telescope you can see craters on the moon.", exampleJa: "この望遠鏡では月のクレーターが見えます。" },
    "microwave":    { example: "She heated up her lunch in the microwave.", exampleJa: "彼女は電子レンジでお昼ご飯を温めました。" },
    "microphone":   { example: "Please speak into the microphone so everyone can hear.", exampleJa: "全員に聞こえるようにマイクに向かって話してください。" },
    "democracy":    { example: "In a democracy, citizens vote for their leaders.", exampleJa: "民主主義では、市民が指導者を選びます。" },
    "confidence":   { example: "Public speaking helped her build her confidence.", exampleJa: "人前でのスピーチが彼女の自信を育てました。" },
    "emergency":    { example: "Call 119 in case of a medical emergency.", exampleJa: "医療上の緊急事態の場合は119に電話してください。" },
    "teamwork":     { example: "Good teamwork is the key to finishing the project.", exampleJa: "優れたチームワークがプロジェクト完成の鍵です。" },
    "network":      { example: "She built a strong professional network through conferences.", exampleJa: "彼女は会議を通じて強いビジネスネットワークを構築しました。" },
    "freedom":      { example: "Freedom of speech is a fundamental right.", exampleJa: "言論の自由は基本的な権利です。" },
    "wisdom":       { example: "His years of experience gave him great wisdom.", exampleJa: "長年の経験が彼に大きな知恵をもたらしました。" },
    "childhood":    { example: "She has many happy memories from her childhood.", exampleJa: "彼女は幼少期から多くの幸せな思い出を持っています。" },
    "friendship":   { example: "Their friendship has lasted for over twenty years.", exampleJa: "彼らの友情は20年以上続いています。" },
    "relationship": { example: "Good communication is the foundation of any relationship.", exampleJa: "良いコミュニケーションがあらゆる関係の基盤です。" },
    "quality":      { example: "We never compromise on the quality of our products.", exampleJa: "私たちは製品の質を妥協しません。" },
    "ability":      { example: "She has the ability to solve problems quickly.", exampleJa: "彼女は問題を素早く解決する能力があります。" },
    "reality":      { example: "The documentary showed the reality of life in the city.", exampleJa: "そのドキュメンタリーは都市生活の現実を映し出しました。" },
    "activity":     { example: "Swimming is my favorite outdoor activity.", exampleJa: "水泳は私の好きなアウトドア活動です。" },
    "difference":   { example: "What is the difference between these two words?", exampleJa: "この2つの単語の違いは何ですか？" },
    "evidence":     { example: "The police found strong evidence at the crime scene.", exampleJa: "警察は犯行現場で強力な証拠を発見しました。" },
    "influence":    { example: "Music has a big influence on people's emotions.", exampleJa: "音楽は人々の感情に大きな影響を与えます。" },
    "experience":   { example: "Working abroad was a valuable experience for me.", exampleJa: "海外での仕事は私にとって貴重な経験でした。" },
    "balance":      { example: "She struggled to maintain a balance between work and life.", exampleJa: "彼女は仕事と生活のバランスを保つのに苦労しました。" },
    "failure":      { example: "Every failure is a chance to learn and grow.", exampleJa: "失敗はすべて学び成長するチャンスです。" },
    "message":      { example: "Did you get my message? I sent it an hour ago.", exampleJa: "私のメッセージは届きましたか？1時間前に送りました。" },
    "habit":        { example: "Reading before bed is a good habit to develop.", exampleJa: "寝る前に読書するのは良い習慣です。" },
    "method":       { example: "This method is more efficient than the old one.", exampleJa: "この方法は以前のものより効率的です。" },
    "research":     { example: "She spent three years doing research on climate change.", exampleJa: "彼女は気候変動の研究に3年を費やしました。" },
    "tradition":    { example: "Eating soba on New Year's Eve is a Japanese tradition.", exampleJa: "大晦日にそばを食べるのは日本の伝統です。" },
    "goal":         { example: "My goal is to become fluent in English.", exampleJa: "私の目標は英語を流暢に話せるようになることです。" },
    "responsibility":{ example: "It is our responsibility to protect the environment.", exampleJa: "環境を守ることは私たちの責任です。" },
    "feedback":     { example: "Thank you for your honest feedback on my presentation.", exampleJa: "プレゼンへの率直なフィードバックをありがとうございます。" },
    "career":       { example: "She has built a successful career in medicine.", exampleJa: "彼女は医療の分野で成功したキャリアを築いています。" },
    "deadline":     { example: "We need to finish the report before the deadline.", exampleJa: "締め切りまでにレポートを仕上げなければなりません。" },
    "customer":     { example: "The store always puts the customer first.", exampleJa: "その店は常にお客様を最優先にしています。" },
    "stress":       { example: "Exercise is a great way to relieve stress.", exampleJa: "運動はストレスを解消する素晴らしい方法です。" },
    "climate":      { example: "The climate in this region is warm and humid.", exampleJa: "この地域の気候は温暖で湿度が高いです。" },
    "earthquake":   { example: "A powerful earthquake struck the coast yesterday.", exampleJa: "昨日、沿岸地域で強い地震が発生しました。" },
    "attitude":     { example: "A positive attitude can change the outcome.", exampleJa: "前向きな姿勢が結果を変えることがあります。" },
    "progress":     { example: "She made great progress in math this semester.", exampleJa: "彼女は今学期数学で大きな進歩を遂げました。" },
    "advantage":    { example: "Being bilingual is a great advantage in today's job market.", exampleJa: "バイリンガルであることは今日の就職市場で大きな強みです。" },
    "benefit":      { example: "Regular exercise has many health benefits.", exampleJa: "定期的な運動には多くの健康上のメリットがあります。" },
    "opportunity":  { example: "Study abroad is a great opportunity to grow.", exampleJa: "留学は成長する素晴らしい機会です。" },
    "situation":    { example: "Please assess the situation before making a decision.", exampleJa: "決断する前に状況を評価してください。" },
    "attention":    { example: "Please pay attention to the safety instructions.", exampleJa: "安全に関する指示に注意を払ってください。" },
    "government":   { example: "The government announced new economic policies.", exampleJa: "政府は新しい経済政策を発表しました。" },
    "nation":       { example: "Representatives from 50 nations attended the summit.", exampleJa: "50か国の代表がサミットに出席しました。" },
    "nature":       { example: "Spending time in nature helps reduce stress.", exampleJa: "自然の中で時間を過ごすとストレスが軽減されます。" },
    "culture":      { example: "Japan has a rich culture with a long history.", exampleJa: "日本は長い歴史を持つ豊かな文化があります。" },
    "language":     { example: "Learning a new language opens many doors.", exampleJa: "新しい言語を学ぶと多くの扉が開きます。" },
    "science":      { example: "Science helps us understand how the world works.", exampleJa: "科学は世界がどのように動くかを理解するのに役立ちます。" },
    "medicine":     { example: "She studies medicine to become a doctor.", exampleJa: "彼女は医師になるために医学を学んでいます。" },
    "memory":       { example: "I have a vivid memory of my first day at school.", exampleJa: "学校の初日の鮮明な記憶があります。" },
    "document":     { example: "You need to sign this document before leaving.", exampleJa: "帰る前にこの書類に署名する必要があります。" },
    "condition":    { example: "The patient's condition improved after surgery.", exampleJa: "患者の状態は手術後に改善しました。" },
    "question":     { example: "Do you have any questions about the assignment?", exampleJa: "課題について何か質問はありますか？" },
    "version":      { example: "Please update to the latest version of the app.", exampleJa: "アプリを最新バージョンにアップデートしてください。" },
    "universe":     { example: "The universe contains billions of galaxies.", exampleJa: "宇宙には数十億もの銀河があります。" },
    "airport":      { example: "We arrived at the airport two hours before departure.", exampleJa: "出発の2時間前に空港に到着しました。" },
    "passport":     { example: "Always keep your passport in a safe place when traveling.", exampleJa: "旅行中はパスポートを安全な場所に保管してください。" },
    "library":      { example: "She borrowed three books from the library.", exampleJa: "彼女は図書館から3冊の本を借りました。" },
    "dictionary":   { example: "Use a dictionary to look up words you don't know.", exampleJa: "わからない単語は辞書で調べてください。" },
    "engineer":     { example: "The engineer designed a more efficient engine.", exampleJa: "エンジニアはより効率的なエンジンを設計しました。" },
    "doctor":       { example: "The doctor advised him to get more sleep.", exampleJa: "医師は彼にもっと睡眠を取るよう勧めました。" },
    "artist":       { example: "The artist spent months creating the mural.", exampleJa: "アーティストは壁画の制作に何ヶ月もかけました。" },
    "musician":     { example: "She became a professional musician at age 20.", exampleJa: "彼女は20歳でプロの音楽家になりました。" },
    "writer":       { example: "The writer published her first novel at age 30.", exampleJa: "その作家は30歳で初の小説を出版しました。" },
    "leader":       { example: "A good leader listens to his or her team.", exampleJa: "良いリーダーはチームの声を聞きます。" },
    "employee":     { example: "The company values each and every employee.", exampleJa: "会社はすべての社員を大切にしています。" },
    "volunteer":    { example: "Many volunteers helped clean up the park.", exampleJa: "多くのボランティアが公園の清掃を手伝いました。" },
    "discovery":    { example: "The discovery of penicillin changed medicine forever.", exampleJa: "ペニシリンの発見は医学を永遠に変えました。" },
    "budget":       { example: "We need to stay within our monthly budget.", exampleJa: "月の予算内に収める必要があります。" },
    "sentence":     { example: "Please write a sentence using the new word.", exampleJa: "新しい単語を使って文を書いてください。" },
    "comfort":      { example: "The warm cup of tea brought her great comfort.", exampleJa: "温かいお茶が彼女に大きな安らぎをもたらしました。" },
    "effort":       { example: "Thank you for all your effort on this project.", exampleJa: "このプロジェクトへのすべての努力に感謝します。" },
    "confusion":    { example: "The unclear instructions caused a lot of confusion.", exampleJa: "不明瞭な説明が多くの混乱を引き起こしました。" },
    "grade":        { example: "She got top grades in every subject this year.", exampleJa: "彼女は今年すべての科目でトップの成績を収めました。" },
    "application":  { example: "Fill out the application form and submit it online.", exampleJa: "申し込み用紙に記入してオンラインで提出してください。" },

    // ── level-0 adjectives ───────────────────────────
    "unhappy":      { example: "He was unhappy with the result of the test.", exampleJa: "彼はテストの結果に不満でした。" },
    "unable":       { example: "She was unable to attend the meeting due to illness.", exampleJa: "彼女は病気のため会議に出席できませんでした。" },
    "underground":  { example: "The underground system in Tokyo is one of the busiest in the world.", exampleJa: "東京の地下鉄システムは世界で最も混雑しているものの一つです。" },
    "automatic":    { example: "The door opens automatically when you approach.", exampleJa: "近づくとドアが自動的に開きます。" },
    "economic":     { example: "The government introduced economic reforms.", exampleJa: "政府は経済改革を導入しました。" },
    "physical":     { example: "Regular physical activity is good for your health.", exampleJa: "定期的な身体活動は健康に良いです。" },
    "logical":      { example: "His decision was completely logical given the facts.", exampleJa: "事実を考慮すると彼の決断は完全に論理的でした。" },
    "incorrect":    { example: "The answer you gave was incorrect.", exampleJa: "あなたが出した答えは間違っていました。" },
    "impossible":   { example: "Nothing is impossible if you try hard enough.", exampleJa: "十分に努力すれば不可能なことは何もありません。" },
    "informal":     { example: "Friday's meeting will be informal, so dress casually.", exampleJa: "金曜日の会議は非公式なので、カジュアルな服装でどうぞ。" },
    "illegal":      { example: "It is illegal to use your phone while driving.", exampleJa: "運転中にスマホを使うことは違法です。" },
    "multiple":     { example: "There are multiple ways to solve this problem.", exampleJa: "この問題を解決する方法はいくつもあります。" },
    "uneasy":       { example: "She felt uneasy about the sudden change in plans.", exampleJa: "彼女は突然の計画変更に不安を感じました。" },
    "unlimited":    { example: "This plan offers unlimited data for a flat fee.", exampleJa: "このプランは定額で無制限のデータを提供しています。" },
    "unnecessary":  { example: "Please avoid unnecessary expenses this month.", exampleJa: "今月は不必要な出費を避けてください。" },
    "national":     { example: "The national park is a popular destination for hikers.", exampleJa: "その国立公園はハイカーに人気の目的地です。" },
    "cultural":     { example: "The festival was a cultural exchange between two nations.", exampleJa: "そのフェスティバルは2か国間の文化交流でした。" },
    "individual":   { example: "Each individual has a unique set of skills.", exampleJa: "それぞれの個人は独自のスキルセットを持っています。" },
    "negative":     { example: "Negative thinking can prevent you from reaching your goals.", exampleJa: "ネガティブな思考は目標達成を妨げることがあります。" },
    "colorful":     { example: "The market was full of colorful fruits and vegetables.", exampleJa: "市場はカラフルな果物や野菜でいっぱいでした。" },
    "homeless":     { example: "The charity provides shelter for homeless people.", exampleJa: "そのチャリティーはホームレスの人々に住居を提供しています。" },
    "useless":      { example: "Without a battery, the remote is useless.", exampleJa: "電池がなければリモコンは役に立ちません。" },
    "absent":       { example: "Three students were absent from class today.", exampleJa: "今日3人の生徒が授業を欠席しました。" },
    "perfect":      { example: "The weather was perfect for a picnic in the park.", exampleJa: "公園でのピクニックにはうってつけの天気でした。" },
    "expensive":    { example: "The restaurant was quite expensive but worth it.", exampleJa: "そのレストランはかなり高かったですが、その価値はありました。" },
    "dramatic":     { example: "There was a dramatic increase in sales last quarter.", exampleJa: "前四半期に劇的な売上の増加がありました。" },
    "enormous":     { example: "The new stadium is enormous — it seats 80,000 people.", exampleJa: "新しいスタジアムはとても大きく、8万人が収容できます。" },
    "previous":     { example: "Please refer to the previous chapter for details.", exampleJa: "詳細については前の章を参照してください。" },
    "ordinary":     { example: "It was just an ordinary Tuesday until the phone rang.", exampleJa: "電話が鳴るまで、ただの普通の火曜日でした。" },
    "necessary":    { example: "It is necessary to study hard to pass the exam.", exampleJa: "試験に合格するためには一生懸命勉強することが必要です。" },
    "primary":      { example: "The primary goal of the project is to reduce costs.", exampleJa: "このプロジェクトの主な目標はコスト削減です。" },
    "important":    { example: "It is important to get enough sleep every night.", exampleJa: "毎晩十分な睡眠を取ることが大切です。" },
    "global":       { example: "Climate change is a global problem we all face.", exampleJa: "気候変動は私たち全員が直面する地球規模の問題です。" },
    "regular":      { example: "She goes for a regular check-up every six months.", exampleJa: "彼女は6か月ごとに定期健診を受けています。" },
    "convenient":   { example: "Online shopping is very convenient for busy people.", exampleJa: "オンラインショッピングは忙しい人にとってとても便利です。" },
    "local":        { example: "We buy vegetables from a local farmer whenever possible.", exampleJa: "できるだけ地元の農家から野菜を買っています。" },
    "similar":      { example: "The two brothers look similar but have very different personalities.", exampleJa: "2人の兄弟は似た外見ですが性格はまったく異なります。" },
    "obvious":      { example: "It was obvious that she was nervous on stage.", exampleJa: "彼女がステージで緊張しているのは明らかでした。" },
    "equal":        { example: "All students deserve equal opportunities to succeed.", exampleJa: "すべての生徒が平等な成功の機会を持つべきです。" },
    "independent":  { example: "She became financially independent after getting a job.", exampleJa: "彼女は就職後、経済的に自立しました。" },
    "secure":       { example: "Make sure your password is secure.", exampleJa: "パスワードが安全であることを確認してください。" },
    "intelligent":  { example: "The intelligent student solved the problem in seconds.", exampleJa: "その聡明な生徒は数秒で問題を解きました。" },
    "brief":        { example: "Please give a brief summary of the report.", exampleJa: "レポートの簡単な要約を述べてください。" },
    "certain":      { example: "Are you certain that you locked the door?", exampleJa: "ドアに鍵をかけたのは確かですか？" },
    "clear":        { example: "The instructions were not clear, so I was confused.", exampleJa: "説明がわかりにくかったので混乱しました。" },
    "formal":       { example: "Please wear formal attire to the graduation ceremony.", exampleJa: "卒業式にはフォーマルな服装でご参加ください。" },
    "major":        { example: "She made a major decision to change careers.", exampleJa: "彼女はキャリアチェンジという大きな決断をしました。" },
    "final":        { example: "Tomorrow is the final day to submit your application.", exampleJa: "明日が申し込みの最終日です。" },

    // ── level-0 adverbs ──────────────────────────────
    "completely":   { example: "I completely forgot about our appointment. I'm so sorry.", exampleJa: "約束のことをすっかり忘れてしまいました。本当に申し訳ありません。" },
    "simply":       { example: "Simply press the button and the machine will start.", exampleJa: "ボタンを押すだけで機械が起動します。" },
    "forward":      { example: "She looked forward to the upcoming holiday.", exampleJa: "彼女は迫ってくる休日を楽しみにしていました。" },
    "backward":     { example: "He glanced backward to make sure no one was following.", exampleJa: "誰もついてきていないか確認するために後ろを振り返りました。" },
    "afterward":    { example: "We had dinner first and went for a walk afterward.", exampleJa: "最初に夕食を食べ、その後で散歩に行きました。" },
  });
})();
