const fs = require('fs');
const ex = new Set(fs.readFileSync('existing_words.txt','utf8').split('\n').map(w=>w.trim()).filter(Boolean));

const cands = [
'abolitionism','absolutism','activism','agnosticism','altruism','anarchism','authoritarianism','behaviorism','centrism','chauvinism','collectivism','conservatism','consumerism','cynicism','defeatism','determinism','dogmatism','dualism','egalitarianism','elitism','empiricism','environmentalism','escapism','ethnocentrism','existentialism','extremism','fanaticism','fascism','federalism','feminism','feudalism','formalism','fundamentalism','hedonism','holism','humanism','idealism','imperialism','individualism','isolationism','libertarianism','materialism','militarism','minimalism','monism','moralism','mysticism','narcissism','nationalism','naturalism','nihilism','objectivism','opportunism','optimism','pacifism','perfectionism','pessimism','pluralism','populism','positivism','protectionism','rationalism','realism','reformism','relativism','romanticism','secularism','separatism','skepticism','structuralism','subjectivism','theism','totalitarianism','utopianism','voluntarism',
'aerobiology','audiology','bacteriology','biochemistry','bioethics','chronobiology','climatology','criminology','cryptology','cytology','dendrology','dermatology','endocrinology','entomology','epistemology','ethnology','geomorphology','gerontology','graphology','hematology','hydrology','ichthyology','kinesiology','lexicology','limnology','lithology','malacology','microbiology','mineralogy','mycology','neuropathology','numismatics','ornithology','otolaryngology','paleoclimatology','parasitology','penology','petrology','phonology','phrenology','primatology','seismology','semiology','sinology','speleology','urology',
'adobe','amphitheater','aqueduct','arcade','archway','atrium','baroque','basilica','battlement','belfry','buttress','cloister','colonnade','cornice','crenellation','cupola','drawbridge','escarpment','facade','foyer','frieze','gargoyle','gazebo','keystone','lintel','loggia','mausoleum','minaret','mullion','nave','obelisk','pagoda','parapet','pediment','pergola','pinnacle','portcullis','portico','rampart','rotunda','spire','stucco','transept','trellis','turret','vestibule','viaduct',
'aria','arpeggio','atonal','baritone','cadenza','cantata','choreography','chromatic','counterpoint','crescendo','dissonant','falsetto','fugue','harmonic','interlude','lullaby','madrigal','mezzo','nocturne','octave','operatic','orchestral','overture','percussionist','polyphony','prelude','repertoire','resonance','rhapsody','serenade','soprano','staccato','symphony','tempo','timbre','tonality','troubadour','vibrato','virtuoso',
'blanch','braise','consomme','coulis','couscous','crouton','culinary','deglaze','emulsify','ferment','flambe','fricassee','ganache','gastronomy','glaze','gnocchi','gratinate','infuse','julienne','macerate','marinade','meringue','mousse','paella','patisserie','poach','ragout','ratatouille','reduction','risotto','saute','simmer','sommelier','sorbet','tartare','tempura','tiramisu','umami','vinaigrette','zabaglione',
'aerosol','albedo','alluvium','anaerobic','aquifer','biodegradable','biome','chlorophyll','compost','convection','decompose','deforestation','desertification','drought','eutrophication','fissure','floodplain','geothermal','glacier','groundwater','habitat','hydrosphere','lithosphere','mangrove','peatland','permafrost','photovoltaic','plateau','precipitation','primordial','rainforest','riparian','savanna','sediment','sequester','solstice','stratum','subduction','temperate','terrestrial','thermocline','tundra','watershed','wetland',
'agile','asynchronous','bandwidth','binary','blockchain','boolean','codebase','compilation','container','daemon','debugger','decentralized','deploy','deprecate','deterministic','devops','distributed','encryption','endpoint','framework','heuristic','immutable','infrastructure','integration','iteration','latency','middleware','modular','optimization','payload','pipeline','plugin','redundant','refactor','regex','repository','scalable','serialization','singleton','socket','syntax','throughput','timestamp','tokenize','transpile','tuple','virtualize','webhook',
'aerobic','agility','altitude','cardiovascular','circuit','conditioning','coordination','endurance','ergonomic','exertion','flexibility','glycogen','hydration','hypertrophy','lactic','locomotion','maximal','mobility','momentum','muscular','overtraining','periodization','plyometric','posture','proprioception','recovery','repetition','resistance','stamina','stretching','symmetry',
'absenteeism','accrual','actuarial','amortize','antitrust','arrears','assay','bailout','barter','bondholder','brokerage','buyout','consortium','copayment','debenture','deregulate','disbursement','divestiture','dossier','downturn','encumbrance','endowment','freelance','goodwill','hedging','incumbent','indemnify','installment','lobbying','loophole','macroeconomic','microeconomic','patent','payroll','profitability','quota','reimbursement','remuneration','restructure','severance','shareholder','solvent','valuation','wholesale','arraign','barrister','codicil','enactment','litigant','perjure','probate','recuse',
'ailment','allergen','analgesia','antipsychotic','contagion','cortisol','delirium','diuretic','fibromyalgia','inhibitor','mitochondria','opioid','pediatrics','sedative','seizure','serotonin','therapist','vitals',
'artisan','bespoke','boutique','capsule','charisma','clutter','commute','demographic','detox','diplomat','entrepreneur','etiquette','frugal','glamour','gourmet','hygiene','influencer','leisure','luxury','meditation','mentor','mindfulness','mingle','nomadic','nurture','pamper','pastiche','pilgrimage','precaution','preserve','recycle','renovation','retreat','ritual','sanctuary','therapeutic','trendy','wellness','workshop',
'abeyance','abrade','allocution','anoint','aspersion','consternation','cull','despotism','ebullience','halcyon','impenitent','indigent','ingenuous','latent','laudable','munificent','phlegmatic','reverence','tortuous','vituperate',
'accreditation','alienate','annotation','appraisal','arbitration','archaic','ascertain','assimilation','bipartisan','bureaucracy','catalyst','cognition','coherent','comorbidity','complementary','comprehension','computation','congenital','contingency','convergence','correlation','criterion','deficit','delineate','deterrent','dichotomy','discourse','disparity','divergence','diversification','doctrine','empirical','encapsulate','enumerate','extrapolate','facilitation','fallacy','feasibility','fluctuate','formulation','fragmentation','generalize','globalization','governance','hypothesis','implication','incentive','inherent','interdependence','interpretation','intervention','intuition','justification','leverage','marginalize','mechanism','methodology','mitigation','mobilize','motivation','narrative','normalization','paradigm','pedagogy','perception','preliminary','prevalence','projection','proportional','provision','rationale','recognition','reinforcement','relevance','resilience','restriction','retention','rigor','scrutiny','solidarity','specification','standardize','stimulus','stratification','sustainability','synthesis','transparency','validation','variability',
'accountability','affiliation','allegiance','allocation','amnesty','annexation','aristocracy','authoritarian','ballot','bicameral','bureaucrat','cabinet','campaign','candidate','caucus','censorship','charismatic','citizenship','coalition','coercion','colonize','communal','constituency','constitutional','coup','curfew','defection','deliberation','democratize','despot','devolution','dictatorship','diplomacy','disenfranchise','dissent','doctrine','dynastic','electoral','embargo','enfranchise','faction','geopolitics','globalize','hierarchy','ideology','impeachment','jurisdiction','legislation','legitimacy','manifesto','militarize','oligarch','partisanship','patronage','polarize','policymaker','polity','propaganda','ratification','referendum','regime','repression','secession','sovereignty','suffrage','supranational','surveillance','tyranny','unicameral',
'affective','ambivalent','amygdala','attribution','autism','burnout','catharsis','cognitive','compulsion','conformity','consciousness','depression','desensitize','dialectical','dissociation','dopamine','ego','empathy','esteem','fixation','gratification','heritability','identity','impulse','inhibition','introspection','mania','neurosis','obsession','perception','phobia','placebo','projection','psychosomatic','rationalization','repression','schema','socialization','stigma','stoicism','subconscious','temperament','unconscious',
'aesthetics','antinomy','axiom','categorical','causation','coherentism','consequentialism','contextualism','deontology','dialectic','epistemology','fallibilism','fatalism','foundationalism','hermeneutics','immanence','inductive','kantian','logic','metaphysics','ontology','pantheism','phenomenology','reductionism','teleology','virtue',
'acceleration','acoustics','adiabatic','allotrope','anion','antimatter','astrophysics','atmosphere','atomic','biodiversity','biosphere','capacitance','cation','centripetal','chromatin','combustion','condensation','covalent','crystallography','cytoplasm','diffraction','dipole','endothermic','entropy','evolution','exothermic','exponent','ferromagnetism','fluorescence','friction','gamete','genome','gravitation','hormone','induction','ionic','kinetic','luminescence','magnetism','mitosis','molecule','mutation','neutron','nucleotide','optics','osmosis','oxidation','photon','polarization','polymer','proton','quantum','radioactive','receptor','refraction','semiconductor','solubility','spectrum','static','subatomic','superconductor','thermodynamics','transcription','ultraviolet','viscosity',
'allegory','alliteration','allusion','anachronism','anapest','anaphora','antithesis','archetype','assonance','chiasmus','circumlocution','connotation','dactyl','denouement','denotation','elegy','ellipsis','epic','epigraph','epiphany','epistolary','euphemism','exposition','fable','figurative','flashback','foreshadow','genre','hamartia','hyperbole','imagery','intertextuality','irony','juxtaposition','litotes','lyric','metonymy','motif','narrate','ode','onomatopoeia','oxymoron','parable','paradox','parody','pathos','personify','prose','protagonist','rhetoric','satire','simile','soliloquy','sonnet','stanza','synecdoche','theme','tragedy','vernacular',
];

// 追加候補バッチ2
const cands2 = [
'abate','accommodate','accuse','acknowledge','administer','advocate','affiliate','aggravate','alleviate','amend','annex','appease','apprehend','approximate','articulate','aspire','attain','authenticate','authorize','automate','bolster','boycott','campaign','centralize','certify','clarify','collaborate','commence','compile','comply','compel','condemn','confront','consolidate','contemplate','convene','correlate','counteract','cultivate','curb','deem','defame','delegate','demote','denounce','designate','detect','deviate','diminish','disclaim','discriminate','dismantle','displace','disseminate','divert','eliminate','empower','endorse','enforce','enhance','enrich','envisage','enumerate','evaluate','exaggerate','exclude','exemplify','exhaust','exile','exploit','facilitate','fluctuate','formulate','foster','generate','govern','halt','hinder','illuminate','impose','incentivize','infer','inspect','instill','launch','leverage','mandate','manipulate','mediate','monitor','offset','overcome','persevere','portray','precede','presume','prioritize','prohibit','pursue','ratify','reinforce','reiterate','revoke','scrutinize','signal','specify','stipulate','streamline','sustain','terminate','underlie','undertake','utilize','verify',
'accessible','adverse','ambivalent','ample','arduous','assertive','authentic','autonomous','coherent','compelling','comprehensive','concise','consequential','credible','cumulative','deliberate','detrimental','discernible','diverse','durable','eloquent','equivalent','excessive','exclusive','exemplary','expedient','extensive','feasible','forthcoming','gradual','imperative','inconsistent','inevitable','inherent','innovative','integral','intensive','lucid','meticulous','minimal','negligible','neutral','nominal','objective','optimal','paramount','plausible','preliminary','prevalent','proactive','proficient','progressive','rational','reluctant','rigid','robust','sequential','sophisticated','steadfast','substantial','sufficient','systematic','tactical','tentative','transparent','trivial','uniform','versatile','viable','voluntary',
'accountability','acquisition','adaptation','ambiguity','arbitration','assertion','assumption','authorization','benchmark','burden','capacity','commitment','complexity','compliance','compromise','constraint','continuum','convention','credibility','deficiency','delegation','deviation','discrepancy','disparity','disposition','distinction','diversity','duration','efficiency','emergence','empowerment','exclusion','facilitation','flexibility','governance','guideline','implementation','inclusion','integrity','interdependence','justification','liability','limitation','mechanism','methodology','motivation','negotiation','neutrality','obligation','opposition','participation','perseverance','perspective','portfolio','premise','procurement','proficiency','progression','projection','protocol','provision','qualification','rationale','recommendation','reinforcement','relevance','resilience','resolution','restraint','revision','solidarity','specification','stability','structure','submission','substitution','synthesis','transition','uncertainty',
'acceleration','acoustics','allotrope','anion','antimatter','astrophysics','atmosphere','atomic','biodiversity','biosphere','capacitance','cation','centripetal','chromatin','combustion','condensation','covalent','crystallography','cytoplasm','diffraction','dipole','endothermic','entropy','evolution','exothermic','ferromagnetism','fluorescence','friction','gamete','genome','gravitation','induction','ionic','kinetic','luminescence','magnetism','mitosis','molecule','mutation','neutron','nucleotide','optics','osmosis','oxidation','photon','polarization','polymer','proton','quantum','radioactive','receptor','refraction','semiconductor','solubility','spectrum','static','subatomic','superconductor','thermodynamics','transcription','ultraviolet','viscosity',
'affirmation','agency','anxiety','aptitude','assessment','attentive','auditory','behavioral','burnout','comprehension','constructive','curriculum','differentiated','empathy','engagement','experiential','formative','growth','heuristic','inquiry','interdisciplinary','intrinsic','kinesthetic','literacy','metacognition','neurodiversity','numeracy','personalized','resilience','rubric','scaffolding','self-efficacy','socioemotional','summative','thematic','transferable',
'agility','alignment','bottleneck','brainstorm','breakthrough','cascade','channel','collaborate','competency','contingency','dashboard','deadline','deliverable','deployment','disruption','diversify','escalate','execution','feedback','forecasting','granular','headcount','ideation','impact','initiative','insight','milestone','mitigation','onboard','optimize','outcome','performance','pipeline','pivot','prioritize','roadmap','rollout','scalable','scope','sprint','synergy','target','throughput','timeline','traction','velocity','venture','workstream',
'allegory','alliteration','anachronism','anapest','anaphora','antithesis','archetype','assonance','chiasmus','circumlocution','connotation','dactyl','denouement','denotation','elegy','ellipsis','epigraph','epiphany','epistolary','euphemism','exposition','fable','figurative','flashback','foreshadow','hamartia','imagery','intertextuality','juxtaposition','litotes','lyric','metonymy','motif','narrate','ode','onomatopoeia','oxymoron','parable','paradox','parody','pathos','personify','prose','protagonist','rhetoric','satire','simile','soliloquy','sonnet','stanza','synecdoche','tragedy','vernacular',
'adrenaline','anthology','atmosphere','authenticity','blockbuster','cameo','caricature','catharsis','cinematic','cliche','collage','commentary','connotation','cult','curator','debut','dystopia','editorial','ensemble','folklore','franchise','genre','grotesque','iconography','illustration','improv','installment','irony','juxtapose','legend','montage','nostalgia','parody','realism','satire','spectacle','surrealism','theatrical','utopia','vignette',
'anthropocene','biofuel','biomass','circular','conservation','decarbonize','degrowth','emission','footprint','fossil','geoengineering','greenhouse','impervious','invasive','monoculture','naturalize','offsets','organic','ozone','pollutant','remediation','renewable','rewilding','runoff','stewardship','toxin','upcycle','urbanization',
'acupuncture','amenity','analytics','appreciation','branding','capability','clarity','compassion','creativity','customization','ecosystem','equity','fulfillment','mentorship','mindset','networking','nonprofit','onboarding','outreach','productivity','self-care','simplicity','storytelling','vulnerability','wellbeing',
'aesthetics','antinomy','axiom','categorical','causation','coherentism','consequentialism','contextualism','deontology','fallibilism','fatalism','foundationalism','hermeneutics','immanence','inductive','kantian','ontology','pantheism','phenomenology','reductionism','teleology','virtue',
'affective','amygdala','attribution','autism','catharsis','compulsion','conformity','consciousness','desensitize','dialectical','dissociation','dopamine','ego','esteem','fixation','gratification','heritability','identity','impulse','inhibition','introspection','mania','neurosis','obsession','phobia','placebo','projection','psychosomatic','rationalization','schema','socialization','stigma','subconscious','temperament','unconscious',
'affiliation','allegiance','amnesty','annexation','aristocracy','authoritarian','ballot','bicameral','bureaucrat','cabinet','candidate','caucus','censorship','charismatic','citizenship','coalition','coercion','colonize','communal','constituency','constitutional','coup','curfew','defection','democratize','despot','devolution','dictatorship','diplomacy','disenfranchise','dissent','dynastic','electoral','enfranchise','faction','geopolitics','hierarchy','ideology','impeachment','jurisdiction','legislation','legitimacy','manifesto','militarize','oligarch','partisanship','patronage','polarize','polity','propaganda','ratification','regime','repression','secession','sovereignty','suffrage','supranational','tyranny','unicameral',
];

const allCands = [...new Set([...cands, ...cands2])];
const missing = allCands.filter(w => !ex.has(w));
console.log('Total missing:', missing.length);
fs.writeFileSync('missing_candidates.txt', missing.join('\n'));
console.log('First 50:', missing.slice(0,50).join(', '));
