const fs = require('fs');
const ex = new Set(fs.readFileSync('existing_words.txt','utf8').split('\n').map(w=>w.trim()).filter(Boolean));

const c3 = [
// 料理
'aioli','antipasto','arancini','bisque','borscht','bouillabaisse','bruschetta','burrata','carpaccio','cassoulet','ceviche','chiffonade','chimichurri','clafoutis','compote','concasse','confit','creme-brulee','dauphinoise','degustation','duxelles','escabeche','escargot','filo','focaccia','fondant','frangipane','fromage','gazpacho','gelato','gravlax','gruyere','guanciale','hollandaise','hummus','kumquat','lavash','linguine','manchego','masala','mezze','mirepoix','miso','morel','mortadella','moussaka','naan','ossobuco','pancetta','panko','passata','pate','pecorino','pesto','pilaf','polenta','porcini','prosciutto','quenelle','quiche','ravioli','rillette','romesco','roulade','saltimbocca','semifreddo','stroganoff','tagliatelle','tapas','tapenade','tartine','terrine','tortellini','vermicelli',
// 音楽
'accelerando','adagio','allegretto','allegro','andante','appoggiatura','bel-canto','cantabile','capriccio','coda','coloratura','con-brio','continuo','da-capo','diminuendo','divisi','dolce','dorian','dynamics','fermata','forte','fortissimo','glissando','harmony','homophony','improvise','intermezzo','largo','legato','lento','leitmotif','moderato','molto','morendo','ostinato','pentatonic','pianissimo','pizzicato','poco','portamento','prestissimo','presto','rallentando','recitative','refrain','requiem','ritenuto','rubato','scherzo','senza','sforzando','slur','solfege','subito','tarantella','tenuto','tremolo','trill','unison','vivace',
// 建築
'apse','arabesque','architrave','arris','ashlar','baldachin','balusters','bartisan','bastion','bracket','campanile','cantilever','capital','catenary','chancel','chevron','clerestory','coving','diaper','dormer','drum','entablature','fanlight','fascia','fenestration','gable','gallery','groin','hipped','impost','intrados','jamb','lancet','lantern','lunette','mansard','merlon','metope','motte','narthex','newel','oculus','oriel','pavilion','pier','pilaster','pillar','plinth','quoin','rafter','relief','render','respond','reveal','rustication','sill','soffit','squinch','strut','tracery','trefoil','triforium','tympanum','undercroft','voussoir','wainscot','ziggurat',
// 哲学
'abduction','absurdism','agape','alienation','animism','anthropocentrism','aporia','archai','authenticity','axiology','banality','causa-sui','cognitivism','compatibilism','correlationism','cosmology','dasein','deconstruction','deflationary','deontic','disjunctivism','dispositionalism','eudaimonia','fallibilism','fatalism','finitude','flux','functionalism','gnosis','hubris','immanence','impermanence','intentionality','intersubjectivity','isomorphism','katharsis','kenosis','libertarian','logos','logicism','meaningfulness','modality','monad','negation','noesis','noumenon','occasionalism','ontology','panentheism','paternalism','perspectivism','phenomenology','physicalism','platonism','presentism','processism','projectivism','psychologism','reductionism','representationalism','retributivism','revisionism','scholasticism','semantics','semiosis','situatedness','solipsism','spatiality','supervenience','syncretism','teleology','temporality','theodicy','transcendentalism','utilitarian',
// 科学
'abiogenesis','absorption','accretion','allele','allometry','alveolus','amino-acid','amorphous','amplitude','angiosperm','anisotropy','anode','antibody','aphelion','apoptosis','asthenosphere','autoimmune','axon','baryon','bathymetry','benthic','biogeography','bioinformatics','biosynthesis','blastocyst','boson','calorie','carbohydrate','carcinoma','carnivore','cathode','celestial','centrifugal','chirality','cholesterol','cilia','cloning','codon','comet','commensalism','conductance','convergent','covalence','cytokine','cytosol','dendrite','density','depolarize','diastole','diorite','diploid','dissipation','divergent','dominant','echolocation','effusion','electrolysis','electromagnetism','embryology','emergent','enantiomer','endorphin','enzyme','epistasis','eukaryote','evaporation','excretion','exoplanet','extinction','extremophile','fermentation','fibril','fissure','flagellum','food-web','fulcrum','gene','geocentric','geophysics','germination','glycerol','haploid','hemoglobin','herbivore','heredity','homeostasis','hydration','hygroscopic','implosion','inertia','infrared','inorganic','insulation','intercellular','intron','isomer','isothermal','keratin','kinetics','leach','leucocyte','ligand','lignin','lipid','longitude','luminosity','lysis','macrophage','meiosis','membrane','mesosphere','metamorphism','microtubule','migration','mitochondria','monomer','morphogenesis','myelin','natural-selection','neurotransmitter','nucleobase','nucleotide','nymph','organelle','ovulation','parasitism','perihelion','permeable','phenotype','photoreceptor','phylogeny','phytoplankton','plasma','plasmid','pollination','population','predation','prokaryote','protein','puberty','recessive','redox','reflex','replication','respiration','ribosome','rotation','salinity','sclerosis','speciation','spore','substrate','succession','symbiosis','synapse','tectonic','transpiration','trophic','tumor','valence','vascular','vector','ventricle','virology','xenobiotic','zygote',
// ビジネス・法律・金融（より詳細）
'accrual','actuarial','adjudicate','affidavit','annuity','appraisal','arbitrage','austerity','bilateral','claimant','class-action','clearance','collateral','commodity','consortium','copayment','culpable','custodian','debenture','deregulate','derivative','disbursement','divestiture','dossier','downturn','encumbrance','fiscal','franchise','garnish','goodwill','grievance','hedging','hierarchy','indemnify','insolvency','installment','intangible','invoice','liquidate','loophole','macroeconomic','microeconomic','milestone','mortgage','multilateral','oligopoly','outsource','overhead','patent','payroll','procurement','profitability','proxy','quota','reimbursement','remuneration','restructure','revenue','severance','shareholder','solvent','speculation','stakeholder','subsidiary','surplus','tariff','threshold','turnover','underwrite','valuation','variance','write-off',
// 医学・心理（より詳細）
'ailment','allergen','analgesia','anesthesia','antigen','antipsychotic','autopsy','benign','biopsy','carcinogen','cardiology','chronic','cognition','comorbidity','congenital','contagion','cortisol','debilitate','dehydration','delirium','dementia','diagnosis','dialysis','diuretic','empirical','endocrine','epidemiology','etiology','euphoria','fibromyalgia','genetics','hallucinate','hypnosis','inflammation','inhibitor','insomnia','lethargy','malignant','metabolism','narcosis','neurology','oncology','opioid','pathogen','pediatrics','pharmacology','prognosis','psychiatry','psychosis','quarantine','radiology','rehabilitation','sedative','seizure','serotonin','somatic','syndrome','therapist','toxicology','vaccination','vitals','withdrawal',
// 社会・文化
'acculturation','affirmative','agglomerate','alienation','anomie','apartheid','archetype','assimilation','attribution','autonomy','bohemian','bourgeoisie','capitalism','cognitivism','communitarianism','conformity','constructivism','cosmopolitan','counterculture','critique','cultural','diaspora','differentiation','discourse','egalitarian','emancipation','ethnicity','ethos','exclusion','globalization','hegemony','homogenization','hybridization','identity','ideology','inclusion','indigenize','inequality','integration','intersectionality','kinship','liberalization','marginalization','meritocracy','modernization','multiculturalism','nativism','normalization','oppression','patriarchy','postcolonial','postmodern','prejudice','privilege','proletariat','radicalization','rationalization','secularization','socialization','solidarity','sovereignty','stereotype','stigmatization','stratification','subculture','systemic','tokenism','tribalism','urbanization','xenophobia',
// 環境・気候
'adaptation','aerosol','albedo','alluvium','aquifer','biofuel','biomass','biosphere','carbon-neutral','chlorophyll','compost','convection','decarbonize','decompose','deforestation','desertification','eutrophication','floodplain','geoengineering','glacier','groundwater','hydrosphere','lithosphere','mangrove','mitigation','monoculture','peatland','permafrost','photovoltaic','plateau','pollutant','precipitation','primordial','rainforest','remediation','renewable','rewilding','riparian','runoff','savanna','sediment','sequester','solstice','stratum','subduction','temperate','terrestrial','thermocline','tundra','watershed','wetland',
// IT・デジタル
'agile','algorithm','asynchronous','bandwidth','binary','blockchain','boolean','codebase','compilation','container','daemon','debugger','decentralized','deploy','deprecate','deterministic','devops','distributed','encryption','endpoint','framework','heuristic','immutable','infrastructure','iteration','latency','middleware','modular','optimization','payload','pipeline','plugin','redundant','refactor','regex','repository','scalable','serialization','singleton','socket','syntax','throughput','timestamp','tokenize','transpile','tuple','virtualize','webhook',
// 教育・認知
'affirmation','agency','aptitude','assessment','attentive','auditory','behavioral','burnout','catharsis','comprehension','constructive','curriculum','differentiated','engagement','experiential','formative','growth','heuristic','inquiry','interdisciplinary','intrinsic','kinesthetic','literacy','metacognition','neurodiversity','numeracy','pedagogy','personalized','rubric','scaffolding','self-efficacy','socioemotional','summative','thematic','transferable',
// 文学・修辞学
'anachronism','anapest','anaphora','antithesis','archetype','assonance','chiasmus','circumlocution','connotation','dactyl','denotation','ellipsis','epigraph','epiphany','epistolary','euphemism','exposition','fable','figurative','flashback','foreshadow','genre','hamartia','imagery','intertextuality','irony','juxtaposition','litotes','lyric','metonymy','motif','narrate','ode','onomatopoeia','oxymoron','parable','paradox','parody','pathos','personify','prose','protagonist','rhetoric','satire','simile','soliloquy','sonnet','stanza','synecdoche','tragedy','vernacular',
// スポーツ・フィットネス
'aerobic','agility','altitude','cardiovascular','circuit','conditioning','coordination','endurance','ergonomic','exertion','flexibility','glycogen','hydration','hypertrophy','lactic','locomotion','maximal','mobility','momentum','muscular','overtraining','periodization','plyometric','posture','proprioception','recovery','repetition','resistance','stamina','stretching','symmetry',
];

const missing = [...new Set(c3)].filter(w => !ex.has(w));
console.log('New missing from batch3:', missing.length);
const prev = fs.readFileSync('missing_candidates.txt','utf8').split('\n').filter(Boolean);
const all = [...new Set([...prev, ...missing])];
console.log('Total combined:', all.length);
fs.writeFileSync('missing_candidates.txt', all.join('\n'));
